### ISSUE TITLE
[designdoc] Create `PagerankGraph`

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1020]
The core SourceCred infrastructure exists to:
1. Create Contribution Graphs which represent contributions to a project as
   nodes in the graph, with edges representing relationships between
   contributions
2. Run a (PageRank-derived) credit attribution algorithm on those graphs,
   assigning a score to every node in the graph. (Normalization is also
   optionally applied, so that e.g. the users' scores can sum to 1000.)

For 1., we have the [Graph class] which provides an object-oriented interface
for creating graphs. The graph has a thoughtful interface that supports
common operations like filtering by prefix, or exploring the 'neighborhood' of
a node. The graph class also provides utility functionality, notably the
ability to (de)serialize graphs, check them for equality, copy them, etc.

[Graph class]: https://github.com/sourcecred/sourcecred/blob/bbe773bb67ef6132554335c643d676fb9d4fef9d/src/core/graph.js#L71

For 2., we have a variety of low-level functions which transform a Graph into a
markov chain, and support taking running PageRank steps on that markov chain.
We also have a [pagerank invocation] that takes the graph, along with
non-serializable arguments like an evaluator function, and outputs a
non-serializable `PagerankNodeDecomposition.` The `PagerankNodeDecomposition`
provides score information, in terms of both the nodes in the graph, and the
`Connection`s in the markov chain.

[pagerank invocation]: https://github.com/sourcecred/sourcecred/blob/bbe773bb67ef6132554335c643d676fb9d4fef9d/src/analysis/pagerank.js#L46

In contrast to 1., 2. has a messy interface. The `Connection`s and `ScoredConnection`s
are new concepts that mostly overlap with edges; there's no support for serializing
the inputs and outputs, the API is split across multiple files in a subfolder.

The non-serializability of the inputs and outputs to `pagerank` are a blocking
issue for #967. We could just write a serializer for
`PagerankNodeDecomposition`, which was prototyped in #995, or we could slightly
modify the interface so that we serialize different data, which is discussed at
length in #1004. However, having spent time exploring implementation of these
alternatives (cf #1008, #1009, #1010, #1012), I think we
should instead re-imagine how we handle step 2 entirely.

I have the following goals in mind:

1. The API for running PageRank should be clean, and easy to depend on. It
   should live in `core/`, rather than in `analysis/` (and it should merit
   inclusion in `core/`) 
2. The inputs and outputs to PageRank should both be serializable.
   - (Introspecting on the final scores often requires the full inputs, e.g. to
     know how a node acquired its score, you must see the edge weights.)
3. To the extent possible, the PageRank API should re-use the conceputal
   vocabulary of the `Graph`, rather than adding a new set of concepts and
   primitives.
4. It should be easy to re-use PageRank state. E.g. if the user has scored a
   graph and changes the weights, they should be able to quickly re-run
   PageRank with the new scores. 
   - (Assertion: assuming that the user has chosen a good convergence
     threshold, and that the graph is not particularly perverse, re-using the
     scores shouldn't change the final output.)
  
With these goals in mind, I propose we create a `PagerankGraph` class, which is
basically a wrapper around a `Graph` that supports adding weights to the edges,
running PageRank on that graph, and retrieving scores and score decompositions.

Below is an API sketch of `PagerankGraph`. It supports all the functionality
needed to replace our existing Pagerank APIs. If implemented, we can re-factor
the frontend, including `PagerankTable`, to directly consume a `PagerankGraph`.

```js
export type {EdgeWeight} from "./attribution/graphToMarkovChain";
export type EdgeEvaluator = (Edge) => EdgeWeight;

export type ScoreNormalizationStrategy = ScoreByConstantTotal;
// Score so that the sum of all nodes matching `nodePrefix` is equal to `total`
export type ScoreByConstantTotal = {|
  +type: "SCORE_BY_CONSTANT_TOTAL",
  +total: number,
  +nodePrefix: NodeAddressT,
|};

/**
 * A PagerankGraph is a wrapper around a Graph that makes it convenient to
 * compute PageRank scores on that graph. It supports stateful operations like
 * changing the weighting of the graph, and re-running PageRank using the
 * previous distribution as a starting point. It also supports decomposing a
 * node's score in terms of its neighbors, and serializing the weighted and
 * scored state.
 *
 * By default, PageRank scores represent a distribution over the nodes, i.e.
 * the scores sum to `1`. Optionally, you may provide a
 * ScoreNormalizationStrategy, which specifies a different way to normalize the
 * scores. For example, if you want the sum of all nodes matching a given
 * prefix to sum to 1000, you can specify that via a
 * ScoreNormalizationStrategy.
 */
export class PagerankGraph {
  scores: Map<NodeAddressT, number>; // The score for each node
  edgeWeights: Map<EdgeAddressT, EdgeWeight>; // The weight for each edge
  syntheticLoopWeight: number;
  totalOutWeight: Map<NodeAddressT, number>; // caching this is convenient

  constructor(
    // The Graph backing the PagerankGraph. Mutating the Graph invalidates
    // the PagerankGraph (can ensure this either by putting a .seal() method
    // on Graph, or exposing the modification count, or by having PagerankGraph
    // create a copy on construction).
    graph: Graph,
    scoreNormalizationStrategy: ?ScoreNormalizationStrategy,
    // The synthetic loop weight; uses a sane default if not provided
    syntheticLoopWeight: ?number,
    // The scores; defaults to uniform distribution if not provided
    scores: ?Map<NodeAddressT, number>,
    // The edge weights; defaults to {toWeight: 1, froWeight:1} for each edge if
    // not provided
    edgeWeights: ?Map<EdgeAddressT, EdgeWeight>
  ): void { }

  hasNode(a: NodeAddressT): boolean { }

  export type ScoredNode = {|
    +score: number,
    +node: NodeAddressT,
  |};

  *nodes(options?: {|+prefix: NodeAddressT|}): Iterator<ScoredNode> { }

  hasEdge(address: EdgeAddressT): boolean { }

  export type WeightedEdge = {|+edge: Edge, +weight: EdgeWeight|};
  edge(address: EdgeAddressT): ?WeightedEdge { }

  *edges(options?: EdgesOptions): Iterator<WeightedEdge> { }

  export type ScoredNeighbor = {|
    // Node adjacent to the target
    +node: NodeAddressT,
    // Edge connecting node to the target
    +edge: Edge,
    // Weight of `edge`
    +weight: EdgeWeight,
    // How much score (in absolute terms) was contributed
    // to target from node via `edge`
    +scoreContribution: number,
  |};

  *neighbors(
    node: NodeAddressT,
    options: NeighborsOptions
  ): Iterator<ScoredNeighbor> {
    // Note: if the graph hasn't been iterated to convergence, then the scores
    // may be inconsistent. }

  /**
   * Reweight the graph, using the given edge evaluator.
   * Note that after re-weighting the graph, you probably also want to
   * rerun PageRank.
   */
  reweight(evaluator: EdgeEvaluator): this { }

  export type ConvergenceOptions = {|
    +maxIterations: number,
    +convergenceThreshold: number,
  |};

  export type ConvergenceReport = {|
    +iterations: number,
    +finalDelta: number,
    +timeElapsedMs: number,
  |};

  /**
   * Run PageRank until the graph is converged to within
   * `options.convergenceThreshold`, or until
   * `options.maxSteps` is exceeded.
   */
  aysnc runPagerank(options: ConvergenceOptions): Promise<ConvergenceReport> { }

  syntheticLoopWeight(): number { }

  equals(that: PagerankGraph): boolean { }

  toJSON(): PagerankGraphJSON { }

  static fromJSON(json: PagerankGraphJSON): PagerankGraph { }
}
```

Some possible objections and responses:

1. It's weird that the underlying graph needs to be immutable. What if a user
   wants to add nodes/edges to the graph and then re-run PageRank?

In principle, there's nothing stopping us from implementing that. We could add
support for the PageRank graph to invalidate its outWeight cache and fill in
support for new nodes/edges (possibly using a default edge weight). We could
also add `addNode` and `addWeightedEdge` APIs to the `PagerankGraph` if we
wanted. But these are more complicated to implement, and we don't need them
yet, so freezing the underlying graph makes sense for now.

2. This class conflates two unrelated concepts: adding weights to the graph,
   and running a particular algorithm on the weighted graph to generate scores.
   We could decouple them so that there's a WeightedGraph class that builds on
   top of graph, and then the PageRank graph sits on top of WeightedGraph.

I considered this explicitly, see #1016 for an implementation of WeightedGraph.
However, splitting these pieces apart, while sensible conceptually, added more
implementation complexity for flexibility that we don't need or have
any plan for at the moment. Since we don't have any algorithm other than
(modified) PageRank that we want to run on these graphs, I don't see the
benefit in factoring the WeightedGraph out on its own just yet. If we decide we
need to factor it apart later, we may have other considerations (e.g. the
details of heuristic implementation) that will allow us to do a better job then.

@wchargin, your review is requested

**Comment by wchargin** [comment]
Thanks! I will read this and let you know what I think.
