### ISSUE TITLE
Add a project title on Project Explorer pages

### ISSUE THREAD

**Issue by BrianLitwin** [sourcecred/sourcecred#1027]
A title on individual project explorer pages that signifies which project you're looking at, eg `repoId.owner}/repoId.name` ? Above the Analyze Cred Button ?

**Comment by decentralion** [comment]
Good suggestion. Should be straightforward to implement too! Marking this contributions welcome.

**Comment by BrianLitwin** [comment]
Nice! I'm gonna give this one a try.
