### ISSUE TITLE
Show sourcecred data on a project's readme file

### ISSUE THREAD

**Issue by asood123** [sourcecred/sourcecred#1047]
It would be cool to generate an SVG that could be easily embedded in a readme file. It can show the top contributors and their percentages. Maybe it shows top 5 or anyone above 5%?

This would be a great way to spread the word about sourcecred.

**Comment by decentralion** [comment]
I like this idea! We'll need to solve #967 first.

**Comment by wpank** [comment]
For reference I think [This Repo](https://github.com/dawnlabs/carbon) is a good inspiration for this sort of feature.

**Comment by wpank** [comment]
I found something that does actually exactly this, with a similar motivation behind sourcecred: showing appreciation for contributors. 

[hall-of-fame](https://github.com/sourcerer-io/hall-of-fame) creates a widget for readme's that shows new, trending and top contributors. 

Taken from their README:

```
Every hour, Hall-of-fame looks into recent commits of your
 repo using GitHub API. It then selects three
 categories of contributors: new (those who made their first 
commit to your repo in the last 7 days), 
trending (those with most commits in the last 7 days), and top 
(those with most commits of all time). 
It then selects up to three new contributors, up to 4 trending 
contributors, and if total is less than 7, 
it fill up the remaining spots with top contributors.

Each contributor in the Hall-of-fame is represented with their 
avatar, and a badge new/trending/top 
with the corresponding number of commits. Each avatar links
 to a contributor's profile. Which means
 that anyone has a chance to be prominently featured on your 
README for some time!

Hall-of-fame works with Sourcerer (https://sourcerer.io), but it's
 not required for your contributors. 
If a contributor has a Sourcerer profile, their Sourcerer avatar 
with a halo is used, and the avatar 
links to their Sourcerer profile. If they don't, an avatar based on 
their GitHub is used, and it is linked 
to their GitHub profile.
```

Example:

### [iterative/dvc](https://github.com/iterative/dvc)

[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/0)](https://sourcerer.io/fame/efiop/iterative/dvc/links/0)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/1)](https://sourcerer.io/fame/efiop/iterative/dvc/links/1)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/2)](https://sourcerer.io/fame/efiop/iterative/dvc/links/2)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/3)](https://sourcerer.io/fame/efiop/iterative/dvc/links/3)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/4)](https://sourcerer.io/fame/efiop/iterative/dvc/links/4)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/5)](https://sourcerer.io/fame/efiop/iterative/dvc/links/5)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/6)](https://sourcerer.io/fame/efiop/iterative/dvc/links/6)
[![](https://sourcerer.io/fame/efiop/iterative/dvc/images/7)](https://sourcerer.io/fame/efiop/iterative/dvc/links/7)

**Comment by Beanow** [comment]
Had a similar thought of using it as an (all time) thanks / attribution of contributors. Looking a bit like what open collective offers https://opencollective.com/Docusaurus/contributors.svg?width=890&button=false

![sample](https://opencollective.com/Docusaurus/contributors.svg?width=890&button=false)


Generation code here https://github.com/opencollective/opencollective-images/blob/master/src/server/lib/svg-banner.js

**Comment by Beanow** [comment]
I've created a little experiment over at https://github.com/sourcecred/widgets/tree/pr/svg-wall-experiment that lets you create an SVG based on the #1223 scores output.

It's very experimental but if you're interested you can test it to generate a all-time top X contributors avatar wall.

**Comment by Beanow** [comment]
This widget has been implemented.
See https://github.com/sourcecred/widgets

Feel free to open new issues there for questions/suggestions :]
