### ISSUE TITLE
Add new reaction types

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#1054]
Context: <https://github.blog/changelog/2019-01-18-more-reaction-emojis/>

This is easy to implement, and will expose a new contributor to parts of
our type system, our GraphQL system, and our plugin system.

**Comment by decentralion** [comment]
If someone wants to take this on, I recommend using `git grep THUMBS_UP` to find where in the codebase other reactions are specified. For example (in the example we only look at `.js` files, ignoring snapshots and the like):

```
❯ git grep THUMBS_UP | grep \.js:
src/graphql/mirror.test.js:        "THUMBS_UP",
src/plugins/github/createGraph.js:          content === Reactions.THUMBS_UP ||
src/plugins/github/edges.js:  reactsThumbsUp: githubEdgeAddress(REACTS_TYPE, Reactions.THUMBS_UP),
src/plugins/github/edges.test.js:        Reactions.THUMBS_UP,
src/plugins/github/graphView.js:        reactionType !== Reactions.THUMBS_UP &&
src/plugins/github/graphqlTypes.js:  | "THUMBS_UP";
src/plugins/github/graphqlTypes.js:  +THUMBS_UP: "THUMBS_UP",
src/plugins/github/graphqlTypes.js:  THUMBS_UP: "THUMBS_UP",
src/plugins/github/schema.js:      "THUMBS_UP",
```

**Comment by wchargin** [comment]
Yep, agreed, modulo some shell nits:

<details>
<summary>Shell nits</summary>

Compare:

  - `git grep THUMBS_UP | grep \.js` is the same as `… | grep .js`,
    where `.` is a regexp metacharacter; you probably meant

  - `git grep THUMBS_UP | grep '\.js'`, which will filter for literally
    `.js`, although you may prefer to use

  - `git grep THUMBS_UP | grep -F '.js'` (`-F` = `--fixed-strings`:
    treat the pattern literally)—but better than all of these is

  - `git grep THUMBS_UP '*.js'` (note quotes), which only includes
    results from files whose names match `*.js`, and thus won’t have
    false-positives on files whose _contents_ happen to contain `.js` or
    that contain `.js` elsewhere in the filename.

(In particular, all these forms but the last include results from files
like `example-github.json`.)

---
</details>

For changes like this, a “compare `git grep` with files changed in this
commit” is a great thing to include in your test plan as well.

**Comment by wchargin** [comment]
Agreed that :eyes: should be invisible, given that I have no idea what
it’s supposed to mean.

:rocket: definitely seems positive, but I’m not sure what people are
expected to use it for, so I don’t know how positive it should be. I’m
fine with it being a positive value of your choice, or not flowing cred
at all.

The reason that I tagged this as [bug] is that the change to the server
schema means that our Flow types are no longer necessarily sound: when
we deserialize a `ReactionContent` from the mirror, we coerce it through
`any` to what used to be the correct type but is now the wrong type. So,
IMO, making the code correctly reflect the remote is more important than
getting the values (which we can always tweak) exactly right.

(One might ask _why_ GitHub chose to add these new emoji, which would
inform these questions. But the entire body of their blog post is one
sentence and a link to the docs, so we can only speculate.)

[bug]: https://github.com/sourcecred/sourcecred/labels/bug

**Comment by wchargin** [comment]
@BrianLitwin has kindly escalated this issue’s priority by reacting to
it with the :rocket: emoji, so that SourceCred now actually loads
poisoned data while eating its own dog food. :-)

(The UI doesn’t actually do anything bad, though, because of
<https://github.com/sourcecred/sourcecred/blob/e0762303d466c6a8f86324eb84e3120c29beddb0/src/plugins/github/createGraph.js#L56-L60>.)

**Comment by BrianLitwin** [comment]
Do i need to bump a version number somewhere after this change? 

I've got the following error after trying to reload a repo (sourcecred) after [these changes ] (updating the reaction types):
`Error: Database already populated with incompatible schema, options, or version` 

[these changes ]: https://github.com/sourcecred/sourcecred/compare/master...BrianLitwin:add-new-reaction-types

 Presuming that I need to bump the version, where and how would I do so?

**Comment by decentralion** [comment]
@BrianLitwin you probably want to blow away the local GitHub cache. 
You want one of the following two commands, depending on whether you have set the `$SOURCECRED_DIRECTORY` environment variable.

if it's set: `rm -rf $SOURCECRED_DIRECTORY/cache`
if not: `rm -rf /tmp/sourcecred/cache`

In general, any time sourcecred is being weird, or showing you versioning issues, you probably want to remove the whole sourcecred directory (not just the cache) via `rm -rf $SOURCECRED_DIRECTORY` or `rm -rf /tmp/sourcecred/cache`.

We should make this easier! Wrote an issue to track this at #1067

**Comment by decentralion** [comment]
Yep, any time you are changing something in `bin/` (e.g. `bin/sourcecred.js`) running `yarn backend` is necessary.

**Comment by wchargin** [comment]
@decentralion, just a note: it pays to be especially careful with your
shell quoting when listing commands that include `rm -rf`. recall that
if `FOO` is set to `foo bar` then your `rm -rf $FOO/cache` will delete two
subtrees called `foo` and `bar/cache`, not one subtree called `foo bar`—and if
it’s set to `* z` then the glob will be expanded to remove everything
under the current directory! (and also `z/cache`). This provides an
escalation mechanism for attacks: a vulnerability that merely lets you
set environment variables can be upgraded to delete arbitrary files.

The steps for determining exactly when you _must_ quote your variables
may be complex, but it _suffices_ to remember the following simple rule:
quote your variables always, literally every time. :-)

**Comment by decentralion** [comment]
Thanks @wchargin! That's a helpful example which will cement the "quote every time" in my mind.

To be clear: In this case I want to type `rm -rf "$FOO"/cache`, not `rm -rf "$FOO/cache"`, yes?

**Comment by wchargin** [comment]
> To be clear: In this case I want to type `rm -rf "$FOO"/cache`, not
> `rm -rf "$FOO/cache"`, yes?

If you mean a string literally, it is always at least as safe to
double-quote it as it is to leave it unquoted.

When you write `"$FOO"/cache`, the slash is not quoted. You mean it
literally, so you’re _betting_ that a slash in a bareword in that
particular context is interpreted literally.

Are you sure about that?

Can you confidently tell me what each of the following prints when run
in sequence?

```
FOO=1
echo $FOO
echo /FOO
echo #FOO
echo _FOO
echo %FOO
echo !FOO
echo &FOO
```

Can you further tell me which of the special characters that _appear_ to
act literally above actually do _not_ always act literally?

If you mean a string literally, it is always at least as safe to
double-quote it as it is to leave it unquoted.

**Comment by wchargin** [comment]
(I usually write `rm -rf "${SOURCECRED_DIRECTORY}/cache"`, because the
braces make it more visually obvious that the `_` is part of the
variable name while the `/` is not; in `$SOURCECRED_DIRECTORY/cache` it
is less clear.)
