### ISSUE TITLE
Add CLI command for clearing cache or data directory

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1067]
It's relatively common at this point that we make backwards-incompatible changes to our serialized data formats, or to the GitHub mirror cache. When we do so, users need to reset their SourceCred data directory, which they may do by invoking either:

`> rm -r $SOURCECRED_DIRECTORY` (if they set the flag)
`> rm -r /tmp/sourcecred` (if they have not)

Since there are two different ways to do this, and only one is correct depending on how the user has configured their environment, it makes it complicated to help people who are in a corrupted state. In the medium term, we should fix the root issue (i.e. automatically upgrade the data formats so the user doesn't need to take any special action when the data format changes). However, for now, we could make this a little easier by adding a command like:

`sourcecred clear --all` -- removes the whole $SOURCECRED_DIRECTORY
`sourcecred clear --cache` -- removes just the cache directory
`sourcecred clear` -- prompts the user to be more specific

Then those errors that are thrown can report exactly how to fix them, i.e. when we have the wrong version of repoIdRegistry, we can ensure that "try running `sourcecred clear --all`" is printed to console.

**Comment by wpank** [comment]
> Since there are two different ways to do this, and only one is correct depending on how the user has configured their environment, it makes it complicated to help people who are in a corrupted state.

Can you elaborate on this a little bit? In what circumstances would a user have  `$SOURCECRED_DIRECTORY` and `/tmp/sourcecred` as their default environmnet?

**Comment by decentralion** [comment]
Basically: I have `$SOURCECRED_DIRECTORY` set to `~/tmp` (my personal tmp folder) so that the data will not automatically be discarded by the OS. For anyone who has done something like this, running `rm -rf /tmp/sourcecred` will not have the effect that they intend. On the other hand, if they have not set `$SOURCECRED_DIRECTORY`, then running `rm -rf $SOURCECRED_DIRECTORY` will not work as intended either. So when users encounter this issue, there is no "default good command" we can give them to get them back into a clean state.

We already have [re-usable logic for resolving this distinction](https://github.com/sourcecred/sourcecred/blob/master/src/cli/common.js#L19) so we should use that to create a generic command that will work no matter how the user has configured their environment.

**Comment by decentralion** [comment]
Labeling as good first issue. Someone looking to implement this can add a new command by adding a corresponding new file to the [cli directory](https://github.com/sourcecred/sourcecred/tree/master/src/cli), i.e. `src/cli/clear.js` and `src/cli/clear.test.js`. They should then update [sourcecred.js](https://github.com/sourcecred/sourcecred/blob/master/src/cli/sourcecred.js#L28), the entry point, so that it invokes the new command, and [help.js](https://github.com/sourcecred/sourcecred/blob/master/src/cli/help.js) so that it prints a help string for the new command.
