### ISSUE TITLE
Need a list of available tasks

### ISSUE THREAD

**Issue by 000drax** [sourcecred/sourcecred#11]
I'm thinking we need a shifting list of tasks available to work on (to encourage contributions). 

Example: I've dropped off for a bit, and I have no idea what needs to be done anymore :)

For each available task, I think it should have
- priority (P0 - P4)
- description
- reviewer
- who's working on it (if anyone)
- expected delivery date (if anyone is working on it)

**Comment by dandelionmane** [comment]
I think the project isn't yet at the level of maturity where it's easy / time efficient to carve out tasks like this; once we have more core code that we're relatively sure of, it will make sense.

For now, I'm glad you're eager to contribute, if you want to coordinate offline to hang out and hack on it for a few hours I'd be glad to! Also, you can join the SourceCred slack (see README)

**Comment by dandelionmane** [comment]
@000drax I've fleshed out some more available tasks
