### ISSUE TITLE
Issues with reference detection logic

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1118]
GitHub reference detection is pretty important to SourceCred, as we believe
that, for example, when a pull request references an issue, it's a strong
source of signal that the issue was relevant to the pull request.

Unfortunately, our current reference detection logic has a number of flaws.

1. When multiple repositories are in scope, numeric references (e.g. `#23`)
will arbitrarily reference one of those repos. If a large number of
repositories have been loaded, this can massively distort cred in favor of
whichever repo "got lucky" and recieves all of the numeric references. (See:
#904).

2. References are stored an manipulated as reference strings (e.g.
  `"https://github.com/sourcecred/sourcecred/issues/904"` or
  `sourcecred/sourcecred#904`), rather than a structured representation. This
  just makes them a little harder to work with.

3. Every time a repository is added to a `RelationalView`, _every_ reference is
  regenerated from scratch, including for all other repositories. This makes
  generating the relational view quadratic in the number of repositories, and
  is a substantial perf overhead in practice.

4. The logic for "paired-with references" is implemented inelegantly. We have
  support for "paired-with" references (see: #451), which allows a GitHub post
  to have shared authorship. This is treated as a separate "kind" of reference,
  and the GitHub reference logic internally creates duplicate references for
  every paired-with reference (one paired-with, one basic) and then manually
  filters out the duplicated basic reference. This works tolerably, but doesn't
  allow us (or plugin authors) to flexibly add more "kinds" of reference edges
  in the future.

Of these issues, 1. is highest priority; it significantly biases results when
loading many repositories. 3. is quite important too, as it has a bad perf
consequence when loading many repositories.

Fixing 1. will be facilitated by fixing 2., so we may want to do that first.
It's interesting to note that for commits, its impossible in general to tell
where the numeric reference should point, since the same commit may exist in
multiple repositories. I think we might choose to solve this by simply
disabling numeric reference detection in commits for the time being.

Fixing 3. should not be particularly hard, though it's somewhat subtle. We need
the RelationalView to track every outbound reference from every existing repo,
even if the referents have not been encountered yet. That way, if we encounter
the referent in a future repo, we can correctly add the references edge.

A lot of these problems stem from the fact that, when we wrote the
RelationalView module, we were not imagining a use case where we have multiple
repos in scope simultaneously. Multi repo support has been added in an ad-hoc
fashion, e.g. see #711 and #1117. We would do well to keep this in mind as we
write fixes, and consider whether we should be refactoring the whole system to
have principled first-class support for project-level attribution (#701).

**Comment by wchargin** [comment]
> will arbitrarily reference one of those repos

Yes—this was always a clear bug, and we just decided that it was low
priority; this may no longer be the case.

> rather than a structured representation. This
> just makes them a little harder to work with.

For more details, see this pull request review, wherein I suggest a
particular structured form (which we appeared to punt on):
<https://github.com/sourcecred/sourcecred/pull/130#pullrequestreview-113849998>

> This makes generating the relational view quadratic in the number of
> repositories, and is a substantial perf overhead in practice.

Huh. Really? Reference detection takes a while?

Quick hackaround: add the smallest repos first. ;-)

> A lot of these problems stem from the fact that, when we wrote the
> RelationalView module, we were not imagining a use case where we have
> multiple repos in scope simultaneously.

For what it’s worth, not sure how true this is—in my original review of
`addData` I specifically requested that we explicitly document this bug:
<https://github.com/sourcecred/sourcecred/pull/442#discussion_r199032153>
The warning that we ended up adding pointed out one specific case that
is not reference-related, but we knew about the reference detection
problem then, too.

**Comment by decentralion** [comment]
> > This makes generating the relational view quadratic in the number of
> > repositories, and is a substantial perf overhead in practice.
> 
> Huh. Really? Reference detection takes a while?
> 
> Quick hackaround: add the smallest repos first. ;-)

Actually, I'm not sure my claim is correct. When loading large groups of repos, the final step (creating the RelationalView) is quite slow and pegs my CPU. However, it might be due to the volume of data, and not reference detection in particular. I haven't tested it.
