### ISSUE TITLE
eslint: enable the `curly` rule

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1121]
We should consider turning on the [curly](https://eslint.org/docs/rules/curly) eslint rule, which will ensure that we always use brackets around if statements (even single-line ifs). It's a good general decision because otherwise, people might try to add another line to an if statement and it doesn't have the semantics they expect.

Surfaced from discussion here: https://github.com/sourcecred/sourcecred/pull/1114#discussion_r268875563

**Comment by wchargin** [comment]
Isn’t this only a problem if you don’t also have code formatting? Once
your code is reformatted to

```js
if (foo)
  bar();
baz();
```

then it’s pretty clear what the semantics are. Even gcc has an option
for this now: `-Wmisleading-indentation`.

In my humble opinion, code like

```js
        if (plugin != null) return die(std, "'--plugin' given multiple times");
        if (++i >= args.length)
          return die(std, "'--plugin' given without value");
        const arg = args[i];
        if (arg !== "git" && arg !== "github")
          return die(std, "unknown plugin: " + JSON.stringify(arg));
```

and

```js
    if (db == null) throw new Error("db: " + String(db));
    if (schema == null) throw new Error("schema: " + String(schema));
```

and

```js
        if (a.type !== "OBJECT") throw new Error("githubTypes: " + a.type);
        if (b.type !== "OBJECT") throw new Error("schema: " + b.type);
```

is perfectly fine, and there’s no reason to clutter it up with extra
braces and newlines.

(Also, just to note: Prettier reformats `if (foo) \n bar();` to remove
the newline when space permits, which completely removes the possibility
of error.)

(I also don’t strongly object if you have strong feelings about this.)

**Comment by decentralion** [comment]
Hmm, I think you make a good point. In the absence of someone else with a strong preference for turning on curly, I'd be happy to keep the status quo.
