### ISSUE TITLE
Unnecessary Array.fill(0)

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1126]
Throughout the codebase, we often have the pattern `new Float64Array(n).fill(0)`. According to the Float64Array docs, the contents are always initialized to 0, so this is a minor but unnecessary performance hit. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array

**Comment by wchargin** [comment]
Good point. `Array`s need to be `fill`ed lest they contain “empty slots”
(distinct from `undefined` values), but typed arrays don’t.

**Comment by raravi** [comment]
Hi,

I was checking this issue to work on, but doing a search with `.fill(0)` doesn't return anything!

Searching with `.fill` yields the below result.

![Screenshot 2019-04-13 at 7 42 37 PM](https://user-images.githubusercontent.com/26003413/56083388-8f72a680-5e24-11e9-8a8e-aebdb57d9c38.png)

I feel like I'm missing something elementary :(

Thank You,
Amith

**Comment by decentralion** [comment]
@raravi it's actually me that was missing something elementary :) We were doing a bunch of hacking on the markov chain module (for https://github.com/sourcecred/odyssey-hackathon/pull/3) and a collaborator added some Array.fill(0) calls. I mis-interpreted them as being from the original codebase and jotted down this issue, but forgot to check that they hadn't been added during our hacking.

Thanks for looking into it! And welcome to the SourceCred community @raravi! Going to close this issue since it was made in error.
