### ISSUE TITLE
Stop storing the Git graph on disk

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1158]
Right now, when the Git plugin is loaded, it saves two files to disk. One contains a serialized Git repository type:
https://github.com/sourcecred/sourcecred/blob/61627531bbfcd4a3d07796150f145cc318608c65/src/plugins/git/types.js#L5-L10

The other is a serialized graph.

We can see the two files being saved here:

https://github.com/sourcecred/sourcecred/blob/61627531bbfcd4a3d07796150f145cc318608c65/src/plugins/git/loadGitData.js#L18-L31

This is a little redundant, because we can already create a Git graph from the repository:
https://github.com/sourcecred/sourcecred/blob/61627531bbfcd4a3d07796150f145cc318608c65/src/plugins/git/createGraph.js#L9-L13

Therefore, instead of persisting both the graph and repository to disk, it would suffice to persist just the Repository, and then create the Graph from it when required. 

The first step will be to modify loadGitData so that it only saves the repository.json. Of course, that will also break the application, because currently the AnalysisAdapter (plugin adapter for cred calculations) and ExplorerAdapter (plugin adapter for the frontend UI) depend on loading graph.json.

In the AnalysisAdapter load method, we should change the following section of code:
https://github.com/sourcecred/sourcecred/blob/e01247a64264b1e55ce8112f6990e31aa16ded1e/src/plugins/git/analysisAdapter.js#L36-L41

Instead of loading graph.json there, we can just load the repository, and then invoke the createGraph method on that repository.

Similarly, in the explorer adapter, we can delete the code for loading the graph, and instead call createGraph on the repository after it is loaded.

https://github.com/sourcecred/sourcecred/blob/e01247a64264b1e55ce8112f6990e31aa16ded1e/src/plugins/git/explorerAdapter.js#L25-L48

After the change has been made, we can test it in the following two ways:

1. Manually
```shell
# rebuild SourceCred
$ yarn backend
# Ensure that no out-dated files are around
$ node bin/sourcecred.js clear --all
# check that load still works (this includes using the analysis adapter for pagerank)
$ node bin/soureccred.js load sourcecred/example-github 
$ yarn start 
# navigate to http://localhost:8080/prototype/sourcecred/example-github/
# and make sure that it still works
```
2. Automatically
```shell
$ export SOURCECRED_GITHUB_TOKEN=acd....0123
# Update the loaded snapshots to reflect the change to the stored data
$ scripts/update_snapshots.sh 
# Run the full test suite (including loading data)
$ yarn test --full
```

**Comment by pkafei** [comment]
Quick check in-

 I looked at the issue, and it seemed clear. When Git plugin is loaded it saves 2 files to disk- the serialized graph and the serialized Git repository type. This is a bug because a serialized graph is created by `createGraph.js`. 


The solution is to only load the repository but to also account the breaking changes in `analysisAdapter.js` and `explorerAdapter.js`.

One can test if the change worked by building and running SourceCred locally. 

I had some trouble with `node-gyp` dependency when building the sourcecred locally because my machine is a mac, but I fixed this bug by running `brew install coreutils`.

**Comment by decentralion** [comment]
Yup, I agree with your assessment. Slight nit, I wouldn't call it a "bug" per se--it's just an opportunity to make things a little more efficient.

If you think we can improve the README to make it easier to catch that `brew install coreutils` is needed by mac developers, feel free to send a PR. :) Actually, I should probably re-vamp the README entirely, but I want to try to get a prototype of time varying cred built first.

**Comment by decentralion** [comment]
I'm closing this issue. As of #1136, the Graph is now the canonical source of all the info that a plugin downloads. So rather than refactoring to not store the graph, we could instead refactor to _only_ store the graph.
