### ISSUE TITLE
Timestamps missing for non-master commits

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1163]
The git plugin owns Git commit nodes, which means we depend on the git adapter to provide commit timestamps (cf #1153). However, at present the Git plugin only retrieves commits that are in the `master` branch's history. But the GitHub plugin adds commit nodes to the graph which may have come from other branches.

At present, the Git plugin throws an error when requesting a timestamp for a commit it doesn't know about. Because #1162 tries to load timestamps for every commit node, this results in crashing `sourcecred load` on many real repositories (e.g. sourcecred/sourcecred). Oops! Should have included "load real repos" in the test plan. :)

For now, we can hackily fix this by just having the adapter return null for commits it doesn't know about. In the long run, there are two more principled solutions (we could implement both):

- Distinguish adding a reference to a node to the graph (what the GitHub plugin wants to do for Git nodes) vs actually adding it to the graph. This could dovetail nicely with putting timestamp information directly into the graph (when it is added by the node owner, the timestamp would get included). 
- Have the Git plugin scan for commits in more places than just the master branch. I don't think this would fix the issue in all cases, as it's possible that the commit could get garbage collected if it's not reachable from any present branches. (but GitHub might still hold on to a reference to it independently.)

**Comment by wchargin** [comment]
> as it's possible that the commit could get garbage collected if it's
> not reachable from any present branches. (but GitHub might still hold
> on to a reference to it independently.)

Indeed: e.g., tags, or the “base ref” of a pull request, which may live
only in a different repository. Note that `git ls-remote origin`
displays _more_ refs that GitHub knows about, but I can’t say with
certainty that that includes _all_ such refs. More importantly…

> For now, we can hackily fix this by just having the adapter return
> null for commits it doesn't know about.

This seems like the _only_ principled solution to me. If any plugin can
add Git commit nodes (or “references” to them—I don’t think that the
distinction matters here), then the Git plugin cannot assume that it
knows about all commits.

As long as

```javascript
import {Graph} from "./core/graph";
import {toRaw} from "./plugins/git/nodes";

// This commit really exists on my local machine; good luck finding its
// creation date.
const oid = "2fc115ef89ad7abc9fb62d6800e5d31da5ba756ec7120f840cac3b97de5d091b";

new Graph().addNode(toRaw({type: "COMMIT", hash: oid}));
```

is valid, you’ll never be able to find all the commits—the real hack is
trying to do so anyway rather than making the system robust to arbitrary
input!

**Comment by decentralion** [comment]
:wave: nice to see you @wchargin! I wondered if you would make an appearance on this issue ;) 

Setting the timestamp as null is a little weird in the context of how null timestamps are interpreted: it means the node is "timeless" and when I do the temporally-iterated PageRank, that node will be present in the initial set. Which makes sense for users and the like, not so much for commits like this.

With the semantics I have in mind for "having a node" vs "having an edge to a node"--it will be OK to have edges to nodes that aren't in the graph, but the edge will be ignored during PageRank (because the markov chain is defined over nodes in the graph). IMO, this is better semantics: if we have a connection to a node but don't know essential details about that node like when it was created, then it's like the node doesn't exist, and no cred flows across the edge.

**Comment by Beanow** [comment]
Is this still applicable for the GitHub plugin? @decentralion

**Comment by decentralion** [comment]
No, this applies only to the Git plugin. Since the Git plugin is not in production and we don't have any plans to use it, I'm fine closing this issue.
