### ISSUE TITLE
build_static_site.sh now requires SOURCECRED_DIRECTORY env var

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1226]
The change in https://github.com/sourcecred/sourcecred/commit/ff026817d014124914af51028c72254052c196dd

Uses the `SOURCECRED_DIRECTORY` env var before it's exported with a default value.
Meaning it's now required to be set or will crash the script. It should probably be wrapped in an if statement to skip linking the cache if the env is not provided.

**Comment by decentralion** [comment]
Thanks for the report. I have a fix for this over at #1228.
I tried to add an automated test, but it didn't work out, for reasons you can read about [here](https://github.com/sourcecred/sourcecred/commit/a575638fa47265cb624663894c4e28ba2bddc2e4). @wchargin, would love to hear if you have any suggestions.
