### ISSUE TITLE
Have GreenKeeper start automatically updating the lockfile

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1269]
Currently Greenekeeper isn't updating our lockfile.

There are two fixes to take. Either:
- setup [greenkeeper-lockfile](https://github.com/greenkeeperio/greenkeeper-lockfile)
or
- make SourceCred a public package ([source](https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0))

I haven't bothered with the first option as yet, because we do want to publish `sourcecred` on npm (#1232). However, that a pretty involved project, which I'm not planning to prioritize until after the discourse plugin (#865), and making SourceCred robust on large repositories (#1256). So unless someone else wants to take a stab at #1232 (@Beanow ?) we should probably bite the bullet and setup greenkeeper-lockfile.

**Comment by Beanow** [comment]
I agree NPM will probably take some time so the first options sounds like the way to go. Plus a bit of experience with that route won't hurt should option 2 ever cause trouble later.

**Comment by decentralion** [comment]
Having given the bug a few weeks to hopefully disappear, I reset greenkeeper, generating  https://github.com/sourcecred/sourcecred/pull/1394. It seems to be updating the lockfile properly now.
