### ISSUE TITLE
Custom weights not kept in legacy

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1316]
Using `--weights` as part of the load command sets these weights as the default in the explorer and applies them to timeline cred. However legacy cred uses the default weights instead.

I'm assuming it's on the way out, but still wanted to make note of this.

**Comment by decentralion** [comment]
Noted. i consider this a wontfix; legacy mode is on its way out. What we should prioritize instead is putting score decomposition into timeline mode, so that we can deprecate legacy.
