### ISSUE TITLE
Blank weeks at the start of timeline cred

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1317]
I've noticed this loading `@sfosc` with the `v0.4.0` release. There are several blank weeks included before the first contributions.

Contributions start in "The week of November 25" yet the first interval is:
```js
{
  "endTimeMs": 1540080000000,
  "startTimeMs": 1539475200000
}

new Date(1539475200000).toISOString()
// "2018-10-14T00:00:00.000Z"
new Date(1540080000000).toISOString()
// "2018-10-21T00:00:00.000Z"
```

All users, including adamhjk who created the org and repository, have nulls for their scores in these intervals.

```js
{
  "id": "adamhjk",
  "intervalCred": [
    null,
    null,
    null,
    null,
    null,
    null,
    8.03125,
    14.953116717673753,
    28.867859281699292,
    61.841989977282196,
    // ...
    0.6651734167260511
  ],
  "totalCred": 245.39729499182977
},
```

Something similar seems to be going on for https://sourcecred.io/cred/timeline/@libp2p/

**Comment by BrianLitwin** [comment]
Would this be a good issue to pick up @decentralion ?

**Comment by decentralion** [comment]
Yeah @BrianLitwin. I'm definitely curious what's going on here.

The intervals get created in this code:
https://github.com/sourcecred/sourcecred/blob/fa6697719aac6cedb8afc5274030f10ed67b43eb/src/analysis/timeline/interval.js#L41-L67

So plausibly there is some weird node that has too early a timestamp, which is resulting in there being the extra intervals up front.

The fact that `null` is included in the scores is also a bug, even if there were no nodes available, I think it should be 0 not `null`. Ideally we'll find both why there are extra intervals, and why the nulls were showing up in the scores. The relevant code is all in `analysis/timeline`: https://github.com/sourcecred/sourcecred/tree/master/src/analysis/timeline

**Comment by BrianLitwin** [comment]
Just to journal on this a little, these org's have github.io projects that seem to have super early timestamps. 

The reason the values are null and not 0 looks like a divide by 0 thing in `distributionToCred` . The distribution passed in is an Array of all 0s and one node w/ a distribution of 1, e.g. `[0, 0, 0, 1]`. I think the  1 isn't summed in the `intervalTotalScore` variable b/c the node (a repo node associated w/ Github.io) isn't recognized in the `scoringNodePrefixes` map b/c it's not a `UserType` node. 

I don't think I have enough context on the project rn to come up with a solution, whether to add some control flow to avoid the divide by 0 or pass in more types to `distributionToCred`?

**Comment by BrianLitwin** [comment]
Just to confirm the source of the early timestamp, Github's GQL Explorer returns this for the `sfosc.github.io` project => 

```gql 
query {
  repository(owner:"sfosc", name:"sfosc.github.io") {
    createdAt
  }
}

=>

{
  "data": {
    "repository": {
      "createdAt": "2018-10-18T18:04:49Z"
    }
  }
}
```

Is that timestamp implausibly early @Beanow ? 

Is it a bug that there can be a Repo node with no connections to any User nodes? Or should we be able to accommodate Repo's that have a first interval with one isolated, non-User node ?

**Comment by decentralion** [comment]
Nice work diving into this @BrianLitwin.

First, given that we've seen this on a few GitHub examples, we definitely need the code to behave properly, both at the data and UI levels. This is part of the shape of real data in the world of SourceCred. :)

On the data layer, as you identified the bug lives in this region of the code:

https://github.com/sourcecred/sourcecred/blob/be7b465f988abbda1f2fc12a8f21aeb3d94f4565/src/analysis/timeline/distributionToCred.js#L52-L62

What's interesting is that we do check and error if no nodes match the scoring prefix. It's like we anticipated one divide by zero but not the other. We should handle these cases consistently, and we should handle them in a way that works for real-world data.

I believe the new contract for the function should include:
- if no nodes match the scoringNodeDistribution, then an empty array is returned
- if in any period all scoring nodes have a raw score of zero, then the total score for the matching nodes in the interval will be zero

**Comment by decentralion** [comment]
Nice work diving into this @BrianLitwin.

First, given that we've seen this on a few GitHub examples, we definitely need the code to behave properly, both at the data and UI levels. This is part of the shape of real data in the world of SourceCred. :)

On the data layer, as you identified the bug lives in this region of the code:

https://github.com/sourcecred/sourcecred/blob/be7b465f988abbda1f2fc12a8f21aeb3d94f4565/src/analysis/timeline/distributionToCred.js#L52-L62

What's interesting is that we do check and error if no nodes match the scoring prefix. It's like we anticipated one divide by zero but not the other. We should handle these cases consistently, and we should handle them in a way that works for real-world data.

I believe the new contract for the function should include:
- if no nodes match the scoringNodeDistribution, then an empty array is returned
- if in any period all scoring nodes have a raw score of zero, then the total score for the matching nodes in the interval will be zero

would you please send in a pull request making this change? please update the docstring of the method as well.

on the design layer: once we fix the issue on the data layer, the solution is easy. we should have the timeline cred filter out intervals for which all users have score zero. the filtering should happen at the transition from core data code to the rendering layer.

between the two, i think fixing it at the data layer is higher priority. wrt. the frontend, i think we should align on a shared vision for how it's going to evolve before we put a lot more work into it. but do feel free to fix the bug.
