### ISSUE TITLE
Reproducibility of fixed-time findStationaryDistribution approach

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1319]
Given the dogfood experiment coming up, having the `yieldAfterMs` option for `findStationaryDistribution` harms reproducibility of any published data to justify payouts.
https://github.com/sourcecred/sourcecred/blob/402945809824e633ace5df26ac0b2c724cff1cb7/src/core/attribution/markovChain.js#L202-L230

Having a fixed time limit will make the number of iterations done CPU performance dependent.
I would suggest either removing it to rely on just `maxIterations` or using a deterministic alternative.

**Comment by wchargin** [comment]
The value of `yieldAfterMs` affects the concurrency properties of the
program, but I don’t see how it affects the final answer. The actual
termination criteria are only a convergence threshold and a maximum
number of iterations, and you can see from your linked code snippet that
we check for termination at every step of the underlying generator
(`gen.next()`), not just between yields. The purpose of the yielding is
just to unblock the main thread to allow for UI updates, etc.

Note that we do have tests for `findStationaryDistribution`, and I’ve
never seen them flake, even across fairly different machines (low-power
CI machines, personal laptops of different calibers, desktops).

Can you elaborate on how this might result in actual value differences?

**Comment by Beanow** [comment]
Ah, I think I've misinterpreted the code then. I had read this initially as, whichever of meeting the convergence threshold, max iterations or `yieldAfterMs` expiring comes first.

But it only postpones the loop with `setTimeout(tick, 0);` roughly every `yieldAfterMs`.

**Comment by wchargin** [comment]
Yep, that’s right!
