### ISSUE TITLE
Additional github bots

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1381]
- https://github.com/gitter-badger
- https://github.com/codecov-io

Found these loading `@fluture-js` spec.

**Comment by decentralion** [comment]
Please send a pull request against https://github.com/sourcecred/sourcecred/blob/master/src/plugins/github/bots.js

**Comment by wchargin** [comment]
…and if these were causing load failures, please also send a pull
request against `src/plugins/github/blacklistedObjectIds.js`.
