### ISSUE TITLE
Discourse plugin doesn't detect mentions

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1420]
The Discourse plugin expects full absolute URLs leading to user identities, as seen here:
https://github.com/sourcecred/sourcecred/blob/01bdb2e94a1d8130f0cf1301e953408b4c788ff5/src/plugins/discourse/references.js#L62

However, as noted in [this review comment](https://github.com/sourcecred/sourcecred/pull/1418#discussion_r337319287), Discourse actually generates relative links for user mentions.

We should fix this, and ensure the references test code uses some real references from the test instance.

**Comment by Beanow** [comment]
Note: the example html I got from going to the actual forum and inspecting in the browser. Not from the API's `cooked` field. Best to double check if it's the same in `cooked`.
