### ISSUE TITLE
Discourse mirror issues and possible enhancements

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1426]
Digging into the Discourse plugin I found a whole bunch of things surrounding the mirror:

Enhancements:
- The API key is not required. All data is available through anonymous access.
- The rate limit does not apply to anonymous access allows for much faster and parallel requests.
  Adding parallel requests - discourse: 3m 22s
  Current implementation - discourse: 8m 28s
- The `Mirror` class has conflated SQL queries, read-only methods, internal write methods and mirroring logic. I would like to split this into a read-interface, read-write interface, an implementation of those and mirroring logic separately.

Issues:
- Resume correctness is poor. The very first topic / post that are saved are the latest ones.
  From there it uses the max ID and assumes this is the head of what's last been synced.
  Should you cancel the update soon after saving the latest topics / posts, you will be missing 99%   of all data and never attempt to load it.
- Edits are not handled at all. #1419 
- Most of the time, we prefer local data over remote data. Even though remote data is authoritative.

Notes:
- There's a very heavy reliance on the assumption topic and post ids are incremental.
- The (remote) API leaves a lot to be desired in terms of calls suitable for syncing. Making it difficult to be both fast and correct. For example, no likes sorted by date and no topics sorted by _any_ update, just by updates that constitute a "bump".

I would be interested in refactoring most if not all of the mirroring logic to improve these aspects.

**Comment by Beanow** [comment]
I've gotten pretty far into a big overhaul: https://github.com/sourcecred/sourcecred/compare/master...wip/refactor-discourse-plugin

Before I restructure the commits and make another pass on handling TODO items, I'd like to discuss the changes on a high level and get your feedback on that.
cc @decentralion @wchargin 

- Now using anonymous API access.
- Removed API key and username all across the code.
- Changed project structure field to: `discourseServers: $ReadOnlyArray<string>`
  Supporting multiple servers per project, and removing the username.
- Updated load API and CLI to support multiple discourse servers.
  _(Currently multiple discourse servers in one project is incompatible with the `identities` plugin,
  as it uses ambiguous `discourse/@username` aliasing.)_
- Moved SQL operations into `MirrorRepository` class, which implements a read-only interface which the graph creation step accepts, having the syncing logic in `Mirror`.

On top of that, a major overhaul of how topics and posts are retrieved.
1. We walk through `/latest.json?order=activity&ascending=false&page=${page}`
  to find all the topics that were "bumped" since our last update.
  _Gotchas: pinned topics change the ordering, and category definitions aren't included._
2. On first load, or every 24h (by default, available as a setting), walk through categories
  `/categories.json?show_subcategory_list=true` and subcategories
  `/categories.json?show_subcategory_list=true&parent_category_id=${parent}`
  to find their topics which looks like `"topic_url": "/t/about-the-site-feedback-category/1"`
3. The combination of step 1 and 2, give us a list of topic IDs we need to load.
  Using `/t/${id}.json?page=${page}` (called `topicWithPosts`) go through all pages until we have all posts in the topic.
_Gotcha: topics loaded from here do not have their `bumped_at` field, which they do have at `/latest.json`._
4. Write all topics and posts we find through step 3 to the `MirrorRepository`.

- I've tested this gives 100% coverage of all visible topics and posts. I've compared to using the old method with and without admin API key.
- It doesn't require ID guessing.
- It's faster and uses less API calls. About ~100% faster on first load, and 1 API call in the best case caching scenario for topics and posts combined.
- It **supports editing posts** (#1419) _whenever it triggers a bump to the topic_.
  If an edit does not cause a bump, it will be included on the next bump.
- It will correctly resume loading data even if cancelled and eventually reach 100% coverage.
- It still doesn't detect deletions.
- It still requires iterating over all known users to update their likes.
- Moving posts / splitting topics I haven't tested.

**Comment by decentralion** [comment]
I'm supportive of this change. A few questions:

- Suppose we had a mega-topic with (say) 1000 posts. Someone adds a new post to the end. My understanding is that in the old system, we would just retrieve the new post (by ID) but in the new system, we will see the mega-topic was bumped and then re-request all of its posts in order. I suppose if this became an issue, we could retrieve the topics from latest-posts-first and keep going until we encounter cached posts? (Would miss edits.)

- Do we know under what circumstances an edit will cause a bump to the topic?

**Comment by Beanow** [comment]
Exactly right on the mega topic. We would fetch the entire thread every time we load after it is bumped.

Focusing on SourceCreds own forums, this makes a lot of sense, because the majority of topics fit in a single request (default posts per page is 30) with a handful that have two pages. I don't recall any beyond that.

Should it be an issue in the future, we can optimize for this rather easily. In the first `/latest.json` we should have the number of posts for each topic. We can detect early on when we're dealing with a mega topic and think of any strategies you like, such as get the bare minimum, or a subset (the last 3 pages for example), or first and last page (to prioritize the first post as a likely edit suspect). Giving a tweakable parameter for the tradeoff between edit coverage and speed.

I haven't done a full sweep of the topic bumping code. However it's worth noting that this ordering is exactly as it looks like in html on the home page of our forum. If it's bumped there, it will bump when loading.

To be extra careful in covering edits of initiatives for example, I can add a system to always load all topics in a particular category every X interval. Similar to what the definition topics are implemented like.
Or we can use convention as a low tech fix. A new post will definitely bump a topic. So a post with a summary of the edits "added 2 more PRs" would work too.

**Comment by Beanow** [comment]
:thinking: had a thought on some detecting of post deletion. All topics (https://discourse.sourcecred.io/t/64.json?page=1) have a `post_stream.stream` array of all it's post IDs. We could precede each topic bump with a delete of any post bound to this topic but not in the list.

**Comment by Beanow** [comment]
This is now resolved I believe :tada:
