### ISSUE TITLE
Keep a network log in the GraphQL mirror

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#1450]
When debugging issues relating to loading data from GitHub, it is often
helpful to insert logging statements to print every outgoing request and
incoming response. This is of course extremely noisy in general, which
is why we don’t have it on by default. But we _could_ modify the Mirror
module to save each outgoing request and incoming response to a new
table in its database. Users encountering trouble could then just send
us their database, and we’d be able to inspect the logs to look for
trouble. They wouldn’t have to build a special debugging build of
SourceCred, and even transient, hard-to-reproduce errors would have
logged useful information as soon as the problem is hit once.

We’d want to save the following properties:

  - Request data:
      - The request timestamp.
      - The stringified GraphQL query.
      - The JSON-stringified query parameters (even though they’re
        always `{}` for now).
  - Response data (once the response is received):
      - The response timestamp.
      - The raw response from the server, which should be a JSON object.
      - Whether the promise resolved or rejected.
  - Processing data (once ingestion completes):
      - The associated update ID: a primary key into the `updates` table
        that can be used to link a mutation to a database object with
        the request/response that generated it.

Note that authentication is handled by the provider of the `postQuery`
callback; the Mirror module knows nothing about it, so we don’t need to
strip out any tokens.

This would enable us to answer simple questions like “What was the query
that caused this ‘nonexistent node: undefined’ error?” as well as deeper
after-the-fact questions like “What query most recently updated the
`reactions` connection of this issue?” by cross-referencing against the
Mirror module’s existing update IDs.

(Context: I originally floated an idea like this in #998.)

**Comment by BrianLitwin** [comment]
Going to give this a shot

**Comment by BrianLitwin** [comment]
@wchargin I'm envisioning passing in a function to `postQuery` from `mirror._updateStep` that logs the response data.. does that sound right? And if so, how would you suggest testing that?

**Comment by wchargin** [comment]
It sounds like you’re suggesting changing the Mirror interface such that
`postQuery` takes an additional argument, which is itself a callback
used to log data—something like this?

```javascript
postQuery: ({
  +body: Queries.Body,
  +variables: {+[string]: any},
  // new argument:
  +logNetworkActivity: (request: JsonObject, response: JsonObject) => void,
}) => Promise<any>
```

…where `_updateStep` invokes `postQuery` with a `logNetworkActivity`
callback that updates the database?

That could work, but I don’t think that it’s necessary. It should be
possible to implement this change without changing the Mirror module API
at all. The `_updateStep` method already has access to the request, the
response, and the database. Thus, we can do something like:

 1. Immediately before calling `postQuery`, write a new row with just
    the request data. Remember the row ID of the newly inserted row:
    say, `requestRowid`.
 2. Immediately after calling `postQuery`, record the response data
    corresponding to the request from row `requestRowid`.
 3. Immediately after the data has been processed, record the update ID
    and link it to the request ID.

So, sketching (proposed updates in comments):

```javascript
    const body = [Queries.build.query("MirrorUpdate", [], querySelections)];
    // TODO: Save request data to the network log.
    const result: UpdateResult = await postQuery({body, variables: {}});
    // TODO: Save response data to the network log.
    _inTransaction(this._db, () => {
      const updateId = this._createUpdate(options.now());
      this._nontransactionallyUpdateData(updateId, result);
      // TODO: Save update ID to the network log.
    });
    return Promise.resolve(true);
```

To test this, you’d want to extend the existing tests for `update` to
check that the new network log table(s) are updated appropriately. (This
will likely involve directly poking at the tables in the test, since we
won’t provide a user-facing API to access the logs. That’s okay.) Note
that this change doesn’t introduce any new “impurities”, like I/O, that
would need to be dependency injected or mocked out: all the data is
already coming from `postQuery`; we just need to save it.

Does this make sense?

**Comment by BrianLitwin** [comment]
Thanks @wchargin ! Makes sense

**Comment by Beanow** [comment]
Oh, bummer I missed this. I think the earlier suggestion by @BrianLitwin makes a lot of sense.
Because applying this as a generic wrapper around the network request would make things much easier to re-use for Discourse and other plugins too. :sweat_smile:

**Comment by BrianLitwin** [comment]
@Beanow I'm about wrapped up with the latest iteration on #1562, but will gladly re-factor if y'all decide that making a generic wrapper is the right move 👍

**Comment by Beanow** [comment]
Just did a quick review of that. I would be happy to accept the #1562 approach. It adds logging where there wasn't any, a clear improvement :]

**Comment by wchargin** [comment]
> Because applying this as a generic wrapper around the network request
> would make things much easier to re-use for Discourse and other
> plugins too.

You’d still need to implement the database logic separately for the
Discourse SQL layer and any other plugins (at least as so far
discussed), so I don’t think that this actually buys very much reuse.

@BrianLitwin’s implementation is nearly done. If you want to implement
analogous functionality for Discourse and then unify them in a way that
clearly reduces overall complexity, taking into account the complexity
of the newly introduced layer of abstraction, go for it.
