### ISSUE TITLE
Smaller alternative to lodash.sortBy

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1488]
We had chat about `lodash.sortby` https://github.com/sourcecred/sourcecred/pull/1464#discussion_r348660981

> Hm, reason I tend to avoid this is because it's a [2630 line dependency](https://github.com/lodash/lodash/blob/4.7.0-npm-packages/lodash.sortby/index.js) to abstract away a 3 line comparison function and shallow copy instead of mutate.

> For `lodash.sortby` I'd like to have a go at replacing it with a small unit function. But since this is definitely not the only place where it would need to be used, I think that is best done as a separate PR. For now I feel this solution is way more comprehensible than the dependency.

There's only a few properties that we need from this function.
- The readability of having a "pluck" function `(x) => x.fieldToSortBy`.
- Creating a shallow copy so the input array isn't mutated.
- [Being simple](https://www.youtube.com/watch?v=rI8tNMsozo0) in implementation.

**Comment by decentralion** [comment]
A good first issue indeed. I think having a hand-rolled sortby function in the util directory would work well.

**Comment by Beanow** [comment]
Found an additional requirement.
There's a few places where we're using multiple pluck functions.
For example: sort Nodes by cred score, but when equal, sort by address string.

A complex case here
https://github.com/sourcecred/sourcecred/blob/master/src/analysis/pagerankNodeDecomposition.js#L37-L57
