### ISSUE TITLE
CI config issue, tag deploy didn't work

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1512]
There's a problem with the tagged version deployment [here](https://github.com/sourcecred/sourcecred/blob/5727a831a92418d9247d2bd7dffd0707e78f6d75/.circleci/config.yml#L94-L114)
Which has a structure of:
```yml
      - docker/publish:
          # ...
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          # ...
```

This job is intended to run only on tag releases with a `v` prefix.
However it has a requirement on a previous `test` job.

Looking at: https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag

> ### Executing Workflows for a Git Tag
>
> CircleCI does not run workflows for tags unless you explicitly specify tag filters. Additionally, if a job requires any other jobs (directly or indirectly), you must use regular expressions to specify tag filters for those jobs. Both lightweight and annotated tags are supported.

In other words, our deployment job would never run. As we require `test` to run first.
And `test` has no explicit filter to run on tag pushes. So it implicitly **won't**.

![facepalm](https://media.giphy.com/media/SEp6Zq6ZkzUNW/giphy.gif) <sup>(Oh circle and your weird config)</sup>

To fix, we need to copy the test job and set it's filter so it will run on tag pushes.
At which point we might as well call this a different workflow.

```diff
workflows:
  version: 2.0
  commit:
    jobs:
      - test
      - deploy_dryrun:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only: master
+
+  tagged-release:
+    jobs:
+      - test:
+          filters:
+            branches:
+              ignore: /.*/
+            tags:
+              only: /^v.*/
      - deploy_tag:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
```

**Comment by Beanow** [comment]
Created a test project to demonstrate.
1. [Before configuration](https://github.com/Beanow/circle-tag-filters/tree/v0.1.1), has no `deploy_tag` 
![image](https://user-images.githubusercontent.com/497556/71328391-e33aa100-2516-11ea-90d0-b0c3cd6bf688.png)
2. [After configuration](https://github.com/Beanow/circle-tag-filters/tree/v0.1.2), does have `deploy_tag`
![image](https://user-images.githubusercontent.com/497556/71328415-49272880-2517-11ea-8500-2ead10ab7a37.png)

**Comment by Beanow** [comment]
Would like to ask @vsoch if I'm not doing anything too weird here. :smile:

**Comment by vsoch** [comment]
But under what circumstances would you want to see the deploy_tag run in a PR (where I'm guessing those screen shots are?) I think you wouldn't see it in a PR because it should trigger when a tag is created.

**Comment by Beanow** [comment]
You're right. They shouldn't and don't run for a PR.
It runs on tag pushes. While previously it never ran because it couldn't satisfy it's dependency.

The screenshots are from a particular _commit's_ checkbox on GitHub.
![image](https://user-images.githubusercontent.com/497556/71328642-d6b84780-251a-11ea-815a-1337ab1d9999.png)

Because this commit was also referenced by a tag, it includes the jobs run because of the tag push.

**Comment by vsoch** [comment]
oh, your screenshots tricked me! Yes that's just right :)

It's definitely not elegant in terms of the config files, but if it gets the job done, I don't see any issue here. The alternative is to have separation of test and then build deploy, for example allocate Circle to do testing, and then GitHub workflows to do build and deploy. But this works so I don't see any need for that.

**Comment by Beanow** [comment]
> oh, your screenshots tricked me!

Heh, yeah I used firefox's screenshot to include just the div. Generally gives nice and minimal views, guess sometimes it's better to keep the context :smile:

Thanks for the feedback!

**Comment by vsoch** [comment]
Sure thing! Btw, we have a beautiful graphic on usrse now :)

https://github.com/usrse/usrse.github.io#the-united-states-us-research-software-engineer-association

**Comment by Beanow** [comment]
> Btw, we have a beautiful graphic on usrse now :)
> 
> https://github.com/usrse/usrse.github.io#the-united-states-us-research-software-engineer-association

Nice! Looking good :] I see it's running the brand new action.
If you feel like it, the forums https://discourse.sourcecred.io/ are great for sharing thoughts/feedback on how the deployment is treating you. There's more people reading there than on our github generally.

**Comment by vsoch** [comment]
oh great! I'll write a good post asking for feedback tomorrow. Thanks for the pointer!

**Comment by Beanow** [comment]
I've created a new tag ([v0.4.1+deployment-fix](https://github.com/sourcecred/sourcecred/releases/tag/v0.4.1%2Bdeployment-fix)) to trigger the build again. Now including #1513 and #1514.

Which has triggered the new workflow.
https://circleci.com/workflow-run/5344de32-be7f-4917-a6e9-eb8229475e44

But it seems like the `deploy: false` I suggested at https://github.com/sourcecred/sourcecred/pull/1514#discussion_r365443659 also doesn't log us in with the registry.

**Comment by vsoch** [comment]
Indeed if we use the orb and put deploy to false it won't log us in, but we need to do that to have more explicit control about the pushes. Why not just add:

```bash
docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}" docker.io
```

**Comment by vsoch** [comment]
If deploy is true, then we would just be pushing sourcecred/sourcecred:latest, so I think you could set deploy to true instead and then manually just push the custom tag. If you think it's unclear for the developer, we could add a note (comment) about that.

**Comment by Beanow** [comment]
Hopefully this will be the last :sweat_smile:
https://circleci.com/workflow-run/1f8f02c3-fb8f-4c02-8391-a06a476229d8

**Comment by vsoch** [comment]
Woo! Gotta love that green :) 

![image](https://user-images.githubusercontent.com/814322/72192530-5cfdd600-33c3-11ea-81d5-d7ab4c50952d.png)

**Comment by Beanow** [comment]
![image](https://user-images.githubusercontent.com/497556/72192529-6a887f80-3406-11ea-9086-89015ffac183.png)

That was more debugging that I had hopped for for a release. But it's done!
Thankfully we went through this pipe-cleaning exercise for a backport, not a hyped feature release.

**Comment by Beanow** [comment]
Thanks for all the help @vsoch :smile:
