### ISSUE TITLE
social contract

### ISSUE THREAD

**Issue by vsoch** [sourcecred/sourcecred#1525]
I'm not sure where to post this (I don't think here is the right spot) but I'm poking around various projects, and think that SourceCred might do well with something like a social contract, akin to Debian's https://www.debian.org/social_contract.  I think it would be most appropriate on sourcecred.github.io, but I couldn't post it there so here was my next idea. I think ideally we would combine the ideas from the [landing page](https://sourcecred.io/) (goals, transparency, etc.) with some basic community guidelines about how to treat one another, and what the project can (generally) promise, and what not. It's the one thing missing when I visit sourcecred.io.

**Comment by decentralion** [comment]
@vsoch I think this is a timely thing to start thinking about, Matt Zumwalt was telling me something similar in an over-the-phone discussion.

Mind re-posting this suggestion on the SourceCred Discourse? I think this is something everyone in the SourceCred community should have a say in, not just folks who follow our GitHub issues (probably < half of active SourceCred community members)

**Comment by vsoch** [comment]
Sure thing.

**Comment by wchargin** [comment]
For posterity, discussion moved to:
<https://discourse.sourcecred.io/t/community-social-contract/570>
