### ISSUE TITLE
Release v0.5.0 🚀

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1679]
![SourceCred logo](https://raw.githubusercontent.com/sourcecred/sourcecred/master/src/assets/logo/rasterized/logo_128.png) _versioned release tracker_

# Summary

Drawing from https://discourse.sourcecred.io/t/summary-of-planning-chat/300
v0.5.0 is sliced when the Initiatives plugin completes.

# Deliverables

- [x] [Load refactor](https://discourse.sourcecred.io/t/refactoring-the-load-system/629)
- [x] Initiatives plugin can use [Unified reference detection](https://discourse.sourcecred.io/t/unified-reference-detection/301)
- [x] [Initiatives plugin](https://discourse.sourcecred.io/t/write-the-initiatives-plugin/269)
- [x] [Support entries in Initiatives](https://github.com/sourcecred/sourcecred/issues/1739)

# Highlights since v0.4.0

New features:
- [Added Discourse support](https://discourse.sourcecred.io/t/create-discourse-plugin/660) (+[reference detection](https://discourse.sourcecred.io/t/discourse-reference-mention-detection/270), +[anonymous access](https://github.com/sourcecred/sourcecred/pull/1431), +[mirror revision](https://discourse.sourcecred.io/t/discourse-mirror-revision/365))
- [Added Identity support](https://discourse.sourcecred.io/t/create-identity-plugin/662)
- [Added Initiatives support](https://discourse.sourcecred.io/t/write-the-initiatives-plugin/269)
- [Published as a Docker image](https://discourse.sourcecred.io/t/publish-sourcecred-as-a-docker-image/661)
- [New data format available: `soucrecred output`](https://github.com/sourcecred/sourcecred/issues/1773)

Enhancements:
- [Minting Discourse Cred on Likes](https://discourse.sourcecred.io/t/discourse-like-minted-cred/663)
- [GraphQL Mirror EAV refactor](https://discourse.sourcecred.io/t/graphql-mirror-eav-refactor/272)
- [GraphQL Mirror fidelity awareness](https://discourse.sourcecred.io/t/graphql-mirror-fidelity-awareness/275)
- [Keep a network log in the GraphQL mirror](https://github.com/sourcecred/sourcecred/issues/1450) (PR #1562)
- [WeightedGraph; Enable plugins to set weights](https://discourse.sourcecred.io/t/weightedgraph-enable-plugins-to-set-weights/664)
- [Load refactor](https://discourse.sourcecred.io/t/refactoring-the-load-system/629)
- [Unified reference detection](https://discourse.sourcecred.io/t/unified-reference-detection/301) (_in progress_, the major pieces have been implemented, but not all plugins have migrated)

# Checklist

- [x] 1. Preparation
  - [x] Merge main deliverables
  - [x] User documentation for all major changes https://github.com/sourcecred/sourcecred/issues/1679#issuecomment-625335274
  - [x] Update release notes
  - [x] Update dependencies #1785, #1786
- [x] 2. Sign off release (serves as a "release review")
  - [x] Bump version #1787
- [x] 3. Releasing
  - [x] Git tag 
  - [x] Docker image (CD)
  - [ ] ~~NPM package~~
- [ ] 4. Announcements
  - [x] GitHub release notes - [release v0.5.0](https://github.com/sourcecred/sourcecred/releases/tag/v0.5.0)
  - [ ] Discord announcement
  - [ ] Blog post?

**Comment by Beanow** [comment]
Having a go at tracking releases ipfs style. What do you think of the idea? And am I missing anything obvious? cc @wchargin @decentralion @vsoch @BrianLitwin

**Comment by vsoch** [comment]
Some projects also maintain branches that correspond to the release in case a hotfix is needed.

Would the larger refactor for the algorithm be some version v1.0.0?

**Comment by Beanow** [comment]
> Some projects also maintain branches that correspond to the release in case a hotfix is needed.

Current SourceCred should be considered alpha, [transitioning into beta](https://discourse.sourcecred.io/t/sourcecred-beta-roadmap/422). Hence the v0.x versioning.
Stable branches is not something I would support till a v1 lands, hotfixing would be [really exceptional](https://github.com/sourcecred/sourcecred/pull/1504).

> Would the larger refactor for the algorithm be some version v1.0.0?

Right now, I don't have a good intuition when [the algorithm refactor](https://github.com/sourcecred/sourcecred/compare/wchargin-fibration) should land. But I do think it would be as a 0.x release.

My best guess would be something like:
- v0.5.0: release initiatives
- v0.6.0: productivity & quality of life update (automate grain, review/release github action, ...)
- v0.7.0?: _possibly_ fibration refactor,
maybe Discord plugin,
maybe a smaller feature skipping the queue,
whichever comes first.

**Comment by vsoch** [comment]
alrighty, whichever version gets pinned to the specific algorithm updates, I'll develop sourcecred-python on top of that (the assumption being the core is unlikely to have huge change).

**Comment by decentralion** [comment]
Having a 0.5.0 on the initiatives plugin makes sense to me.
Having 0.6.0 be the QoL (e.g. instance system) works for me. I could imagine CredRank coming in sooner or around the same timeframe (@wchargin seemed willing to champion it landing short-term -- though he also said he's busy with TF dev summit stuff for a few weeks).

@vsoch, I think 1.0.0 is still a long ways off. Once we go 1.0.0 I want us to start treating changes that alter the cred distribution as breaking changes, and we're still a while away from being ready to offer that. When we 1.0.0, we might also want to split out plugins on independent versioning.

**Comment by vsoch** [comment]
Makes sense. I figured the algorithm changes might be breaking and warrant a refactor and version bump, but I was wrong.

**Comment by decentralion** [comment]
The algorithm change will definitely warrant a version bump -- just per semver, since we haven't reached 1.0, we'll bump the second digit.

**Comment by Beanow** [comment]
> Having 0.6.0 be the QoL (e.g. instance system) works for me. I could imagine CredRank coming in sooner or around the same timeframe

Yeah for reasons like this I feel like we probably shouldn't specify which version will get which features until the last minute, so these are just guesstimates :smile:

For now we could say, both QoL and CredRank warrant a release. If they're 2+ weeks apart in terms of completion, they could get their own releases, whichever comes first. If they're within 2 weeks, it could be combined into one release that has both?

**Comment by Beanow** [comment]
**`@here`** I've added a new item: 1. Preparation / "Beta-test main deliverables"

What I mean by that here is: using Initiatives in our own SourceCred instance. We might get some follow-up changes by using it, and have better docs / recommendations, so as a general rule it would make sense to me to slightly delay a release for a chance to include this. :smile:

What do you think?

(cc @s-ben who's working on this particular test)

**Comment by decentralion** [comment]
It looks like @wchargin's work on making the GH plugin more robust (#998) will land in 0.5.0, so let's be sure to give that a shoutout in the release notes.

**Comment by decentralion** [comment]
Also, @beanow: definitely agree that we should beta test the initiatives plugin a bit before the release. Let's have at least a few initiatives that we're using before we publicly encourage others to use the API. :)

**Comment by Beanow** [comment]
Also suggesting:
  - [ ] Update dependencies

As greenkeeper doesn't keep everything perfectly green. Doing a manual chore commit to update dependencies for a versioned release would be nice especially for the docker image.

**Comment by decentralion** [comment]
Sounds good to me.

**Comment by Beanow** [comment]
Adding the highlights was a fair bit of work. 280+ commits since the last release in august last year.

So I'm inclined not to go through and update this with even more fine-grained, yet arbitrary, detail
https://github.com/sourcecred/sourcecred/blob/master/CHANGELOG.md
What are your thoughts on this?

**Comment by decentralion** [comment]
Yeah, we haven't really been using the CHANGELOG. Maybe we should delete it if isn't a part of our workflow.

Thanks for finding the highlights.

**Comment by Beanow** [comment]
Cool! Then I'll consider the release notes updated, we can pull in the highlight list. Feel free to suggest edits though.

CHANGELOG workflow wise, it's not clear when something should or shouldn't be in it. As every PR would definitely be too granular to be useful. With a more specific guideline on that we could probably include it as part of our review process and update it consistently. But probably should figure out who we're maintaining it for to do that.

**Comment by decentralion** [comment]
Stuff that's missing in the highlights: we made it possible to depend on SC as an API: see https://github.com/sourcecred/sourcecred/pull/1526 (and #1536 #1537)

**Comment by Beanow** [comment]
Should have:
- Required documentation
- Sign off before release

**Comment by Beanow** [comment]
> Stuff that's missing in the highlights: we made it possible to depend on SC as an API: see #1526 (and #1536 #1537)

I did make judgement calls on what is a highlight candidate.
Since there are several hundreds of commits included, it's not an exhaustive list.
So if the suggestion is because it was not exhaustive, yep! That's intentional.
If you think it should be highlighted, next question is:

For that highlight, can you link it to an initiative or something that works as a primer on what it is?
This seems to be related to https://discourse.sourcecred.io/t/enable-cred-analysis-notebooks/573
I'm happy to update/maintain the issue highlight suggestions, but will ask suggester to write them up  :]

**Comment by decentralion** [comment]
> For that highlight, can you link it to an initiative or something that works as a primer on what it is?
This seems to be related to https://discourse.sourcecred.io/t/enable-cred-analysis-notebooks/573
I'm happy to update/maintain the issue highlight suggestions, but will ask suggester to write them up :]

Fair. Let's leave this out for now, and punt on announcing any API dep support until we also publish on NPM. (Let's punt on npm publishing for another release, so we can give proper distinct attention to setting that up.)

**Comment by Beanow** [comment]
Discussed the release requirements with @decentralion in another call.

**Suggest we scrap beta-feedback**

As the project itself is in _beta_ status. Delaying releases on beta-feedback is a large slowdown. For PRs we had a similar discussion and decided not to delay PRs because we might want to change it based on future feedback. Instead embracing "should have been different in retrospect" PRs. Likewise for releases I suggest we scrap the beta-feedback step, and include this feedback in future releases.

**Details on documentation requirements**

For this particular release, we're going from no docs requirement, to _a_ docs requirement.
And for now I think we shouldn't set the bar too high.

Having a `.md` file in the repository, similar to https://github.com/sourcecred/sourcecred/pull/1720 and https://github.com/sourcecred/sourcecred/pull/1728. Is the level to aim for in this release I think. In future releases we can improve our documentation game with more solid organization, expectations and rendering.

Following the advice from the past team call as well. The suggestion by @s-ben there was that getting information from the expert/author is the hardest part. This will ensure _some_ documentation by them exists and can be refined later.

**Comment by Beanow** [comment]
Since docs were not yet ready, a new deliverable snuck in as well. "Create new contributions from JSON files" #1739

The release feels long overdue, so I think it's necessary to lower the bar for documentation even further. To let #1779 release workflow experiments proceed while in alpha. My intention is to add "bare minimum notes" level documentation for the remaining features and prepare to ship this release. Considering we have a documentation roadmap independently of this, I'm confident we'll refine those notes into proper docs later.

**Comment by Beanow** [comment]
Going to claim that all feature documentation exists or is on it's way:
- Discourse plugin:
  - https://github.com/sourcecred/docs/pull/70
- Identity plugin:
  - https://github.com/sourcecred/sourcecred/blob/master/src/plugins/identity/README.md
- Initiatives plugin:
  - https://sourcecred.io/docs/concepts/initiatives
  - https://sourcecred.io/docs/setup/plugins/initiatives
- Docker image:
  - https://github.com/sourcecred/sourcecred/blob/master/README.md
  - https://github.com/sourcecred/docs/pull/71

**Comment by Beanow** [comment]
Suggesting that the NPM packaging is currently not ready for use yet. Striking through that for this release.

**Comment by decentralion** [comment]
FYI since https://github.com/sourcecred/sourcecred/pull/1783 just merged, we can include mention of the `sourcecred output` command in the release notes.

**Comment by Beanow** [comment]
Agreed, I think we should. I'm inclined to link to #1773 as the context for this. Would be great if you could introduce the feature a bit there like we do for Initiatives. :]

**Comment by decentralion** [comment]
Closing this since we released 0.5.0 quite a while ago!
