### ISSUE TITLE
Switch to CredRank

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1686]
During CredCon, wchargin and I prototyped a new version of the SourceCred algorithm, called "CredRank". This is a tracking issue for merging CredRank into master and replacing [timeline cred](https://discourse.sourcecred.io/t/timeline-cred-prototype/115).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038446129020) by [Unito](https://www.unito.io/learn-more)

**Comment by Beanow** [comment]
See also
https://discourse.sourcecred.io/t/credrank-scalable-interpretable-flexible-attribution/654
