### ISSUE TITLE
Attack Vector - any team member can edit PR descriptions

### ISSUE THREAD

**Issue by hammadj** [sourcecred/sourcecred#1708]
Right now, I could go into all the old PRs and tag myself in the description with "Paired-with @hammadj" to steal cred from all the contributors. Not sure what the best solution to this would be, but these are the permission levels available in GitHub: 
![image](https://user-images.githubusercontent.com/7143583/76917310-a1589700-6888-11ea-8f13-593fcf9d0df4.png)

**Comment by decentralion** [comment]
@wchargin You're right that this attack is not part of our current threat model. That said, I think it's good for us to track attacks like this regardless--would be good to have some docs that track all the attacks we know about. (Or, we could make an "attack" label on GitHub?")
