### ISSUE TITLE
SourceCred hosted prototype is down

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1761]
Ever since we rolled out the docasaurus website, https://sourcecred.io/cred/timeline/@sourcecred/ gives a "Page not found" issue.

@hammadj and I tried fixing it via https://github.com/sourcecred/website/pull/7 but that didn't work. 

We somehow need to make sure that url goes to the github pages based in the https://github.com/sourcecred/cred repository, but not sure how. Will probably need more experimentation.

**Comment by Beanow** [comment]
Resolved by moving to a different subdomain: http://cred.sourcecred.io/
