### ISSUE TITLE
Create an "editor" for Initiatives

### ISSUE THREAD

**Issue by hammadj** [sourcecred/sourcecred#1778]
Currently, initiatives have to be manually created as JSON files in GitHub, like so: https://github.com/sourcecred/cred/tree/master/initiatives

Would be great to have a UI to edit these initiatives, possibly just a form type thing to start with where:
- the weights are just a dropdown picker for fibonnaci weights
- linking to other initiatives is also a dropdown so we dont have to think about file names and make sure they are correct, etc.
- inline initiatives can be defined easily
- Calendar picker for timestamp
- Dropdown for champions picker as well or ability to manually add GitHub or forum usernames

Could use this library possibly to make things easier: https://github.com/typicode/lowdb

Nice to have features:
- Ability to see how the cred flows for a given initiative to the different nodes
- Ability to enable/disable an initiative to compare before and after scores

**Comment by Beanow** [comment]
Just want to offer a few thought on how to make the issue more accessible to new contributors.

The more context available the better :]
After all, if you're less likely to already know this.
Examples:
- What problems we're hoping this will solve / why it matters.
  (To improve [inclusivity](https://sourcecred.io/docs/setup/plugins/initiatives/#status-and-caveats), to create initiatives faster?)
- Some kind of implementation plan.
  Creating a standalone prototype first (good first issue), then taking what we like for long term UI improvements.
- Expectations. Like requirements, which repo to work in, who to get reviews from, and support they might receive.

**Comment by decentralion** [comment]
I would love to see someone take this on. I like the idea of using this as a "Request for Champion" -- we could even try funding it as an initiative with a material cred bounty on completion. That said, I think we need a "RFC Champion" to own the pipeline for prospective champions, and figure out how to get the message out. Feels like something for outreach team. I know @LexBirdie was thinking about "Help Wanted" posters, maybe this could be a trial run?

**Comment by blueridger** [comment]
hashtag creditor
