### ISSUE TITLE
type error: Compatibles are not JsonObjects

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1875]
Currently, the Compatible type is defined as follows: 
https://github.com/sourcecred/sourcecred/blob/7797c120e61ef7f501b64b5db39f44d3b178f368/src/util/compat.js#L4-L8

The Combo.JsonObject type is defined as follows:

https://github.com/sourcecred/sourcecred/blob/7797c120e61ef7f501b64b5db39f44d3b178f368/src/util/combo.js#L6-L12

At present, it's not possible to treat a Compatible object as a JsonObject. This is documented in the following test case:

https://github.com/sourcecred/sourcecred/blob/cbfa6ed64856e1b5a1edea8edfce649cb9c0283e/src/util/compat.test.js#L24-L29

Once this is fixed, we should be able to remove the `// $ExpectFlowError` in that test case.

**Comment by wchargin** [comment]
Blocked on <https://github.com/facebook/flow/issues/8405>.

We could work around that if we’re willing to make the `Compatible<T>`
type transparent rather than opaque.

**Comment by decentralion** [comment]
I'm fine with making `Compatible<T>` transparent.
