### ISSUE TITLE
Discourse: Flow topic cred based on posts' likes

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1896]
The Discourse plugin creates a Cred Graph to flow Cred based on interactions on Discourse forums, e.g. https://discourse.sourcecred.io. Currently, there are four types of nodes:
- Users
- Topics
- Posts
- Likes

At present, the topic nodes are connected by edges to:
- the posts in the topic
- the user who created the topic

With the default weights, very little Cred flows "out" from a topic. Cred used to flow from the topic to every post in the topic, but as of https://github.com/sourcecred/sourcecred/pull/1681 we changed that, because it was rewarding "spammy" posts in high-value topics.

However, having so little Cred flow away from topics is awkward, because it means topics can become "cred vortexes" where Cred gets stuck and isn't able to readily flow away. It only flows out to the author of the topic, but this risks giving too much Cred to the author.

One suggestion from @LongForWisdom was to flow Cred from a topic based on the likes in the topic. This gets at the idea that whichever posts in the topic were liked by readers of the topic were, in fact, valuable to the topic as a whole. If we add this, then it becomes feasible to Mint large amounts of Cred directly to valuable topics, and get it distributed in a way that makes sense.

We can make this change by modifying the `addLike` method in discourse/createGraph.js, so that in addition to creating a Like node edges connecting the Like to the like-creator and the post, we also create an edge from the topic to the post that was liked. We could call this a `hasLikedPost` edge, and include the like's associated username and postid in the edge address, to ensure no address conflicts.

https://github.com/sourcecred/sourcecred/blob/219c4490b26f78d7eb7c1b716c11b37e00baae41/src/plugins/discourse/createGraph.js#L194-L213

https://github.com/sourcecred/sourcecred/blob/219c4490b26f78d7eb7c1b716c11b37e00baae41/src/plugins/discourse/createGraph.js#L233-L239

Since the LikeAction does not include the associated topic, (see below), we'd need to maintain some sort of `postIdToTopicAddress` map in the graph creator (similar to postIdToDescription, or topidIdToTitle).

https://github.com/sourcecred/sourcecred/blob/219c4490b26f78d7eb7c1b716c11b37e00baae41/src/plugins/discourse/fetch.js#L82-L88

This should also have a new test case added to createGraph.test.js which verifies that the new edges are instantiated properly, as was done with (for example) createsLikesEdges:

https://github.com/sourcecred/sourcecred/blob/219c4490b26f78d7eb7c1b716c11b37e00baae41/src/plugins/discourse/createGraph.test.js#L484-L487

Some reference materials:

Add likes edges to the graph: https://github.com/sourcecred/sourcecred/pull/1299
Create a node for each Discourse like: https://github.com/sourcecred/sourcecred/pull/1587

As ever, whoever takes this on should first read [CONTRIBUTING.md](https://github.com/sourcecred/sourcecred/blob/master/CONTRIBUTING.md)

**Comment by benoxmo** [comment]
hey, I'd like to spend some time on that. Has anyone worked on it yet?

**Comment by decentralion** [comment]
I don't believe anyone is working on it. Go for it @benoxmo!

**Comment by benoxmo** [comment]
ok, I'll have a go.

**Comment by decentralion** [comment]
Props to @benoxmo for the great idea of using Whimsical to diagram changes to the Graph structure. Here's a diagram for this change:

![image](https://user-images.githubusercontent.com/1400023/87204738-6e646400-c2ba-11ea-9c9f-1e6962d136f6.png)

We want to add the dashed-blue lines connecting topics to posts in the topic, when posts in the topic got likes. The weight of that edge should be equal to the number of likes. (In the original issue, I suggested making multiple edges from the topic to the post, one for each like, but using weights will be cleaner.)

Link to diagram: https://whimsical.com/EcM2dqAar1oTC1jYCR5i7P
