### ISSUE TITLE
Consider refactoring away the address–payload distinction

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#190]
Currently, a node has both an address and a payload. The address ID
needs to uniquely identify the node, and the payload holds anything else
that we want to store.

This can be confusing: if you have a node and want to access a field,
you have to think about where the data lies. It’s a leaky abstraction.

Also, as the address ID must be a string, this often leads to “stringify
the whole shebang and put it in the payload”. If you want to get the
data back out of the node, you have to either additionally store it in
the payload (wasting space and causing extra confusion) or parse the ID
(slow, breaks typing, and generally considered a Questionable Idea).

We should consider eliminating this distinction by doing something more
reasonable.

(This all applies to edges, too.)

**Comment by wchargin** [comment]
Here is one idea: nodes are arbitrary JSON blobs with a `type`
identifier; plugins register handlers that take nodes of a fixed `type`
to a unique address.

In more detail, suppose that we define nodes as follows (names up for
discussion):
```js
interface Node {
  __type: {|
    +repositoryName: string,
    +pluginName: string,
    +type: string,
  |};
}
```
Then, a plugin can register a handler:
```
type Id = string;
interface AddressHandler<T> {
  (node: Node<T>): Id;
}
type AddressHandlers = {[type: string]: AddressHandler};
```

For simple nodes, this can just be a projection:
```js
type Commit: Node = {|
  __type: {|
    +repositoryName: string,
    +pluginName: "sourcecred/git-beta",
    +type: "COMMIT",
  |},
  hash: string,
  summary: string,
|};
function handleCommit(commit: Commit) {
  // Commits can be uniquely identified by hash.
  return commit.hash;
}
```
Something more complicated, like `JSON.stringify(someFieldsOfNode)`,
might be necessary for more complicated nodes.

In some sense, this addressing function can be considered an
optimization, because `JSON.stringify(theWholeNode)` should always be a
safe (i.e., injective) implementation. This implementation has a few
downsides, though. First, memory performance: using a commit’s full
summary, or a blob’s full contents, as an address will lead to a lot of
wasted space. This is especially true for nodes with lots of incident
edges. Second, decreased lookup potential: using `handleCommit` above,
one can write
```js
graph.node(gitPlugin.commitNodeAddress(someHash)).summary
```
to find the summary of a commit for which only the hash is known. (This
pattern obviously generalizes.) If the content-addressing requires the
whole object, then this is no longer feasible. It could be argued that
this is not inherently bad, that a graph is not necessarily supposed to
be a key–value store.

Lots of details remain to be filled in, of course. Thoughts welcome.

**Comment by decentralion** [comment]
I like this proposal, and am open to implementing it soon (and, as ever, we can try it out and see how we like it in practice).

One addition: I think we should get rid of the `repositoryName` field. In cases where the repositoryName is actually needed to disambiguate, the projector logic can be responsible for inserting it, but in many cases (e.g. Git and GitHub plugins), it seems unnecessary.

I think what we were aiming for with the repositoryName field was really something more like: `publisher`, i.e. which entity has responsibility for updating this information / can canonically provide the source of truth? However, conflating that with repository boundaries needlessly complicates cross-repository projects. For now, I think we can assume that all graphs exist in the purview of a single publisher (the entity that created it) and we can hold off on adding publisher-type information until the requirements are clear.

**Comment by wchargin** [comment]
Per @decentralion 's suggestion, I've created PR #296 to discuss this design doc.

**Comment by wchargin** [comment]
Duly considered.
