### ISSUE TITLE
Create a `sourcecred-ci` or `sourcecred-bot` user

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#194]
Currently, Travis CI uses my personal auth key to run cron jobs that hit
the GitHub GraphQL API. This is okay as a concession for the very short
term, but I’d like to move away from it as soon as possible.

There is [a StackOverflow question about this][1]. The accepted answer
is from a GitHub employee, who suggests creating a machine account for
this purpose. Given that the API key would only be used from cron jobs,
running at most once daily and using just a handful of API tokens, this
seems easily in line with the terms of service. As further comfort, [the
GitHub help page on managing deploy keys][2] says:

> cannot automate the creation of accounts. But if you want to create a
> single machine user for automating tasks such as deploy scripts in
> your project or organization, that is totally cool.

[1]: https://stackoverflow.com/questions/31159275/how-do-i-generate-the-github-oauth-token-for-organization-accounts
[2]: https://developer.github.com/v3/guides/managing-deploy-keys/

**Comment by wchargin** [comment]
cc @decentralion

**Comment by decentralion** [comment]
How about "credbot"? I was thinking we might want to have a bot that can help users learn SourceCred workflows or help data collection, e.g. by showing up on newly created issues and giving info on how to use GH reactions to attribute cred (assuming the repo owners asked for credbot's presence). 

although maybe our CI user should be isolated from our commenting-on-issues user

**Comment by decentralion** [comment]
Created @sourcecred-ci and put their tokens into Travis
