### ISSUE TITLE
Create Discord Bot to Report Cred Real-Time

### ISSUE THREAD

**Issue by Bex2594** [sourcecred/sourcecred#1974]
Having a simple way to check on one's Cred could be a cool way to see how your Cred grows with specific contributions. It would be a tool to understand how Cred Flows (and mints) and also a way to receive validation for one's efforts any time. The Bot would tell you your Cred Score, explain that Cred changes over time, and provide links to additional resources to understand Cred and an individual's Cred and grain, such as [Earning Cred](https://sourcecred.io/docs/guides/earning-cred), the [SourceCred UI](https://cred.sourcecred.io/timeline/@sourcecred/), and the [Grain UI](https://observablehq.com/@sourcecred/sourcecred-week-41).

Here is a proposal for the Cred Reporter Bot response:
As of _date and time_, your Cred score is _###_. Cred changes even when you are inactive, so this number will change. 
- To learn more about how Cred flows, read [Earning Cred](https://sourcecred.io/docs/guides/earning-cred).
- To see everyone's Cred scores, check out the [SourceCred UI](https://cred.sourcecred.io/timeline/@sourcecred/).
- To see your Grain ledger, check out the [Grain UI](https://observablehq.com/@sourcecred/sourcecred-week-41).

**Comment by benoxmo** [comment]
the action plan is here : https://discourse.sourcecred.io/t/discord-introduction-bot-questions-actionable-items/792/4

**Comment by benoxmo** [comment]
a first version locally run is here : https://github.com/benoxmo/infoBot

**Comment by befitsandpiper** [comment]
We have something like this for 1hive in the assistant-bee bot: https://github.com/1Hive/assistant-bee/blob/master/src/handlers/mycred.js

However, the cred is often inaccurate. I believe the live site still has syncing issues, and is not always up to date.

**Comment by blueridger** [comment]
Credbot is live! https://github.com/benoxmo/infobot
