### ISSUE TITLE
Decide on a unicode symbol for Cred

### ISSUE THREAD

**Issue by dandelionmane** [sourcecred/sourcecred#2]
It's important that Cred have a unicode symbol. This will save us from needing to write "SourceCredCred" and other such ungainly constructs.

I've been provisionally using ¤ as the symbol; I like that it is reminiscent of a network, something that is both a circle and has flows in/out... the circle represents egalitarian community and the edges represent new contributions? :smiley: 

Here are some other options:
¢￠ ₡ ¢ ₢ ₵

Here are all the options in context:

SourceCred¤
SourceCred¢
SourceCred￠
SourceCred₡
SourceCred¢
SourceCred₢
SourceCred₵

![image](https://user-images.githubusercontent.com/1400023/35776257-cffa59d2-094d-11e8-8c7b-ccac52fe59a9.png)

My vote is for ¤. Please feel free to suggest characters I haven't thought of yet. There are *a lot* of them.

Also, yes this is the bikeshed.

**Comment by 000drax** [comment]
I like the symbol idea!

Chiming in on the bikeshed... I think the symbol should be simple and familiar.
SourceCredϾ
SourceCred¿

I'm rather partial to the Lunate Sigma (Ͼ).

**Comment by dandelionmane** [comment]
I like Lunate Sigma too, although I'm still quite fond of the [currency sign ¤](https://en.wikipedia.org/wiki/Currency_sign_(typography)). Now that I know that ¤ semantically means "an unknown currency" it seems pretty appropriate. 

Some more examples to look at:
Python¤
TensorFlow¤
Git¤

PythonϾ
TensorFlowϾ
GitϾ

Hmm, the fact that Lunate Sigma looks like a "C" does make it easier for my brain to parse/pronounce PythonϾ as "PythonCred"

**Comment by dandelionmane** [comment]
Ooh, another benefit to using Ͼ: Everywhere that I was writing "Cred", I can now write "Ͼred". That makes it extremely transparent that Ͼ stands for Ͼred. 

I'm going to switch to Lunate Sigma as the default choice for unicode symbol :D

**Comment by dandelionmane** [comment]
Another benefit to Ͼ: if someone wants to write 1000Ͼ but doesn't know how to grab that unicode symbol, they can just write 1000C and it will still be pretty clear what they mean.

**Comment by wchargin** [comment]
Two notes on the lunate sigma:
  - At least to me, it is very hard to distinguish from a standard "C". The dot is small and not prominent, as opposed to the strokes in the dollar, euro, pound, etc. signs.
  - We would need to specify "dotted lunate sigma", which is not the standard variant. A capital lunate sigma (U+03F9) is just Ϲ `Ϲ`; the dotted one is U+03FE Ͼ `Ͼ`. (Somewhat unfortunately—if [unsourced Wikipedia][1] is to be believed—the dotted form is "an editorial sign indicating that the line so marked is at an incorrect position.")

[1]: https://en.wikipedia.org/w/index.php?title=Sigma&oldid=822738925#Lunate_sigma

My two cents:
  - I like U+A4 CURRENCY SIGN ¤ `¤`. It's kind of amusing that you suggested it without knowing the currency-related meaning! :-) Interpreting "unknown currency" as "arbitrary currency" seems very appropriate to me. The standard glyph is simple and unambiguous.
  - *And* it's in Latin-1, which—practically speaking—has the potential to avert a lot of problems. Of the options in Latin-1, it seems the best to me.
  - As a less-valuable-but-also-nice technical boon, the catcode of ¤ is "Symbol, Currency", while Ϲ is "Letter, Uppercase".
  - I suspect that picking anything that looks like the "cents" symbol, as in a few of the examples, would lead people to read "GitCents" and "TensorFlowCents", which doesn't really match what you want.

**Comment by dandelionmane** [comment]
I'm going to close this issue in favor of ¤ as our symbol for SourceCred. This is absolutely something we can revisit later if someone comes up with a compelling reason to switch to a different symbol in particular.
