### ISSUE TITLE
GitHub pages deploy broken

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#2093]
Consider the following repository [decentralion/makerdao-instance-demo](https://github.com/decentralion/makerdao-instance-demo/) which was created from our template instance. It's deployed on GitHub pages at https://decentralion.github.io/makerdao-instance-demo/. However, it fails to load, because it tries to request https://decentralion.github.io/sourcecred.json rather than the correct url of https://decentralion.github.io/makerdao-instance-demo/sourcecred.json.

I believe @ecwireless has reported the same issue.

**Comment by topocount** [comment]
I believe I found the issue. Pushing a fix shortly
