### ISSUE TITLE
New SC Explorer Dashboard: Top Chart

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2229]
Atomic-style ticket for #2227 — Top Chart component:

![SourceCred Explorer Dashboard - 1  Top Chart@2x](https://user-images.githubusercontent.com/33087/92655394-2c4da380-f2a6-11ea-8f8b-5d92d075fc5e.png)

**Specifications:**

* Chart is flexible width, 100% width of explorer container (meaning: the width of the `<table>` in the current explorer)
* Chart height: aim for 100px, check in with KuraFire if that doesn't render the lines well
* The X-axis of the Top Chart should have markers at the beginning (left), and end (present day, right). 
  * FUTURE EXPANSION: labels and more markers, but some data gathering is needed first.
  * FUTURE EXPANSION: hover mini-popovers on the chart lines that show number + date
* Chart has **3** lines (colors listed are for **DARK THEME**):
  * `#6174CC` Blue for **Cred**
  * `#FFAA3D` Yellow for **Grain**
  * ~~`#FDBBD1` Pink for **Participants** — see CAVEAT on **"Active Participants"** below~~
* The Legend in the bottom left matches the colors as small circular swatches without a border, unlike the image suggests (wait for visual UI comps for details; in the interim, use 1em height & width).

**Update 2021-02-05:** the Participants elements of the top chart (line, legend) & stats circle are taken out for the time being, pending future design.

#### ~~CAVEAT on **"Active Participants"**~~
~~The attached image of the Top Chart wireframe mentions "active participants"; this term is measured as follows:~~

> ~~Participants who made **a contribution that earned Cred**~~

~~The Top Chart and the "Contribution Chart" column in the Activity Table always show data for All Time. In the rest of the Explorer wireframe, it means:~~

> ~~Participants who made **a contribution that earned Cred** _during_ the selected Timeframe~~

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038574980018) by [Unito](https://www.unito.io/learn-more)

**Comment by KuraFire** [comment]
@befitsandpiper Just a heads up, the Explorer UI is initially going to be designed in Dark mode, so I've updated the colors in this ticket to reflect the ones I'll be using.

**Comment by blueridger** [comment]
V1 will not have active participants.

**Comment by blueridger** [comment]
Acceptance Criteria:
- Cred and Grain aggregates are both shown as overlapping lines
- Cred and Grain are in the legend
- Correct colors are using
- lines should be affected by existing filtering logic

Non Acceptance Criteria
- Participants should not be included
- Time window selection

**Comment by KuraFire** [comment]
Addendum, following sync-up with @befitsandpiper:

* Participants circle should also not be included
* X axis line should be 2 pixels thick
* Top Chart (incl.) X axis line should be exact same page width as the Activity Table, or "100% width of the page container" that holds the contents.

**Comment by blueridger** [comment]
V1 should not include grain per cred
