### ISSUE TITLE
New SC Explorer Dashboard: Stats Circles

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2237]
Atomic-style ticket for #2227 — Stats Circles component:

![SourceCred Explorer Dashboard - 3  Stats Circles@2x](https://user-images.githubusercontent.com/33087/92780941-88710000-f358-11ea-807a-642ca21227e4.png)

### Specifications:

- Circles are 128px × 128px to start
- Circle colors are:
   - `#6174CC` Blue for **Cred**
   - `#FFAA3D` Yellow for **Grain**
   - ~~`#FDBBD1` Pink for **Participants**~~
   - `#4BD76D` Green for **Grain Per Cred**
- Text inside the Circles should resize to fit on one line; suggested font size ranges:
   - min. size: 21px
   - max. size: 34px
- Text labels below the Circles are in 21px to start. Upon implementation we may adjust. 
- Exact label names for the Circles (note capitalization):
   - Cred This Week
   - Grain Harvested
   - ~~Active Participants~~
   - Grain per Cred
- Spacing between the Circles:
   - `margin-left: 0` (left-aligned to the same container that holds all other content)
   - `margin-right: 0` (right-aligned to the same container)
   - flexible spacing in-between the circles, with a **minimum gutter width of 20px**
- Spacing below Circles (above labels): **13px**

**Update 2021-02-05:** The Active Participants circle is to be taken out for now, pending future design changes.

**Comment by blueridger** [comment]
Shouldn't have closed. New AC:
- top stats are NOT affected by filtering/pagination

Not AC:
- top stats will be affected by Timeframe Control only

**Comment by KuraFire** [comment]
Addendum:

The Active Participants circle is to be taken out for now, pending future design changes.

**Comment by blueridger** [comment]
V1 should not include grain per cred

**Comment by BrianBelhumeur** [comment]
To clarify:
- We will only have two circles, "Cred This Week" and "Grain Harvested"?
- Since the stats will be affected by the timeframe control, I assume the label on "Cred This Week" should update to reflect the interval being shown

**Comment by KuraFire** [comment]
@BrianBelhumeur both of these assumptions are correct. The Stats circles should reflect the Timeframe Control's / top chart's selected period of time. And to start, we'll only have two Stats circles for now.
