### ISSUE TITLE
New SC Explorer Dashboard: Plugin Bar Chart

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2261]
Atomic-style ticket for #2227 — Plugin Bar Chart component. See UX wireframe image below.

## Specification

**Colors:**
- `#D7E2F3` for GitHub
- `#6174CC` for Discord
- `#FB89AB` for Discourse 

**Widths & Heights:**
- Numbers above the bars in the chart are `24px bold`
- Columns should be `55px` wide, with a `34px` gap (gutter)
- Gap from bar chart to Legend below: `55px`
- Legend boxes: `21px` (square)
- Legend labels are `30px normal` 

UX Wireframe:
![SourceCred Explorer Dashboard - 5  Plugin Bar Chart@2x](https://user-images.githubusercontent.com/33087/93148549-f135e080-f6a8-11ea-8b8a-dd794d8a56ea.png)

Visual composition (WIP):
<img width="144" alt="SourceCred Plugin Bar Chart - Visual" src="https://user-images.githubusercontent.com/33087/93150835-0f064400-f6af-11ea-8729-77e51e273b85.png">

Color blindness variations (tested for accessibility):
<img width="629" alt="SourceCred Plugin Bar Chart - Visual (Chromas)" src="https://user-images.githubusercontent.com/33087/93150840-13326180-f6af-11ea-950b-94d37184f030.png">

**Comment by KuraFire** [comment]
The plugin bar chart UI has been pushed back on and is likely to be nixed. I'm hesitant to close this issue or add a Wontfix label just yet, but no development cycles should be spent on this ticket at this time.

**Comment by decentralion** [comment]
@KuraFire I suggest closing it if we aren't working on it--it's easily reversible if we change our minds later. In the limit, if we are super hesitant to close things, we can expect our open issues to be super noisy and unusable (which they arguably already are ;) )
