### ISSUE TITLE
Explorer Home Frontend API connection

### ISSUE THREAD

**Issue by befitsandpiper** [sourcecred/sourcecred#2297]
This ticket is for connecting the API for the Explorer Home page to the new frontend, and setting up proper data and functionality for all components. It is possible this will be split further into a few PRs.

related to catch-all ticket here: https://github.com/sourcecred/sourcecred/issues/2227

**Comment by blueridger** [comment]
Closing in favor of https://github.com/sourcecred/sourcecred/issues/2464
