### ISSUE TITLE
Explorer Home frontend cleanup/final pass

### ISSUE THREAD

**Issue by befitsandpiper** [sourcecred/sourcecred#2298]
This ticket is to cleanup any minor styling/design spec issues remaining.

catch-all ticket can be found here: https://github.com/sourcecred/sourcecred/issues/2227

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038482971852) by [Unito](https://www.unito.io/learn-more)

**Comment by blueridger** [comment]
Launch blocking feedback from @KuraFire 

- [ ] Add a second pagination utility row above the table header
- [ ] Remove the background fill color from the pagination utility rows (top and bottom)
- [ ] Checkboxes at the bottom should start out checked
- [ ] when no checkboxes are checked the table should be empty
- [ ] Add this help text row above the average row:
```
<TableRow key="help-text">
                  <TableCell colSpan={4}>
                    Average and Total numbers represent the list shown above only.
                  </TableCell>
                </TableRow>
```

**Comment by BrianBelhumeur** [comment]
All set!
