### ISSUE TITLE
Setup CI integration

### ISSUE THREAD

**Issue by dandelionmane** [sourcecred/sourcecred#23]
We should set up CI integration. What I have in mind is pretty basic:
- should be fast (build & test <1min would be ideal, slower than 3 mins is bad IMO)
- should run `yarn flow`, `yarn test`, and a command to verify prettier is satisfied
- should generalize nicely to testing our backend code too

**Comment by dandelionmane** [comment]
cc @wchargin

**Comment by VictorBjelkholm** [comment]
We could put this on our jenkins instance that we're using for most Protocol Labs projects if you're interested?

**Comment by dandelionmane** [comment]
Thanks for the offer @VictorBjelkholm. My instinct right now is to use Travis - it's simpler, I'm more familiar with it, it's free, and I'm almost certain it will solve all our immediate needs. Happy to hear any arguments in favor of using jenkins, though.
