### ISSUE TITLE
UI Identities Page should have a search box

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#2352]
Currently the new username box / rename username box is at the top of the screen. It's really un-intuitive b.c. as a user searching for identities, i'd rather have a search. Having watched @panchomiguel use the UI for the first time, in many cases he put search strings in, which could have led to accidentally creating new identities or renaming them.

Creating a totally new identity from scratch doesn't happen very often, so make that a power user feature. Renaming is also kind of rare. It would be good to have a little edit button to put you into the rename flow. 

The search should be most prominent.

**Comment by KuraFire** [comment]
This is already being handled by https://github.com/sourcecred/sourcecred/issues/2490

**Comment by KuraFire** [comment]
(This is not to say that #2490 is the destined design for this search solution, but that it's wasted effort to implement that when the exact identical functionality is already being implemented under a different name, and the entire page is about to be redesigned.)

**Comment by BrianBelhumeur** [comment]
Issue #2490 is pretty much the same thing as this and has much more detail, so I'm closing this issue in favor of that one.
