### ISSUE TITLE
Discord plugin cannot load!

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#2353]
The Discord plugin is no longer working in prod. I believe it is due to this change:

https://discord.com/developers/docs/topics/gateway#privileged-intents

Hopefully we just need to change our bot permissions, not a change to code. In which case we should update our docs too.

**Comment by decentralion** [comment]
Looked into this with @hammadj and here's the solution:

Navigate to the discord developer portal, and then flip the "server members intent"
![image](https://user-images.githubusercontent.com/1400023/95505098-a5eab700-0962-11eb-8e0b-ae3b32b0e32d.png)

**Comment by topocount** [comment]
resolved with https://github.com/sourcecred/docs/pull/225
