### ISSUE TITLE
`yarn graph` gives opaque error when `ledger.json` is empty

### ISSUE THREAD

**Issue by BrianBelhumeur** [sourcecred/sourcecred#2460]
Currently, `yarn graph` requires an empty array in `ledger.json` when computing a new graph. Without this array, the following error occurs:
```
➜  template-instance git:(master) ✗ yarn graph
yarn run v1.22.5
$ dotenv sourcecred graph
  GO   graph
Error: line 1 is not valid JSON: SyntaxError: Unexpected end of JSON input
    at eval (webpack:///./src/util/jsonLog.js?:23:551)
    at Array.forEach (<anonymous>)
    at Function.fromString (webpack:///./src/util/jsonLog.js?:23:463)
    at Function.parse (webpack:///./src/core/ledger/ledger.js?:173:97)
    at loadLedger (webpack:///./src/cli/common.js?:40:618)
    at async graphCommand (webpack:///./src/cli/graph.js?:21:1158)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Since the error offers little in the way of debugability, I suggest one of two solutions when `yarn graph` is run and `ledger.json` is empty:
1. Default the contents to an empty array and continue
or
2. Throw an error that points to the need for an empty array

**Comment by topocount** [comment]
I've actually replicated this as a bug in a completely fresh template instance. Running `yarn go` without configuring any plugins completely wipes out the contents of the ledger.json file when `yarn graph` runs.

**Comment by BrianBelhumeur** [comment]
Ah ha, thats how I triggered it! I saw on my git diffs that the `[]` had been removed from `ledger.json` but not sure how. I did indeed run `yarn load` before configuring plugins. This seems like an additional place we could add some better error messaging (e.g. “warning: no plugins configured!”) as well as fixing the bug that removes the empty array from `ledger.json`

**Comment by topocount** [comment]
> This seems like an additional place we could add some better error messaging (e.g. “warning: no plugins configured!”) as well as fixing the bug that removes the empty array from `ledger.json`

haha I'm just seeing this @BrianBelhumeur. That's exactly what I did in #2485 and #2486.
