### ISSUE TITLE
[ExplorerHome] Use paginated CredGrainView

### ISSUE THREAD

**Issue by topocount** [sourcecred/sourcecred#2464]
## AC (Acceptance Criteria)
- ExplorerHome uses CredGrainView and NOT CredView
- ExplorerHome displays real cred data loaded from json
- CredGrainView is optional similar to CredView (I can load the admin view without a credGraph.json in my instance)
- TableState+MaterialUI pagination

## Not AC
- filtering/sorting

**Comment by BrianBelhumeur** [comment]
Taking with permission from @befitsandpiper

**Comment by BrianBelhumeur** [comment]
For clarity and to keep the PRs more atomic, I'm going to split this into two PRs.
