### ISSUE TITLE
Create a filtering interface for The Identities admin view

### ISSUE THREAD

**Issue by topocount** [sourcecred/sourcecred#2490]
Currently, there is no easy way to find identities you want to modify, except for scrolling. We need a filter box to make navigating this page simpler.

**Comment by KuraFire** [comment]
Here is some new UI for filtering the Identities list:
![Identity filtering - UI update](https://user-images.githubusercontent.com/33087/100940771-685f6180-34ad-11eb-92b7-5a663ee8324e.png)

This image shows what changes were made:
![Identity filtering - UI changes](https://user-images.githubusercontent.com/33087/100940800-76ad7d80-34ad-11eb-9a6f-ae290efebd1c.png)

Please note: the "(click one to update it)" inside the new `<h3>` element is inside a `<small>` tag, so it's:
```
<h3>Identities <small>(click one to update it)</small></h3>
```

## Behavior
The matching should be fuzzy for now, meaning `an` will match any identity name that contains both an `a` _and_ an `n` in that order, but not necessarily sequentially. So, it'll match `sandpiper` and `decentralion` but it will not match `Thena`.

Below is an animation for the filtering. If possible, please collapse elements that get filtered out using an `ease-in-out` transition over `300ms`:
![Identities table filtering](https://user-images.githubusercontent.com/33087/100940720-55e52800-34ad-11eb-95a0-d8601f3582af.gif)

**Comment by felixbbertrand** [comment]
This is basically a sorter using the name of the user?

**Comment by KuraFire** [comment]
> This is basically a sorter using the name of the user?

@felixbbertrand Not a sorter, but a filter, as non-matching entries must be excluded from the list.
