### ISSUE TITLE
New API: Cred & Grain for specific timeframes

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2492]
For the new Explorer Dashboard, the Cred and Grain columns in the Activity Table (See #2260 ) will show the counts for the selected time period in the Timeframe Control (see #2231 ).

This ticket requests the creation of a new API to expose the Cred and Grain values for specific time periods from the data.

**Comment by blueridger** [comment]
https://github.com/sourcecred/sourcecred/issues/2227

**Comment by blueridger** [comment]
![](https://cdn.discordapp.com/attachments/454007880111095808/775886014631116830/Explorer_Dashboard_-_MVP.png)

**Comment by blueridger** [comment]
Done https://github.com/sourcecred/sourcecred/commit/a55b5ee1a098f5407a98825875f26941f3e983f8
