### ISSUE TITLE
develop frontend testing practices

### ISSUE THREAD

**Issue by dandelionmane** [sourcecred/sourcecred#25]
It's tempting to charge ahead with the frontend and wait until after the UI is more established to begin testing it. However, based on past experience, it's easy to get to a state where the system is so complex that adding tests is a daunting undertaking. It will be much better to test as we go. 

I'd like to set up functional tests for the following behaviors:
- expand/collapse FileExplorer UI 
- change selected filepath in FileExplorer
  - .. and UserExplorer receives it
     - ... and UserExplorer displays new sums

I'm not sure what the best way to structure these tests. Should it be very tightly scoped unit tests of each individual primitive of the behavior, or should it be end-to-end, going straight from the user input on the FileExplorer to the updated sums in the UserExplorer? 

I think we can have both, in a fairly labor efficient way, if we mix unit testing and [snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html). For each individual component-specific interaction, we can test the logic via unit tests. For end-to-end integration, we can describe a sequence of user inputs and then take a snapshot in the terminal state. We should be able to write these easily and quickly, and maintain them without too much effort.

cc @wchargin

**Comment by wchargin** [comment]
> For each individual component-specific interaction, we can test the logic via unit tests

Certainly.

> For end-to-end integration, we can describe a sequence of user inputs and then take a snapshot in the terminal state

This suggests to me that

**Comment by wchargin** [comment]
:+1:

> For each individual component-specific interaction, we can test the logic via unit tests

Agreed. 

> For end-to-end integration, we can describe a sequence of user inputs and then take a snapshot in the terminal state

Perhaps. This suggests to me that the E2E test’s snapshot will change frequently: the test could be invalidated by style/copytext changes even at leaf nodes, changes to default sorting/allocation settings, etc. It would be unfortunate if this led to people (read: future-me) regenerating the snapshots blithely enough that actual regressions are not only unnoticed but promoted to the “correct” behavior. But I’m still willing to try it out!

I _do_ agree that we should have “E2E things-still-work” tests for each major feature. Such tests are probably easy enough to write without snapshot testing—DOM inspection is made pretty easy by helper functions like `findManyWithTag`, `findUniqueWithId`, etc. For instance, the test that you describe with “`UserExplorer` displays new sums” is easy to write in this way.

Heck, we could write both versions, and see which ones give better ROC curves. :-)

**Comment by wchargin** [comment]
Closed by #102.
