### ISSUE TITLE
[frontend] Make “Grain” label match configured name for Grain in an instance's Accounts view

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2501]
**Problem:** The configurable name for Grain does not get used everywhere; the word “Grain” is hardcoded.

**Expected result:** when you change the name of Grain for your instance, it should work everywhere.

**Actual result:** in the Cred explorer, Accounts page, the word “Grain” shows up no matter your configured name.

See on e.g. [SourceLove Cred Explorer](https://kurafire.github.io/sourcelove/#/accounts) or in the attached screenshot.

![sourcecred Grain bug](https://user-images.githubusercontent.com/33087/98863010-9b698480-241c-11eb-872d-ddbaf8ff856a.png)

**Comment by decentralion** [comment]
I'm pretty sure this was already fixed by https://github.com/sourcecred/sourcecred/pull/2428. Sorry @BrianBelhumeur for the misleading assignment!
