### ISSUE TITLE
Ambiguous error messaging: cred is zero

### ISSUE THREAD

**Issue by pablomendezroyo** [sourcecred/sourcecred#2582]
When using discord plugin, there may be users that have no interacted, so their cred will be 0.
After running `yarn load`, if you have an idedntity created with cred 0, `yarn grain` will return the error `Error: cred is zero`.

This is a critical issue since there is a high probability of having users with cred 0.

Possible **bug** detected at `processedIdentities()`, check it [here](https://github.com/sourcecred/sourcecred/blob/b7eca599d7f24e823336b962f8211faed42751d1/src/core/ledger/processedIdentities.js)

I have detected that there are contemplated 2 possibilities. `cred > 0` and `cred < 0 `. For `cred > 0`, Should be contemplated **`cred >= 0`** instead. 

![Screenshot from 2020-12-11 13-55-28](https://user-images.githubusercontent.com/41727368/101906488-53738400-3bb9-11eb-9f10-7bcca4e4532a.png)

**Comment by elihanover** [comment]
I haven't worked in the plugins, but given the local context and the documentation on the function, seems like a reasonable fix.  We should only be checking for > 0 across the total, not individual identities.

**Comment by elihanover** [comment]
@pablomendezroyo I'm not familiar with the plugin modules, but it appears here that it only needs one identity to have positive cred.  Note that it only checks `hasPositiveCred` after mapping over the identities (called `items` here).

**Comment by blueridger** [comment]
@elihanover is correct. That code only requires that at least 1 identity has cred. I see no bug. You need to run `yarn go` after `yarn load` and before `yarn grain`. A possible improvement here would be to improve the error message to "cred is zero. Remember to run 'yarn go' to calculate the cred scores."

**Comment by thr3m** [comment]
@blueridger Hi! Can you assign me this issue please :)
