### ISSUE TITLE
Experimental Discord: handle 429 errors in fetcher

### ISSUE THREAD

**Issue by topocount** [sourcecred/sourcecred#2601]
Discord seems to be throwing [unhandled](https://github.com/sourcecred/sourcecred/blob/6f6a28f27c020b2ea1445e98ee51625ca841e9f9/src%2Fplugins%2Fexperimental-discord%2Ffetcher.js#L63-L65) 429 errors, which means we might be missing out on chances to re-query otherwise accessible channel data. ~~Per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After), if these error responses contain a retry-after header we can `await` a cool down and then re-run the query once more, finally throwing if that one fails.~~

 Rather than waiting for the 429 responses, we should should key more proactively on the [rate limit headers](https://discord.com/developers/docs/topics/rate-limits).

**Comment by topocount** [comment]
An example error from a local `sourcecred load` on my system, using the sourcecred/cred repo:
![image](https://user-images.githubusercontent.com/17910833/102658308-f2a9f580-413c-11eb-9801-9cc5a550083f.png)
```
Error: not OK status 429 on https://discordapp.com/api/channels/454007907663740939/messages?after=482416921422200847&limit=100
    at failForNotOk (webpack:///./src/plugins/experimental-discord/fetcher.js?:6:4399)
    at Fetcher._fetchJson (webpack:///./src/plugins/experimental-discord/fetcher.js?:6:1727)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Fetcher.messages (webpack:///./src/plugins/experimental-discord/fetcher.js?:6:3007)
    at async Mirror.addMessages (webpack:///./src/plugins/experimental-discord/mirror.js?:9:88)
    at async Mirror.update (webpack:///./src/plugins/experimental-discord/mirror.js?:7:507)
    at async DiscordPlugin.load (webpack:///./src/plugins/experimental-discord/plugin.js?:19:1235)
    at async Promise.all (index 2)
```

**Comment by crisog** [comment]
I came up with a solution, probably not the most efficient though. It takes around 1hr 30m to load the current state of the 1Hive instance, it takes breaks when it's about to hit rate limits. @topocount 
Check the commit here: https://github.com/sourcecred/sourcecred/commit/81636cc2d1c72ef79cee9b95e8d6118cb7e6edfe

![image](https://user-images.githubusercontent.com/40803711/107245047-18e56680-6a05-11eb-9433-386b3dd73854.png)

**Comment by crisog** [comment]
However, the unit tests are failing due to Jest timeout before it finishes. I increased the timeout, but that doesn't seem to work.

**Comment by topocount** [comment]
> However, the unit tests are failing due to Jest timeout before it finishes. I increased the timeout, but that doesn't seem to work. 

@crisog thanks for jumping on this! We should be stubbing the request and mocking the 429 error and short-circuiting. The timeout. We can definitely test out this behavior with burning cpu cycles unnecessarily.

**Comment by blueridger** [comment]
Prevention really should be prioritized over handling, because I'm pretty sure hitting 429s reduces your token's reputation with Discord, causing stricter rate limits. (Learned this the hard way during bot development)

**Comment by topocount** [comment]
@crisog as per @blueridger 's suggestion and experience, we should key more proactively on the [rate lmit headers](https://discord.com/developers/docs/topics/rate-limits)

**Comment by crisog** [comment]
@blueridger thanks for the heads up, it makes sense. We've been hitting from the same token for months being rate-limited at 1Hive, so probably we are at the lowest level of reputation if that's the case.

@topocount  I think the proposed solution prevents them rather than handling them, given that once you first receive `X-RateLimit-Remaining: 0` you just gotta stop until it resets and you won't receive any 429 error. In my local tests, I never received a 429 loading the 1Hive instance.
