### ISSUE TITLE
Discord: Include messages from deleted authors in the graph

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#2629]
Currently, the Experimental Discord plugin [only adds messages to the graph if the author is a present member](https://github.com/sourcecred/sourcecred/blob/master/src/plugins/experimental-discord/createGraph.js#L315-L319) in the server. This is undesirable because someone deciding to leave the server would remove all props they gave from the graph, adversely affecting the cred scores of other people in the community.

Instead, we should include the message in the graph (and simply omit the author node/edge).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038637282737) by [Unito](https://www.unito.io/learn-more)

**Comment by saintmedusa** [comment]
broken link above; [target code](https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/plugins/discord/createGraph.js#L311)
