### ISSUE TITLE
Make the Transfer view mobile-friendly

### ISSUE THREAD

**Issue by topocount** [sourcecred/sourcecred#2646]
the transfer view works on desktop but doesn't fit into a portrait view or mobile view

**Comment by felixbbertrand** [comment]
Can you assign me this ? @topocount

**Comment by felixbbertrand** [comment]
@KuraFire

**Comment by KuraFire** [comment]
Thanks @felixbbertrand & @thr3m. I left my comments in the other PR:

https://github.com/sourcecred/sourcecred/pull/2699#issuecomment-767988087
