### ISSUE TITLE
CLI: Show list of grain recipients in console

### ISSUE THREAD

**Issue by topocount** [sourcecred/sourcecred#2647]
When the grain command is run, it prints out total grain distributed, but it'd be especially helpful for administrators to see who received what if it was printed in the console (and therefore visible in the autogenerate github PRs)

**Comment by decentralion** [comment]
@elihanover has done a bunch of work on this front, it didn't merge tho

**Comment by elihanover** [comment]
Will get this finished tomorrow or Wednesday
