### ISSUE TITLE
Add includeNsfwChannels flag to Discord plugin config

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#2676]
By default, NSFW channels should be ignored (ideally during load but at least during graph). As an instance maintainer, I should be able to override this by adding `"includeNsfwChannels": true` to my discord plugin config file.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038356656308) by [Unito](https://www.unito.io/learn-more)

**Comment by hozzjss** [comment]
I'll take this

**Comment by blueridger** [comment]
I thought I had groomed this task better...

# Tech notes
- This will definitely require manual testing, which means setting up a template-instance repo clone that uses discord, which means making your own test bot and adding it to our test server. You'll need help with at least part of this due to permissions.
- You will need to add the new field/default to the config type/parser here: https://github.com/sourcecred/sourcecred/blob/master/src/plugins/discord/config.js
- Then, update the fetcher to include the nsfw attribution provided by the API https://github.com/sourcecred/sourcecred/blob/5fa72e73507a0a7ebe3b3be7a3e8cea677727800/src/plugins/discord/fetcher.js#L124
- Then, you will need to populate the field [from the load method](https://github.com/sourcecred/sourcecred/blob/master/src/plugins/discord/plugin.js#L62) into the mirror constructor and then use it in [the addTextChannels method](https://github.com/sourcecred/sourcecred/blob/master/src/plugins/discord/mirror.js#L67) to filter out the channels if needed
