### ISSUE TITLE
[PersonalAttr] [Epic] Create a Basic Cred Tithing System

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#2677]
# Notes
As a contributor with an assistant contributor, I want to be able to tithe a percentage of my cred to my assistant every week.
As Protocol Labs, I want to collect a percentage of my employee's cred in exchange for their base sponsorship salary.

MVP is probably json config file in the config folder details the tithes that exist in an instance and are loaded when running credrank.

First create the config structure and get it approved by DL, then implement.

# Tech notes
Check out the mintBudget feature for inspiration https://github.com/sourcecred/sourcecred/blob/master/src/api/pluginBudgetConfig.js

More to be added...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038311790385) by [Unito](https://www.unito.io/learn-more)

**Comment by decentralion** [comment]
Looks good. From an implementation perspective, we'll want to create "tithe" edges that go from a tither's epoch nodes (i.e. their periodic Cred accumulator node) to the tithe recipient's epoch node. With a weight that's calibrated to be a fixed proportion of Beta (the proportion of the Cred flowing out from the epoch node that becomes that user's Cred).

Happy to discuss this in more depth with whoever is implementing this on the backend.

**Comment by elihanover** [comment]
This is a very exciting development.  This could be the foundation for a DisCo style interdependence "tax".  Let me know how I can help here, happy to do legwork.

**Comment by topocount** [comment]
@blueridger closing since it's completed
