### ISSUE TITLE
[UX] Improve Save Ledger interaction design

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2702]
The "Save Ledger to Disk" button in the SC explorer admin area (all pages) should start in a `:disabled` state, since there is nothing to save.

When the state of the ledger becomes **dirty** (= there are unsaved changes), two things should happen:

1. Remove the "Save Ledger" button's `:disabled` state once an action has been made (e.g. a Grain transfer has been submitted, an identity has been created);
1. A message above* the "Save Ledger" button in a bold white color, reading: "Changes not yet saved to ledger!"

Once the user Saves Ledger to disk, the button should return to its `:disabled` state until the state of the ledger becomes **dirty** again.

_Per @BrianBelhumeur's excellent suggestion:_
If the ledger state is **dirty** and the user navigates away from the page (or reloads),  use the `onbeforeunload` event to provide an alert reading the following:
> Changes not yet saved to ledger! Proceeding will discard your changes.

([MDN `onbeforeunload` page](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload))

\* Above or below. Unfortunately my local instance isn't working ATM, so I can't currently provide visual mockups for the exact placement of the warning labels and Save Ledger buttons across all of the screens. The label design-discussion is for me to work with someone to get my local instance running again.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038310139683) by [Unito](https://www.unito.io/learn-more)

**Comment by BrianBelhumeur** [comment]
We might also consider the `onbeforeunload` event in combination with or in lieu of the notice. It's the thing that pops up the alert box when you try to navigate way and lets you reconsider.
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by KuraFire** [comment]
Thanks @BrianBelhumeur — I included it in the spec.

**Comment by blueridger** [comment]
https://github.com/sourcecred/sourcecred/pull/2785
