### ISSUE TITLE
Github load error output as [object Object]

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#2734]
# Problem
[This line](https://github.com/sourcecred/sourcecred/blob/master/src/cli/load.js#L106) passes an error of type `any` to a function which expects a string. This works for some plugins, but not Github (probably depends on whether the plugin throws a string or an Error object).

# Solution
Check if `e` is an object, and if it is, send `JSON.stringify(e)` instead.
`message = typeof e === 'object' && e !== null ? JSON.stringify(e) : e`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038217385768) by [Unito](https://www.unito.io/learn-more)

**Comment by topocount** [comment]
the `.toString` method will yield effectively the same result. We probably want to use `[JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)` here
