### ISSUE TITLE
Merging active, existing Identities Breaks Ledger History distribution popover

### ISSUE THREAD

**Issue by topocount** [sourcecred/sourcecred#2753]
# Description
After merging myself and Beanow in the "Identities" View on SourceCred's production cred instance, I went back to the "Ledger History" view and received a React Admin Error when attempting to click into a distribution popover, I received this error:
![Screenshot from 2021-02-12 11-17-39](https://user-images.githubusercontent.com/17910833/107800183-1431f280-6d24-11eb-964c-31419087b460.png)

I initially believed this is a symptom of a larger problem involving ledger consistency across all components, but I've found that saving the ledger to disk and reloading the page does not fix this issue, so it's an issue with the ledger not providing this account after it's been merged, or more correctly, not omitting this account from the popover table at all and foregoing this query.

# Detailed Replication Steps
1. In the `sourcecred/sourcecred` repo, run `git checkout master && yarn && yarn start`
2. navigate to the identites view ([http://localhost:8080/#/admin](http://localhost:8080/#/admin)) and merge "dandelion" into "william":
![Peek 2021-02-12 11-32](https://user-images.githubusercontent.com/17910833/107801745-1ac16980-6d26-11eb-81f5-06211601021e.gif)
3. navigate to the "Ledger History" View and click on a distribution pill: 
![Peek 2021-02-12 11-35](https://user-images.githubusercontent.com/17910833/107802070-80adf100-6d26-11eb-888c-365eee962e8c.gif)

**Comment by blueridger** [comment]
related to https://github.com/sourcecred/sourcecred/issues/2719

**Comment by blueridger** [comment]
My recommended solution is to simply change [this line](https://github.com/sourcecred/sourcecred/blob/e31c083b78fe93b31901b833cd5fb55b704cc9c7/src/core/ledger/ledger.js#L350) to
```
this._accounts.set(targetIdentity.id, baseAccount);
```
Double-check to make sure there aren't unintended side effects, but I'm pretty sure this would be the ideal fix.

**Comment by topocount** [comment]
> My recommended solution is to simply change [this line](https://github.com/sourcecred/sourcecred/blob/e31c083b78fe93b31901b833cd5fb55b704cc9c7/src/core/ledger/ledger.js#L350) to
> 
> ```
> this._accounts.set(targetIdentity.id, baseAccount);
> ```

@blueridger With this change, target accounts are left dangling when the base account later becomes the target in another merge. I'm looking into adding an index that tracks this stuff, but I don't see any clear implementation paths just yet.
