### ISSUE TITLE
Grain distribution quantity input should be string that allows a decimal point

### ISSUE THREAD

**Issue by befitsandpiper** [sourcecred/sourcecred#2779]
# User Story
As an instance maintainer in a community with a very expensive token and a small instance budget, I want to be able to distribute a fraction of a token so that I can distribute smaller/more precise amounts than increments of a single token.

Example: In 1hive, the $HNY token price is ~900 USD, so it is impossible to distribution $500 per week, since the minimum allowed is 1 grain = 1 $HNY = $900.

# Tech Notes
Some files of interest:
https://github.com/sourcecred/sourcecred/blob/master/src/api/grainConfig.js
https://github.com/sourcecred/sourcecred/tree/master/src/core/ledger/policies
https://github.com/sourcecred/sourcecred/blob/master/src/core/ledger/grain.js

The allocation configs currently parse a json number and validate that it is an integer. This should be changed to a `string` representation of a number that may have a decimal point and that is [parseable to `Grain`](https://github.com/sourcecred/sourcecred/blob/master/src/core/ledger/grain.js#L233).

# Alternatives considered
An alternative solution would be to make your instance's grain not 1:1 with the token, for example 10 grain could be equal to 1 $HNY. This is difficult to enact retroactively though, because it would mean re-writing the entire ledger to create a consistent grain evaluation. And also, this is difficult because it adds a new currency value / conversion, which would probably mean more confusion and cognitive load for the entire community.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038210995889) by [Unito](https://www.unito.io/learn-more)

**Comment by topocount** [comment]
@befitsandpiper can you lay out this user story a bit more? I think this just might be an issue of configuration.

Floats should not be used with cryptocurrencies because they are non-deterministic. Grain in sourceCred is typed as a BigInt but by default the first 18 of those digits are reserved as decimals by default: https://github.com/sourcecred/sourcecred/blob/aa1a46943d83da3f61bbfae797021976e08d1240/src/core/ledger/grain.js#L46-L50

Likewise, ERC20 tokens in Ethereum are similar, in that they are typed as uint256 (256 bits, or 32 bytes, are reserved for the value), but the first 18 digits are typically reserved for decimals.

**Comment by blueridger** [comment]
We should be able to take a float in the configuration and immediately convert it to a grain string without risk of non-deterministic behavior.

**Comment by wchargin** [comment]
Floats aren’t “nondeterministic”, and neither are the common arithmetic
algorithms that operate on them (e.g., addition), but those algorithms
do lack the properties necessary to make them suitable for anything
touching grain.

It is harder than you might think to “take a float” and losslessly
convert it to a grain string. What does the float `0.1` represent, and
do 10 of them represent `1.0`? There is a reason that Java’s
[`BigDecimal(double)`] constructor is almost never what you want.

[`BigDecimal(double)`]: https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#BigDecimal(double)

One possible approach may be to take a *string* possibly containing a
decimal point and parse that to an exact grain value with at most
18 decimal digits of precision. This is fine, but that is *not* the same
as taking floats as input, and we should not confuse it as such. As soon
as your data’s in floats, you have already lost. But +1 to @topocount’s
request for more context and motivation, please.

**Comment by befitsandpiper** [comment]
The configuration only allows distribution quantities to be integers. I'm just asking that we allow floats for distribution quantities. This is unrelated to decimal precision, the precision is still 18 decimals for the token. Yes it is fine if this is in the form of a string rather than an actual float. It doesn't have to be an actual float, just something that intuitively behaves how you would expect when you say you are distributing say 1.2 grain or 0.67 grain, etc up to DECIMAL_PRECISION numbers after the decimal point.
