### ISSUE TITLE
Fix interval data that is being passed into ExplorerTimeline

### ISSUE THREAD

**Issue by magwalk** [sourcecred/sourcecred#2788]
The CredTimeline/ExplorerTimeline had a visual bug where the line wasn't taking up the full x-axis, and wasn't displaying at all on the Last/This Week tabs. This is because the timeline displays a line graph for cred and grain, where each point on the graph signifies one interval of time.  Since our time intervals are set in weeks, the "last week" and "this week" views of the graph only displayed one point and therefore didn't draw a line (you need at least two points to draw a line).

The "this month" and "all time" line should also take up the full width of the graph. 

Currently there is a quick fix that duplicates the last value of the array, but ideally we should modify the values that are getting passed in so at least two values are always passed into ExplorerTimeline, ensuring that a line is drawn. Look for the comments in ExplorerTimeline that talk about the quick fix and you'll find the code that extends each array by one value.

This work will likely require looking at TIMEFRAME_OPTIONS and modifying the selector values. 

**The different tab views should be as follows:**
_"This Week" view:_ A line with two points, the first point being last week's value and the second point being this week's value (to demonstrate the change from last week to this week)
_"Last Week" view:_ A line with two points, the first point being the week before last week's value and the second point being last week's value (to demonstrate the change from the previous week to last week)
_"This Month" view:_ A line with four points, each point being each of the weeks in that month
_"All time" view:_ A line with x points, however many intervals there have been over the course of time that the instance has existed

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038299119564) by [Unito](https://www.unito.io/learn-more)

**Comment by blueridger** [comment]
partial fix: https://github.com/sourcecred/sourcecred/pull/2804
