### ISSUE TITLE
Implement versioning for all serializables

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#280]
Currently, SourceCred has no consistent way to approach versioning. This hasn't been a problem thus far as we have no users, and it's reasonable to regenerate all graphs from scratch every session. Once we start persisting graphs (/ have users), we will need versioning and approach for backcompat on old data structures.

We should implement a consistent versioning system. Ideally it will have at least the following two properties:
- Allow fine-grained versioning of composite objects, e.g. at present a Graph serializes using Address Maps, and the address maps should be independently versionable (h/t @wchargin )
- Allow plugins to have separate data versioning, e.g. the GitHub plugin can change its graph representation without this leaking over to other plugins

**Comment by Beanow** [comment]
Nowadays we use `Compatible<T>` for this.

https://github.com/sourcecred/sourcecred/blob/f260569605f2c97f52cafd226b172070de3fb351/src/util/compat.js#L3
