### ISSUE TITLE
can't define array index property past the end of an array with non-writable length

### ISSUE THREAD

**Issue by vanmoortel** [sourcecred/sourcecred#2854]
**Describe the bug**
An issue with SourceCred website, can't access the explorer section.
I'm only using the Discord plugin yet.
Everything works fine with 0.7.7 but doesn't work with 0.8.0

Console output
`TypeError: can't define array index property past the end of an array with non-writable length
    Xg ExplorerTimeline.js:43
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
react-dom.production.min.js:209:194
    React 5
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
`

**Steps to reproduce**
What sequence of actions results in this error?  e.g.:

1. yarn load
1. yarn start
1. Go to http://localhost:6006/#/explorer-home
1. See an error

**Expected behavior**
Display explorer.

**Screenshots**
![image](https://user-images.githubusercontent.com/54771141/111456574-744af880-8717-11eb-9a31-cc16655e9f05.png)

**Technical Details:**
These are important!

* OS & version: Pop!_OS 20.10
* Browser & version: Firefox 86.0
* Link to your SourceCred Instance: No published yet

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200073887798318) by [Unito](https://www.unito.io/learn-more)

**Comment by blueridger** [comment]
fix: https://github.com/sourcecred/sourcecred/pull/2861
