### ISSUE TITLE
Update design of Ledger EVENT types in UI 

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2870]
### Status quo
❌  : Ledger action colors are as prominent as the details.
❌  : Ledger actions are in ALL CAPS because of API output.

### New world
✅  : Ledger action colors are set to `#CBDFFF`
✅  : Ledger actions to be human-first, and read as follows:

 - Create Identity
 - Rename Identity
 - Add Alias
 - Merge Identities
 - Toggle Activation
 - Distribute Grain
 - Transfer Grain
 - Change Identity Type
 - Set Payout Address

I'm gonna guess this would be a Good First Issue™ but YMMV.

**Comment by blueridger** [comment]
Starting place: 
https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/ui/components/LedgerViewer/LedgerViewer.js
