### ISSUE TITLE
UI: Add Date filtering to LedgerView

### ISSUE THREAD

**Issue by KuraFire** [sourcecred/sourcecred#2878]
This ticket is quite similar to #2630, but covers filtering for Dates (via a range) in the Ledger instead of filtering by Events.

## Design Spec
Here is an updated interface & specifications for updates to the Ledger page:

![Ledger - new default](https://user-images.githubusercontent.com/33087/112197658-8c17f600-8bc9-11eb-991a-39d75313da66.png)

## Context Matters (Disclaimer)
The screenshot above shows changes which will be represented in at least three different tickets. This ticket only addresses Date filtering.

- #2870 addresses the changes in color and capitalization of the Event Types in the left column.
- #2630 covers filtering by Event types in the Ledger

There are two new filtering types being introduced to the Ledger: Filter Events, and Filter Date (select a range). Here is a close-up view:
![Ledger - new filters row](https://user-images.githubusercontent.com/33087/112198842-c3d36d80-8bca-11eb-8285-bc55126557c7.png)

## Filter by Date range: UI spec
- The two date pickers for this filter use the [standard Material UI date picker component](https://material-ui.com/components/pickers/#material-ui-pickers), and **not** the native date picker. _(Chrome made a **much** less accessible native picker that's awful to use.)_
- For mobile, let's test Material UI's default handling of this before exploring specifics. This can be a separate ticket in the future.

![Ledger - date picker](https://user-images.githubusercontent.com/33087/112199513-7a375280-8bcb-11eb-921e-1ca2edd484ce.png)

## Filter by Date range: Interaction Design spec
The filter works reductively:

- By default (initial page load), no dates are selected
- Selecting a Start Date (but no end date) filters as expected: from selected Start Date to Today
- Selecting an End Date (but no start date) filters as expected: from start of project to selected End Date
- Selected both Start _and_ End Date filters as expected: within that range, inclusively (i.e. both selected dates are included in the range)

Resetting the field once a Date is selected (either/both):
- a small "Clear ×" link-style `<button>` is added above the right edge of the date input field;
- activating this button sets the value back to `null` to clear the field, and updates the filtering of the ledger table accordingly;
- Clearing the field should **not** return the focus on the date input field

![ledger date - clear](https://user-images.githubusercontent.com/33087/112541689-ea330d80-8d70-11eb-8110-32a9d08c85d2.png) ![ledger date - clear hover](https://user-images.githubusercontent.com/33087/112541690-eacba400-8d70-11eb-83b9-9d9773fbf742.png)

The "(Start •• End) Date" label works as a standard MUI floating label pattern, meaning it transitions into small text above the field upon focus.

## Filter control states & colors
The "Filter Date" label should be:

- In default state: `rgba(215, 226, 243, 0.7)` (or `#CBDFFF` at 70% opacity)
- In `:hover` state: `#CBDFFF`
- In `:focus` state: `#31AAEE`

The "Clear ×" text link-style `<button>` should be:

- In default state: `rgba(215, 226, 243, 0.5)` (or `#CBDFFF` at 50% opacity)
- In `:hover` + `:focus` + `:active` state: `#FF594D`

**Comment by blueridger** [comment]
Assigning to mahmoud

**Comment by blueridger** [comment]
Use the TableState to add a filtering function.

**Comment by blueridger** [comment]
Here's the file to get you started:
https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/ui/components/LedgerViewer/LedgerViewer.js
