### ISSUE TITLE
Support metadata in discord JSON

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#3029]
From @panchomiguel 
> Is it possible to allow a text descriptor of the string-of-numbers identifying the Discord Channels' weights?
> As it stands, it is impossible to know the weights of separate channels by looking at this config file without having a separate reference list.
> In the attached image, being able to write "Announcements -"638464252847587328"" instead of just "638464252847587328" would be make it more user friendly to to set custom weights in the future

A few decent solutions I see:
- support // comments across all JSON by creating a comment removal util that gets run after loading JSON files an before running JSON.parse
- Change config strategy to use JS files instead of JSON files
- Allow a delimiter in configs like ':' in which we remove the piece of the key before the delimiter, or something of that nature.

This probably something that should be discussed with @wchargin and @decentralion

**Comment by blueridger** [comment]
https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/plugins/discord/config.js

https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/plugins/discord/plugin.js#L37

Though I might just suggest actually not doing this in discord, and instead intercept an clean the file text in this module:
https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/util/storage.js

**Comment by hozzjss** [comment]
I'm for the third solution as it can be backwards compatible something like
```js
const [channel_id, /* ignored field */ ] = channelKey.split(":")
```

I'm still not convinced of adding // in JSON files because it's against standard and parsing would not work in editors

This also could be cleaned in here https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/plugins/discord/plugin.js#L37

**Comment by blueridger** [comment]
Example config file that is not very human readable: https://github.com/sourcecred/cred/blob/main/config/plugins/sourcecred/discord/config.json

**Comment by blueridger** [comment]
I agree that we should not make our json unparseable by json parsers.

It would be pretty easy to add delimiter support by simply stripping the delimiter and what comes after it using a .map()  here:
https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/plugins/discord/config.js#L133

Since ':' already has a different semantic meaning for custom emojis, I would actually recommend that we use a different delimiter for these throw-away comments.

Maybe '-' if we want something basic, however...
I think it would be fun to use '//' since it is semantically recognized as non-functional commenting, and if we support it inside of key strings we wouldn't be breaking json rules.
