### ISSUE TITLE
[Write Instance] Create WriteableOriginStorage

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#3037]
Add a WriteableOriginStorage that implements WriteableDataStorage to https://github.com/sourcecred/sourcecred/blob/master/src/core/storage/originStorage.js
by copying the POST logic from https://github.com/sourcecred/sourcecred/blob/master/src/ui/utils/ledgerDiskStorage.js

**Comment by hozzjss** [comment]
I worked on this branch https://github.com/sourcecred/sourcecred/tree/hz/Create-WriteableOriginStorage-%233037
