### ISSUE TITLE
Discord: don't load 0-weighted channels

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#3119]
- discord/plugin.js
  - Pipe the channelWeightsConfig attribute into either the mirror constructor or mirror.update during `load`
- discord/mirror.js
  - in `addTextChannels`, use the channelWeightsConfig to omit channels the a weight of 0 (explicit or default weight)

**Comment by Amirjab21** [comment]
Hi,

I have completed the work for this but I do not have access to push to the repo.

**Comment by Amirjab21** [comment]
I can do this issue but could I have access to push to a new branch?
