### ISSUE TITLE
As an instance maintainer, I can configure discord channels by category instead of just by single channel. 

### ISSUE THREAD

**Issue by magwalk** [sourcecred/sourcecred#3188]
Per this discussion: https://discord.com/channels/453243919774253079/718263631158050896/888764649770741770

This would allow users to set their discord configuration to go by channel category (GUILD_CATEGORY) instead of just by channel name (GUILD_TEXT). For instances that have a very high number of channels, this would make setup a lot easier so they don't have to have every single channel signified in the config.

**Comment by thohoh** [comment]
In one of our chat categories we have dynamic channels being added to /moved to archive category. Yet being able to track those channels for contribution is also important. If, by specifying just channels category I can make sure all the new channels will be scanned for contributions - that would be awesome.
