### ISSUE TITLE
Grain Accounts Page: add pagination and search-by-name to speed the page up

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#3257]
File to change: https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/ui/components/AccountOverview.js

You can see an example of how to add pagination and search in the [ExplorerHome code](https://github.com/sourcecred/sourcecred/blob/main/packages/sourcecred/src/ui/components/ExplorerHome/ExplorerHome.js). Also see if you can fix any possible React leaks, as the page is really slow.

**Comment by amrro** [comment]
Related: #3224 #3225
