### ISSUE TITLE
Library bug: Uncaught ReferenceError: Cannot access...

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#3311]
# Summary
Running build succeeds but the resulting distribution files (packages/sourcecred/dist) cannot be successfully imported. I've narrowed down https://github.com/sourcecred/sourcecred/commit/8b9871100d6dd3d2ff2c3a8ed2228bfe8c5a4a21 as the commit that introduced the problem.

# Error message: 
```
Uncaught ReferenceError: Cannot access 'Jp' before initialization
    at Module.<anonymous> (/Users/thena/workspace/sourcecred/packages/sourcecred/dist/server/api.js:48:246675)
    at r (/Users/thena/workspace/sourcecred/packages/sourcecred/dist/server/api.js:1:128)
    at exports.sourcecred (/Users/thena/workspace/sourcecred/packages/sourcecred/dist/server/api.js:1:927)
```

# Steps to reproduce
1. checkout 8b9871100d6dd3d2ff2c3a8ed2228bfe8c5a4a21 or any commit after it.
2. yarn build
3. `yarn shell` OR `node` and then `require("./dist/server/api.js")`

**Comment by amrro** [comment]
For the bug, initial results suggest that the issue could be in a circular dependencies in `commonjs` module type 
I found a tool that can statically analyze the imports of the project's files
```npx madge --circular . ```

and this what I found
19 circular dependencies!
```
1) packages/sourcecred/src/core/credequate/config.js > packages/sourcecred/src/core/credequate/contribution.js > packages/sourcecred/src/core/credequate/operator.js
2) packages/sourcecred/src/core/credequate/config.js > packages/sourcecred/src/core/credequate/contribution.js > packages/sourcecred/src/core/credequate/operator.js > packages/sourcecred/src/core/credequate/scoredContribution.js
3) packages/sourcecred/src/core/credequate/contribution.js > packages/sourcecred/src/core/credequate/operator.js > packages/sourcecred/src/core/credequate/scoredContribution.js
4) packages/sourcecred/src/core/credequate/operator.js > packages/sourcecred/src/core/credequate/scoredContribution.js
```
