### ISSUE TITLE
How to export cred calculation to json or other readable format

### ISSUE THREAD

**Issue by sudoFerraz** [sourcecred/sourcecred#3375]
Hello,

Having a hard time trying to import sourcecred as a package in another project to calculate cred scores of participants programmatically, additionally I've also tried to export the data from a running instance of sourcred, but the generated files on the /output folder are binary. 

How can I read the cred scores of participants? Using the sourcecred API from this observable seem to not work anymore as well; (https://observablehq.com/@sourcecred/api-tutorial)

Ideal solution would be to fetch (load) cred scores through the package API, and not have it download an already calculated score from an instance that uploaded it in github (e.g. Doing the full cycle of configuring, loading the data from a github plugin configuration, and calculate the cred scores programmatically on another application) -> Exporting an already calculated instance to CSV is not a viable option

cc @decentralion 

Thanks

**Comment by alalonde** [comment]
Hi there, 

Here is an example of [how we do it in Metagame](https://github.com/MetaFam/TheGame/blob/develop/packages/backend/src/handlers/actions/sourcecred/sync.ts). Basically, you first load the ledger into memory, and then you can pull whatever data you need.

As for the observable being out of date, are you seeing API mismatches? What exactly doesn't work?  Are you using the [new CredEquate or old CredRank](https://sourcecred.io/docs/guides/core-algorithm/) algorithm?  I don't think there are many examples using the former.

**Comment by sudoFerraz** [comment]
Hey @alalonde,

Thank you for your answer, I took a look around the codebase and that really helps a lot.

I saw that you are loading the ledger from the sourceCred instance `XP` through this GithubProvider: 
![image](https://github.com/sourcecred/sourcecred/assets/6979719/b36c9266-2100-4430-82d9-fe2999914089)

This is already very useful and I could use it with some workarounds! 

For my use case, ideally, what I am looking for is to actually calculate the ledger programmatically without having to fetch it from an instance that has already calculated it (e.g. what are the objects sourcecred exposes that I could use to calculate the ledger on runtime by passing a github repo and a github token).

To contextualize, I'm trying to create on-demand instances of sourcecred with a frontend that anyone could use through a web application, simply by registering with their GH and choosing a repo to see results of their contributions;

Again, thanks for pointing that out and any information is appreciated! 🙏 👍

**Comment by alalonde** [comment]
> This is already very useful and I could use it with some workarounds!

Great!

> For my use case, ideally, what I am looking for is to actually calculate the ledger programmatically without having to fetch it from an instance that has already calculated it (e.g. what are the objects sourcecred exposes that I could use to calculate the ledger on runtime by passing a github repo and a github token).

I am confident you could do this with the existing "API", unfortunately I don't think there is any API documentation per se. However we used a tool to generate typescript [typings](https://github.com/MetaFam/TheGame/blob/develop/packages/%40types/sourcecred/index.d.ts) that could help. Hopefully that is useful!
