### ISSUE TITLE
Investigate moving to TypeScript

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#421]
Factors to consider:

  - time/effort spent integrating TypeScript into the build system
  - time/effort spent porting the existing Flow types to TypeScript (can
    this be done incrementally?)
  - time/effort saved by better type information due to TypeScript
  - time/effort wasted by worse type information due to TypeScript
  - time/effort saved or wasted by build- and run-time [performance
    differences][bernhardt]
  - relative cost of switching now versus later

[bernhardt]: https://threadreaderapp.com/thread/1007690864909529088.html

**Comment by wchargin** [comment]
An initial technical assessment of “which type system is better for us”,
disregarding any costs of integration, performance, etc.…

The TypeScript playground is at: http://www.typescriptlang.org/play/

Summary
=======

Roughly equivalent:
  - discriminated unions
  - exact and read-only objects
  - object and array type destruction
  - opaque types (via a workaround)
  - upward propagation of constraints

TypeScript better than Flow:
  - checked downcasts

TypeScript worse than Flow:
  - nominal types
  - read-only arrays?
  - variance (unquestionably, fundamentally broken)

Notes:
  - functions are bivariant by default (!!!), but this can be turned off
  - first-class `enum`s have nontrivial runtime elision

Roughly equivalent
==================

Discriminated unions
--------------------

These work exactly as in Flow, as far as I can tell.

Exact and read-only objects
---------------------------

Object types are exact by default. Attributes can be marked `readonly`:

```typescript
type O = { readonly x: number };
const tooMany: O = { x: 1, y: 2 };  // error
const okay: O = { x: 1 };
okay.x++;  // error
```

Object and array type destruction
---------------------------------

Works, with specialized (and cleaner) syntax. For objects:

```typescript
type O = { x: number };
function takesNumber(n: O["x"]) {
    console.log(n.toFixed(3));
}
takesNumber(3.14159265358979);  // okay
takesNumber("three");  // error
```

For arrays:

```typescript
type O = number[];
function takesNumber(n: O[number]) {
    console.log(n.toFixed(3));
}
takesNumber(3.14159265358979);  // okay
takesNumber("three");  // error
```

Opaque types
------------

Not supported directly. The following should be a workaround:

```typescript
declare const NodeAddressIdentity: unique symbol;
export type NodeAddress = typeof NodeAddressIdentity & string;
function nodeAddress(value: string): NodeAddress {
  return value as any;
}
```

This is because TypeScript knows about symbols and supports generative
“unique types” for them.

[opaque-1]: https://github.com/Microsoft/TypeScript/issues/202#issuecomment-381437628
[opaque-2]: https://github.com/Microsoft/TypeScript/issues/202#issuecomment-381603738

Upward propagation of constraints
---------------------------------

Not supported (as with Flow):

```typescript
type Foo = { type: "FOO", address: { type: "FOO" }, foo: string };
type Bar = { type: "BAR", address: { type: "BAR" }, bar: string };
type FooBar = Foo | Bar;
function onType(x: FooBar): string {
    return x.type === "FOO" ? x.foo : x.bar;  // works
}
function onAddressType(x: FooBar): string {
    return x.address.type === "FOO" ? x.foo : x.bar;  // error
}
```

TypeScript better than Flow
===========================

Checked downcasts
-----------------

Supported via `as`:

```typescript
const x: number = 3;
const a: 3 = x;  // fails, as expected
const b: 3 = x as 3;  // works!
const c: string = a as string;  // fails! 'number' not subtype of 'string'
```

TypeScript worse than Flow
==========================

Nominal types
-------------

Explicitly opaque types are not supported, and furthermore classes are
treated as structural:

```typescript
class FileSystem {
    close(fd: number): boolean {
        console.log("Closing file...");
        return true;  // success!
    }
}

class ApproximateNumber {
    close(x: number): boolean {
        const closeEnough = Math.abs(x) < 1e-6;
        return closeEnough;
    }
}

function closeStdout(fs: FileSystem) {
    fs.close(1);
}

declare const z: ApproximateNumber;
closeStdout(z);  // no error! bad! :o
```

Read-only arrays
----------------

There’s a generic `Readonly` type, but it doesn’t seem to be very
useful:

```typescript
declare let x: Readonly<number>;
x++;  // no error!

declare const xs: Readonly<number[]>;
xs[0] = 3;  // error
xs.push(3);  // no error!
xs.reverse();  // no error!
```

Variance
--------

Variance annotations not supported. Apparently, all generic types are
treated as bivariant, which is completely broken:

```typescript
declare class Container<T> {
    put(t: T): void;
    getAll(): T[];
};

class Animal {
    speak() {
        console.log("hello");
    }
}
class Dog extends Animal {
    speak() {
        console.log("woof");
    }
    shout() {
        console.log("arf arf arf");
    }
}

declare function f(x: Container<Animal>): void;

declare const animals: Container<Animal>;
declare const dogs: Container<Dog>;
declare const strings: Container<string>;

f(animals);  // works (good)
f(dogs);     // works!!! :o (very bad)
f(strings);  // fails (good)
```

**Comment by wchargin** [comment]
Honestly, the bivariant generics are pretty much enough to convince me
that the type system is strictly worse. The lack of read-only arrays
could be a problem, too.

**Comment by decentralion** [comment]
Cool, my prior was that we should only invest the effort switching from Flow to TypeScript if we would see really big benefits in the quality of the typesystem. Your preliminary analysis is conclusive that that won't be the case, so let's close out this investigation. Thanks for digging into it!
