### ISSUE TITLE
Switch Explorer repository input to a list rather than text entry

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#498]
Right now, users of the cred explorer manually specify a repository name / owner via text inputs. In practice, there are only a few valid options, based on what data is available on the backend. We should modify the UI so that it offers only valid options. (If no options are present, it should probably offer help text on how to load data.)

This will make the UI more convenient to use, and will likely take less space.

**Comment by wchargin** [comment]
In the long run, I’d like to keep the power user in mind. Lists are
sometimes much less convenient than text entry fields when you already
know what you want to enter. Something like a fuzzy-finder might get the
best of all worlds.

**Comment by decentralion** [comment]
In the long run, we're ~~all dead[1]~~ gonna completely regenerate the UI

[1]: https://en.wikiquote.org/wiki/John_Maynard_Keynes

In the medium term, I think it's likely that individual projects will host their own cred explorers on their own domain (possibly GitHub pages). This way the data can all be available and relatively fresh, all of the right plugins are already loaded, etc. I expect most end users will access SourceCred via those hosted explorers. Then, there won't be a case where power users are rapidly putting lots of different repos into the cred explorer UI, since it's already scoped to a particular project/organization.

**Comment by wchargin** [comment]
Agreed. A list is probably fine with me for now.

**Comment by wchargin** [comment]
Closed by #529.
