### ISSUE TITLE
Create a static SourceCred demo

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#499]
Now that we have an interesting prototype to play with, I'd like us to have an online demo that statically serves graphs/data for a fixed set of chosen repositories. We can use GitHub pages for hosting, and then make it publicly available on sourcecred.io. We can then link to it in the README, etc. This will make SourceCred's progress a lot more tangible and easy to communicate. We should handle #498 first so that users don't need to guess which options are valid. 

Implementation wise, since the backend right now only serves static JSON, it shouldn't require much modification of our code. We should build good infrastructure for setting up and updating the demo instance, as it is likely that this pipeline will be a good fit for other projects that want to easily setup their own SourceCred instance using GitHub pages.

**Comment by wchargin** [comment]
> it shouldn't require much modification of our code

Yes, but I would like to do some performance analysis before we set up
anything hosted. I suspect that we can go a fair bit faster than we do
now, in terms of both raw speed and perceived speed.

> We should build good infrastructure for setting up and updating the
> demo instance, as it is likely that this pipeline will be a good fit
> for other projects that want to easily setup their own SourceCred
> instance using GitHub pages.

Good point. Agreed.

**Comment by decentralion** [comment]
Summarizing an offline discussion:
- We agree that setting this up should not be hard, and that we would like to do this soon.
- We'll host it on GitHub pages, and can use [travis to deploy]. 
- We'll make it publicly available from sourcecred.io, maybe sourcecred.io/prototype
- We'll automatically update it every day, both so that new contributors can quickly get visible cred, and so that we can spot breakages early. 
- we could use GitHub webhooks to try to update it more frequently, but think this is unnecessary right now

[travis to deploy]: https://docs.travis-ci.com/user/deployment/pages/

paired with @wchargin

**Comment by decentralion** [comment]
Fixed, with thanks to @wchargin!

https://sourcecred.github.io/explorer/
