### ISSUE TITLE
Investigate React UI component libraries

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#561]
Based on @claireandcode's work in #549 and #552, we think we want to import a React UI component library as it can make it easier to create a pretty, accessible, and consistent UI. Those PRs use semantic-ui-react and semantic-ui-css.

However, @wchargin did some digging into those dependencies and had [some reservations], as they would significantly inflate our build.  Given that there are [many React UI toolkit options], I think it would be good to investigate a few for project fit before deciding which one to commit to.

[some reservations]: https://github.com/sourcecred/sourcecred/pull/552#issuecomment-408638061
[many React UI toolkit options]: https://hackernoon.com/23-best-react-ui-component-libraries-and-frameworks-250a81b2ac42

We can use this issue to collect notes on different options we explore.

**Comment by decentralion** [comment]
I spent some time investigating Blueprint ([site], [GitHub]) and experimentally integrating it ([commit]). Here are some thoughts and impressions:

[site]: http://blueprintjs.com/
[GitHub]: https://github.com/palantir/blueprint
[commit]: https://github.com/sourcecred/sourcecred/commit/f169e2a5de5f95899fd4068e277da65565b98f76

- Blueprint "is optimized for building complex data-dense interfaces for desktop applications", which sounds nice
- It seems relatively low on configurability - e.g. it doesn't support custom color themes. It seems to be UI toolkit for Palantir and Palantir's aesthetic first and foremost, which also happens to be open source
- It adds 200KB (tripling size of the build)  and 5s to build time (15 vs 20)
- It doesn't boast much mobile support
- It does some weird things like restyle all of our links by default
- The UI seems to have some weird bugs / unpolished edge cases (e.g. sliders always expand from 0 outward, rather than left to right, which looks weird on our sliders that start at -10; except if they are at the default  value, in which case they expand from left to right,  even if the default value is 0).

Overall, I do not think we should use this library. I'll note that [blueprintjs/select] is an interesting and powerful component that can be depended on separately and might be worth including in the future.

[blueprintjs/select]: http://blueprintjs.com/docs/#select

![image](https://user-images.githubusercontent.com/1400023/43420116-b9dfcf26-93f7-11e8-8f46-c94b4ed2a2fe.png)

**Comment by befitsandpiper** [comment]
Is it fair to close this?
