### ISSUE TITLE
Separate Weight Sliders by Plugin, better namespacing

### ISSUE THREAD

**Issue by claireandcode** [sourcecred/sourcecred#595]
As the project evolves, it is likely that the number of plugins will increase.
Similarly, a user may wish to weight different plugins relative to each other, e.g. all "git" nodes are weighted less heavily than all "github" nodes. 
To start building the infrastructure to facilitate those changes, we want to separate the weight sliders by plugin, and also take advantage of the namespacing in the plugin adapter to provide better labelling, and thus a friendlier UI.

Credit to @decentralion and @wchargin for architectural planning discussions.

**Comment by decentralion** [comment]
FYI, I'm making some changes related to #465 which should simplify how the plugin-level weights will work. Please hold off on implementing this until my changes land

**Comment by decentralion** [comment]
Nevermind, I didn't make any relevant changes.

**Comment by decentralion** [comment]
Closed by #773.
