### ISSUE TITLE
Consider making the synthetic self loop an edge

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#606]
Right now, we have three kinds of contributiors: (contribution in the graphToMarkovChain.js meaning, i.e. contributors to a PageRank score, not contributors to a project).
```
export type Contributor =
  | {|+type: "SYNTHETIC_LOOP"|}
  | {|+type: "IN_EDGE", +edge: Edge|}
  | {|+type: "OUT_EDGE", +edge: Edge|};
```
The IN_EDGEs and OUT_EDGEs are self-explanatory. The single SYNTHETIC_LOOP are present so as to stabilize PageRank. However, this has the side effect of complicating logic that processes Contributors, as it means we can't assume that a contributor has an edge associated.

I don't think this special casing is actually needed. We could accomplish the same objective, without complicating our type signature, by shifting the synthetic edges to be data rather than type info. I.e., we could create a default plugin that provides the SYNTHETIC_LOOP edges (which are added like real edges during graphToMarkovChain translation).

I'm not sure if this is actually a good idea; it allows us to clean up the type signature, but it moves the "exceptional casing" out of the type layer where it is very clear, and into the value layer where it is unclear. So perhaps it's better to leave it in the type layer and just explicitly handle the complexity in downstream functions.

For context: I'm starting work on https://github.com/sourcecred/sourcecred/issues/502, and over the course of implementing it I found I needed a function that would sort all contributions by edge type, and return a data structure with aggregated contributions grouped by edge type. If the synthetic loop were just another edge type, this would be easy; however, it's presence as currently implemented makes everything more complicated.

@wchargin please let me know what you think.

**Comment by wchargin** [comment]
I’d prefer not doing this, though I’m not dead-set against it.

I’m not sure how exactly a plugin would provide synthetic loop edges for
every node in the graph. Such a plugin would need to know about the
nodes that all the other plugins have added to the combined graph, which
suggests that there needs to be a phase distinction: the synthetic loop
plugin would need to come “after” all the other plugins, and take the
intermediate graph as input.

Even if we did something like that, the semantics are still troublesome.
Currently, our `graphToMarkovChain` takes _any_ graph, and produces an
ergodic Markov chain. With this modification, the function would need to
take a restricted subset of graphs (namely, graphs where every node has
at least one out-edge). We could enforce that at run-time by hardcoding
that the “default plugin” must always be present, but this would then be
a “long-distance dependency” whose implications are not locally obvious
from either endpoint (and, as you say, not obvious from the types).
Similarly, test code calling into `graphToMarkovChain` would need to
perform the same addition of synthetic loops, and so on.

It sounds like the motivation for the suggestion is convenience of
implementation. Given the above, I’m doubtful that the convenience
justifies the fundamental changes to the data model.

**Comment by decentralion** [comment]
Good points @wchargin. Deciding not to do this.
