### ISSUE TITLE
Design and implementation of the Mirror module (formerly: Incremental/resumable GraphQL loading notes)

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#622]
Documenting design efforts here.

*Editor’s note:* Comments before 2018-08-10 describe older ideas of how the system might be designed, and were never implemented. Discussion of the design that we use today starts here: <https://github.com/sourcecred/sourcecred/issues/622#issuecomment-412228254>

**Comment by wchargin** [comment]
Daily dump of some stuff that is reasonably solid.

Object model:

```js
// A reference to a GraphQL node. The typename is its GraphQL type, as
// defined in a relevant schema. The ID is the unique ID assigned by the
// remote server (i.e., GitHub).
type Ref = {|+typename: Typename, +id: string|};

// The interface used by the GitHub plugin. Described below.
declare class GraphqlMirror {
  constructor(options: {|
    +storage: Storage,
    +schema: Schema,
    +ttl: Duration
  |}): void;
  update(root: Ref): void;
  denormalize(root: Ref): any;
}

// An abstraction over persistent storage.
interface Storage {
  write(filename: string, contents: string): void;
  read(filename: string): string | void;
  sync(): Promise<void>;
}

// Storage backed by a physical filesystem; `sync` writes to disk.
declare class DiskStorage implements Storage {
  constructor(basedir: string): void;
  ...Storage;
}

// Memory-only storage, for tests and such; `sync` is NOP.
declare class MemoryStorage implements Storage {
  constructor(initialState: Map<string, string>): void;
  ...Storage;
}
```

Top-level options (constructor to `GraphqlMirror`):

  - `storage`: Persistent storage, wholly scoped to the plugin and
    repository. In principle, this could be structurally shared across
    repositories, but we’ll keep it simple for now.
  - `schema`: A structured sub-GraphQL schema, as described above. This
    is required to remain fixed across invocations with the same cache
    directory; it may be persisted on disk to check for
    data-incompatible code upgrades.
  - `ttl`: Time to live; a duration after which data is to be considered
    stale.\* This may vary across invocations.

\* For liveness, we may wish to relax the definition of staleness to
prevent a case wherein our fetch rate can’t keep up with the TTL.
Semantics to be determined. This isn’t very important for an initial
version of the system, so we omit discussion.

Desired operations (methods on `GraphqlMirror`):

  - `update(root: Ref)`: Make any needed updates for `root` and any
    transitive dependencies. Writes to persistent storage, `sync`ing
    periodically (in particular, `sync`ing at each network request).
  - `denormalize(root: Ref)`: Create a structured form where IDs are
    replaced by their referents and connections are inlined as arrays,
    failing if any transitive dependencies are not met. The result will
    conform to the schema entry for type `root.typename`.

Workflow:

  - The GitHub plugin maintains a standalone registry mapping `Repo` to
    `Ref`. A query `repository(owner: "foo", name: "bar") { id }` is
    used to populate the repo-ref registry.
  - At `node ./bin/sourcecred.js load` time:
      - Retrieve the repository’s GraphQL ID `id` from the repo-ref
        registry, computing via a single GraphQL query if absent. Let
        `ref` be `{typename: "Repository", id}`.
      - Execute `update(ref)`.
      - Let `repo` be `denormalize(ref)`.
      - Construct a `RelationalView` from `repo`, and store it on disk
        in the data directory.
  - At runtime, the relational view is loaded from disk as usual.

Update semantics:

  - A node is _up to date_ if (a) it is present, (b) its mtime is more
    recent than the TTL, and (c) if it is a connection, it is exhausted.
  - Updating an object node entails fetching its data and replacing the
    existing content.
  - Append-updating a connection node entails fetching any remaining
    elements, starting from its end cursor.
  - Full-updating a connection node essentially entails removing it and
    then append-updating it. Only a full update will pick up deletions,
    reorders, etc. of elements in the list. We may or may not support
    full-updating in the first version, as we do not expect this to be a
    big issue; the data that we care about is append/edit-only in the
    vast majority of cases.

**Comment by wchargin** [comment]
```sql
-- Current thoughts about representation follow.


-- A singleton table. We store the stable-stringified JSON schema
-- here. At each load, we check that it is consistent to prevent
-- data incompatibility. This is redundant with the actual table
-- structure, but is convenient and only incurs a small constant
-- additive increase in space usage.
CREATE TABLE meta (
    json_schema TEXT NOT NULL
);

-- An "update" is an invocation of `node ./bin/sourcecred.js load`. Such
-- an update may write to the database multiple times, updating the
-- timestamp each time, so that the final timestamp associated with the
-- update is the time that the update completes.
CREATE TABLE updates (
    time_epoch_seconds INTEGER NOT NULL /* epoch time in seconds */
);

-- Each node has an entry in `objects`. Its data is stored across three
-- tables:
--   * for primitives, a type-specific "data" table;
--   * for singleton fields (e.g., author of issue), the "links" table;
--   * for connections (e.g., comments on PR), the "connections" table.
CREATE TABLE objects (
    id TEXT PRIMARY KEY NOT NULL,
    last_update INTEGER,
    typename TEXT NOT NULL,  -- needed for union/interface deref
    FOREIGN KEY(last_update) REFERENCES updates(rowid)
) WITHOUT ROWID;

CREATE TABLE links (
    parent_id TEXT NOT NULL,
    fieldname TEXT NOT NULL,
    child_id TEXT NOT NULL,
    PRIMARY KEY(parent_id, fieldname),
    FOREIGN KEY(parent_id) REFERENCES objects(id),
    FOREIGN KEY(child_id) REFERENCES objects(id)
) WITHOUT ROWID;
CREATE TABLE connections (
    object_id TEXT NOT NULL,
    fieldname TEXT NOT NULL,
    end_cursor TEXT /* may be null if no items */,
    UNIQUE(object_id, fieldname)
);
CREATE TABLE connection_entries (
    conn_id INTEGER NOT NULL,
    idx INTEGER NOT NULL,  -- impose an ordering
    child_id TEXT NOT NULL,
    FOREIGN KEY(conn_id) REFERENCES connections(rowid)
);

-- Primitives on objects.
CREATE TABLE data_Repository (
    id TEXT NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    starcount INTEGER NOT NULL
) WITHOUT ROWID;
CREATE TABLE data_Organization (
    id TEXT NOT NULL PRIMARY KEY,
    login TEXT NOT NULL
) WITHOUT ROWID;
CREATE TABLE data_User (
    id TEXT NOT NULL PRIMARY KEY,
    login TEXT NOT NULL
) WITHOUT ROWID;
CREATE TABLE data_Issue (
    id TEXT NOT NULL PRIMARY KEY,
    num INTEGER NOT NULL,
    title TEXT NOT NULL
) WITHOUT ROWID;

-- Example data.
INSERT INTO updates VALUES (1533851800);
INSERT INTO objects (last_update, typename, id) VALUES
    (1, 'Repository', 'repo:sc/sc'),
    (1, 'Organization', 'org:sourcecred'),
    (1, 'Issue', 'issue:sc#1'),
    (1, 'User', 'user:wchargin')
;
INSERT INTO connections (object_id, fieldname, end_cursor) VALUES
    ('repo:sc/sc', 'issues', 'cr123'),
    ('issue:sc#1', 'comments', NULL)
;
INSERT INTO links (parent_id, fieldname, child_id) VALUES
    ('repo:sc/sc', 'owner', 'org:sourcecred'),
    ('issue:sc#1', 'author', 'user:wchargin')
;
INSERT INTO connection_entries (conn_id, idx, child_id) VALUES
    (1 /* (repo:sc/sc).issues */, 0, 'issue:sc#1')
;

INSERT INTO data_Repository (id, description, starcount) VALUES
    ('repo:sc/sc', 'open source is pretty cool', 57);
INSERT INTO data_Organization (id, login) VALUES
    ('org:sourcecred', 'sourcecred');
INSERT INTO data_User (id, login) VALUES
    ('user:wchargin', 'wchargin');
INSERT INTO data_Issue (id, num, title) VALUES
    ('issue:sc#1', 1, 'todo: write the code');

-- We can find transitive dependencies...
WITH RECURSIVE cte_deps (id) AS (
    SELECT 'repo:sc/sc'
    UNION SELECT connection_edges.child FROM cte_deps JOIN (
        SELECT parent_id AS parent, child_id AS child FROM links
        UNION
        SELECT
            connections.object_id AS parent,
            connection_entries.child_id AS child
        FROM connections JOIN connection_entries
        ON connections.rowid = connection_entries.conn_id
    ) AS connection_edges
    ON cte_deps.id = connection_edges.parent
)
--
-- ...and see which are out of date:
SELECT typename, objects.id, last_update FROM objects LEFT OUTER JOIN cte_deps
ON objects.id = cte_deps.id
WHERE last_update < 2;  -- could do a join with timestamp to be more specific

-- vim: ft=sql
```

**Comment by wchargin** [comment]
Let me elaborate on the previous dump of SQL code.

Our goal is to persistently store and update a subset of entities
fetched from a remote GraphQL server. There are three evident approaches
to the storage aspect:
  - Store everything in a `db.json` file.
  - Store each object in a separate file, like `issue_17.json`.
  - Use a SQL database or other similar tool.

The first option has serious disadvantages. Reading any object requires
deserializing a massive blob of JSON. Writing any object or making in a
change requires serializing a similarly massive blob. These limitations
mean that you have to store the entire string in Node memory (unless you
have some on-the-fly JSON decoder that reads from a stream directly),
and you have to store the whole database in memory to read a single
object. Node also has limits on the size of a string, which we have
already hit on large repositories.

The second option also has disadvantages. We might easily have tens of
thousands of objects to store—for instance, the GitHub graph for
`metamask/metamask-extension` has 31 853 nodes at last count. This
incurs a lot of syscalls, a lot of context switches, and a lot of
interaction with the filesystem. Typical filesystems also struggle with
directories that have a large number of entries—operations like
pathname-to-inode resolution perform a linear scan over the directory
entries—so we’d want to perform some kind of chunking, like Git does
with `.git/objects/??/*`.

In light of the above discussion, it becomes clear that it is silly to
deal with these problems when the solution is clear: just use an actual
database. SQLite is an attractive choice: it stores its database in a
single file, it is lightweight and portable, and it has a plethora of
Node bindings. Thus, we adopt this approach.

The remainder of this document is a literate SQL script. You can run it
with

```shell
src=/path/to/this/document &&
db=/tmp/test.db &&
rm -f "$db" &&
sqlite3 "$db" < <(print_code_fences -v lang=sql "$src")
```

where `print_code_fences` comes from [this gist][1].

[1]: https://gist.github.com/wchargin/e7e72370efe58d0959e2fb68065ae539

<details>
<summary>Boilerplate</summary>

First, some setup for pretty-printing, and an indication that SQLite
should check foreign key constraints. (Without the PRAGMA, everything
would work, but the foreign key annotations would be ignored.)

```sql
.mode line
PRAGMA foreign_keys = ON;
```

</details>

Our goal is to turn a schema for a subset of a GraphQL database into a
schema for a SQL database. We will demonstrate on a subset of the GitHub
schema.

We start with a safety check. If the schema changes between invocations,
we should fail and require the user to blow away all data. The simplest
way to do this is to store a JSON-serialized version of the GraphQL
schema from which we generated the SQL schema, and check at each
invocation that it matches the schema that we expect. There’s a bit of
redundancy here, but that’s okay (the additional space used is totally
negligible). We store this data in a singleton table.

```sql
CREATE TABLE meta (
    json_schema TEXT NOT NULL
);
```

Next, we define what it means for data to be out of date. We say that a
single invocation of `node ./bin/sourcecred.js load` is an _update_. An
update has an associated timestamp, but an update may write to the
database multiple times (say, between network requests), updating its
timestamp each time. Then the final timestamp associated with an update
is the time that the update completes.

```sql
CREATE TABLE updates (
    rowid INTEGER PRIMARY KEY,
    time_epoch_seconds INTEGER NOT NULL
);
```

Our GraphQL objects will be stored as follows. Each GraphQL object has
an entry in the `updates` table, which is only a registry. It stores the
last time that the object was updated, and the GraphQL type associated
with the object, but does not store any actual data.

```sql
CREATE TABLE objects (
    id TEXT PRIMARY KEY NOT NULL,
    last_update INTEGER,
    typename TEXT NOT NULL,
    FOREIGN KEY(last_update) REFERENCES updates(rowid)
) WITHOUT ROWID;
```

The data for an object is stored across three tables, depending on the type of each field.

  - Primitive data is stored in an type-specific table, like
    `data_Repository`. The fact that this table is type-specific means
    that the actual data can be stored with locality and with strong
    typing.
  - A reference to a single other GraphQL object, like the author of an
    issue or the owner of a repository, is stored in the `links` table.
  - A connection, like the labels on a pull request or the comments on a
    review, is stored in the `connections` table, and individual entries
    in the connection are stored in the `connection_entries` table.

Here are the schemata for the link and connection tables:

```sql
CREATE TABLE links (
    parent_id TEXT NOT NULL,
    fieldname TEXT NOT NULL,
    child_id TEXT NOT NULL,
    PRIMARY KEY(parent_id, fieldname),
    FOREIGN KEY(parent_id) REFERENCES objects(id),
    FOREIGN KEY(child_id) REFERENCES objects(id)
) WITHOUT ROWID;

CREATE TABLE connections (
    rowid INTEGER PRIMARY KEY,
    object_id TEXT NOT NULL,
    fieldname TEXT NOT NULL,
    -- The end cursor may be NULL if no items are in the connection;
    -- this is a consequence of GraphQL and the Relay pagination spec.
    end_cursor TEXT,
    UNIQUE(object_id, fieldname)
);

CREATE TABLE connection_entries (
    rowid INTEGER PRIMARY KEY,
    conn_id INTEGER NOT NULL,
    idx INTEGER NOT NULL,  -- impose an ordering
    child_id TEXT NOT NULL,
    UNIQUE(conn_id, idx),
    FOREIGN KEY(conn_id) REFERENCES connections(rowid),
    FOREIGN KEY(child_id) REFERENCES objects(id)
);
```

I considered using `(object_id, fieldname)` as the primary key for
`connections`. This makes logical sense to me, but it incurs a
non-trivial increase in the space usage of `connection_entries`. Typical
GitHub IDs range in length from ~20 to ~40 characters (Base64 code
units), for a total PK size of maybe ~30 to ~50 bytes. TensorFlow, a
large repository, has ~32K issues and pull requests combined; if we take
each of these to have 8 or 16 or even 128 transitive connections on
average, then a numeric connection ID would have around 16 to 22 _bits_
total, making it a factor of ~18 smaller than the structured primary
key.

Here are some sample type-specific data tables:

```sql
CREATE TABLE data_Repository (
    id TEXT NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    starcount INTEGER NOT NULL,
    FOREIGN KEY(id) REFERENCES objects(id)
) WITHOUT ROWID;
CREATE TABLE data_Organization (
    id TEXT NOT NULL PRIMARY KEY,
    login TEXT NOT NULL,
    FOREIGN KEY(id) REFERENCES objects(id)
) WITHOUT ROWID;
CREATE TABLE data_User (
    id TEXT NOT NULL PRIMARY KEY,
    login TEXT NOT NULL,
    FOREIGN KEY(id) REFERENCES objects(id)
) WITHOUT ROWID;
CREATE TABLE data_Issue (
    id TEXT NOT NULL PRIMARY KEY,
    num INTEGER NOT NULL,
    title TEXT NOT NULL,
    FOREIGN KEY(id) REFERENCES objects(id)
) WITHOUT ROWID;
```

Note that the foreign keys ensure that any referenced object must exist
in the `objects` table, but this doesn’t mean that we have to have data
for any referenced object. This is good!

Implicit in this schema is the key restriction that the set of data that
we care about is fully determined by an object’s type. For instance, it
is _not_ the case that we want to record a user’s email address if we
reached them from a Git commit, but we don’t care about it if they just
posted an issue. On the contrary: a `User` is a `User`; we define a
certain set of `User` fields to store, and we store them for every user.

Storing the typename of an object in the `objects` table is necessary to
handle interface and union types. For instance, from the GraphQL schema
for `Repository`, we know that the `owner` property has type `Actor`.
But an actor could be a user, an organization, or a bot. If all we know
is that a repository’s owner has a particular ID, we won’t know _a
priori_ whether to look up its data in the `data_User` table or the
`data_Organization` table. The `typename` field disambiguates this.

Here is some example data. We use human-readable IDs for this example,
but the IDs would actually be GitHub’s opaque Base64-encoded strings.

```sql
INSERT INTO updates (time_epoch_seconds) VALUES (1533851800), (1533940400);
INSERT INTO objects (last_update, typename, id) VALUES
    (1, 'Repository', 'repo:sc/sc'),
    (1, 'Organization', 'org:sourcecred'),
    (1, 'Issue', 'issue:sc#1'),
    (2, 'Issue', 'issue:sc#2'),
    (1, 'User', 'user:wchargin'),
    (2, 'User', 'user:decentralion'),
    (1, 'User', 'user:bystander')
;

-- Now that the objects have been defined, the following insert
-- statements can be commuted in any order.

INSERT INTO connections (object_id, fieldname, end_cursor) VALUES
    ('repo:sc/sc', 'issues', 'cr123'),
    ('issue:sc#1', 'comments', NULL),
    ('issue:sc#2', 'comments', NULL)
;
INSERT INTO links (parent_id, fieldname, child_id) VALUES
    ('repo:sc/sc', 'owner', 'org:sourcecred'),
    ('issue:sc#1', 'author', 'user:wchargin'),
    ('issue:sc#2', 'author', 'user:decentralion')
;
INSERT INTO connection_entries (conn_id, idx, child_id) VALUES
    (1, 0, 'issue:sc#1'),  -- 1 = (repo:sc/sc).issues
    (1, 1, 'issue:sc#2')   -- 1 = (repo:sc/sc).issues
;

INSERT INTO data_Repository (id, description, starcount) VALUES
    ('repo:sc/sc', 'open source is pretty cool', 58);
INSERT INTO data_Organization (id, login) VALUES
    ('org:sourcecred', 'sourcecred');
INSERT INTO data_User (id, login) VALUES
    ('user:wchargin', 'wchargin'),
    ('user:decentralion', 'decentralion'),
    ('user:bystander', 'bystander');
INSERT INTO data_Issue (id, num, title) VALUES
    ('issue:sc#1', 1, 'todo: write the code'),
    ('issue:sc#2', 2, 'todo: ship the thing');
```

Note that the foreign key constraints prevent some kinds of errors—any
of the following queries would raise an error because `issue:sc#3` and
`user:someone-else` are not registered as objects:

```sql
/*
INSERT INTO data_Issue (id, num, title) VALUES
    ('issue:sc#3', 1, 'todo: add this object to the database');
INSERT INTO links (parent_id, fieldname, child_id) VALUES
    ('issue:sc#1', 'assignee', 'user:someone-else');
INSERT INTO links (parent_id, fieldname, child_id) VALUES
    ('issue:sc#3', 'author', 'user:wchargin');
INSERT INTO connection_entries (conn_id, idx, child_id) VALUES
    (1, 2, 'issue:sc#3');  -- 1 = (repo:sc/sc).issues
*/
```

By expressing the links and the connections in the relational model, we
can leverage the expressive power of SQL to do useful work. For
instance, if we’ve been asked to bring a particular repository node up
to date, we can ask SQLite exactly which objects are transitively
referenced and have not been updated since a certain time (which falls
between update 1 and update 2):

```sql
WITH RECURSIVE cte_deps (id) AS (
    VALUES ('repo:sc/sc')
    UNION SELECT connection_edges.child FROM cte_deps JOIN (
        SELECT parent_id AS parent, child_id AS child FROM links
        UNION
        SELECT object_id AS parent, child_id AS child
        FROM connections JOIN connection_entries
        ON connections.rowid = connection_entries.conn_id
    ) AS connection_edges
    ON cte_deps.id = connection_edges.parent
)
SELECT typename, cte_deps.id, last_update
FROM objects
LEFT OUTER JOIN updates ON last_update = updates.rowid
JOIN cte_deps ON objects.id = cte_deps.id
WHERE last_update IS NULL OR updates.time_epoch_seconds < 1533851801;
```

This prints:

```
   typename = Issue
         id = issue:sc#1
last_update = 1

   typename = Organization
         id = org:sourcecred
last_update = 1

   typename = Repository
         id = repo:sc/sc
last_update = 1

   typename = User
         id = user:wchargin
last_update = 1
```

Note that `issue:sc#2` and `user:decentralion` are not printed because
they were updated recently enough, and `user:bystander` is not printed
because there is no transitive reference to that user.

Next on the table: given a GraphQL schema, what kinds of GraphQL queries
do we generate? (In particular: how are initial fetches different from
updates?)

**Comment by wchargin** [comment]
At this point, I turn to implementation, with the following rough plan:

  - Create the `schema` module.
  - Generate a SQL schema from a GraphQL schema.
  - Implement an “initial query” API that adds the root object (e.g., a
    GitHub repository).
  - Implement updates.

**Comment by decentralion** [comment]
Just a thought for as you're working on this:
It would be really great if we could show a progress bar on the GitHub load.

**Comment by wchargin** [comment]
> It would be really great if we could show a progress bar on the GitHub
> load.

I’ve been thinking about that. On the one hand, it’s tricky, because
we’re exploring an object graph of unknown size. But on the other hand,
we do have some information available. We can pull the `totalCount` off
of each connection, so we can immediately know how many issues and pull
requests a repository has. In practice, this is probably a pretty good
heuristic for overall progress. It’s not perfect, because it obscures
the fact that some issues might have a thousand comments while others
have none. But it should at least be monotonically increasing (unless
new issues are posted while querying, which is an inevitable
concession).

So, what I have in mind is the following: for each connection on the
root-level object (i.e., the repository’s issues, pull requests, labels,
etc.), sum the number of nodes fetched and divide by the sum of the
appropriate `totalCount`s, and use this as the progress indicator. The
granularity will be that the progress bar updates once per GitHub query,
which should be every few seconds. ([Here is a run of the current system
against TensorFlow][tf]; the median duration is 5.25 seconds, the 90th
percentile is 10.4 seconds, and the maximum is 10.6 seconds. Query times
may be different in the new system, but not by orders of magnitude.)

[tf]: https://gist.github.com/wchargin/2e4352b5e875cf764e1ea64f56ed13b7

Does this sound good to you?

**Comment by decentralion** [comment]
That sounds great.

**Comment by wchargin** [comment]
Status update: I’ve written implementations(+docs+tests) for the core
functionality that enables emitting queries for the important pieces of
the data model, ingesting the results of those queries, and extracting
structured objects from the repository. Remaining to be done are some
abstractions on top of this to wire everything together and produce a
nice client API, plus integration with the GitHub plugin and perhaps
end-to-end tests. Usually I’d want to get things “just right” in a stack
of commits and PR them at the same time, but per @decentralion’s
suggestion I’ll PR each one once it’s in a state that at least locally
seems good. Benefit of this include that it minimizes Travis
babysitting, that it makes incremental review more feasible, and that it
keeps the code from diverging too much from master. This may induce some
churn, but that’s okay.

**Comment by wchargin** [comment]
Status update. I’ve been chugging along (commits that made functional
progress, as opposed to minor refactors or redesigns, are linked above
(pardon the voluminous GitHub spam)). The `Mirror` module now has all
the core functionality to register a root object, fetch dependent
objects, and then extract an arbitrary object as structured data. I
still have to write porcelain on top of this to provide a nice internal
API and a nice public API.

I’ve also discovered an issue in the formulation due to recent changes
in the data that we want from GitHub. In particular, we recently added
support for fetching the GitHub user who authored a commit. This
involves querying `commit { author { user } }`, where `author` points to
a `GitActor`. But the `GitActor` object type does not have an ID, so we
cannot handle it, because there would be no way to query this for
updates.

Clearly, we need to be able to handle this in some form or another
before Mirror is ready. I see two approaches:

  - Somehow record that a `GitActor` needs to be “owned” by a commit,
    and updates should be fetched by re-querying the enclosing commit:
    like `node(id: ...) { ... on Commit { author { ...fields } } }`.
    Note that we would need to retain a whole upward path of
    fieldnames/arguments (a commit has both an `author` and a
    `committer`, both `GitActor`s), terminating in an object ID and
    typename.

  - Imagine that `Commit` has a field named `author.user`, treated as
    own-data of the commit. Update this with all other own-data,
    transparently reaching into the `GitActor` in the actual query.

I prefer the latter solution. It’s simpler, I think, and requires a less
drastic reduction to the status quo.

In particular, I plan to implement a restricted version of this
approach, wherein we only support nested fields of own-data type (not
connection type). This is more convenient to implement, because it means
that the top-level field selections given by `_queryOwnData` and
`_queryConnection` are necessarily disjoint. Also, I don’t have any
real-world test cases for the full functionality (a connection on a
nested object without an ID). If we want the full functionality later,
it will be quite easy to add (and should even be backward-compatible).

Before implementing this extension, I plan to finish up the “v0” version
of the `Mirror` module, by adding the aforementioned porcelain to
support everything except for these nested fields. This is primarily
because I already have a fair amount of code, tests, and context along
this path, and don’t want these to go stale. I don’t view this as
merging something “broken”—it’s well-documented that we only work with a
particular subset of GraphQL APIs, and we simply plan to expand that
subset later.

**Comment by wchargin** [comment]
Having all of our data available in a local SQL database is powerful. It
enables us to ask questions of our data that we just can’t with the
GitHub APIs.

For instance: “who, other than the SourceCred maintainers, has reacted
to posts in the SourceCred repository? What are these posts and
reactions?”

The answer is just a query away:

```sql
$ cat whoreacts.sql
.mode line  -- pretty-printing
SELECT
    reactor_data.login AS reactor_name,
    content AS reaction_type,
    reactables.typename AS reactable_typename,
    reactable_id AS reactable_id,
    COALESCE(issue_data.url, issuecomment_data.url, '(no url found)') AS url
FROM
(
    SELECT rowid AS connection_id, object_id AS reactable_id
    FROM connections
    WHERE fieldname = 'reactions'
) AS reaction_connections
JOIN objects AS reactables
    ON reaction_connections.reactable_id = reactables.id
JOIN connection_entries USING (connection_id)
JOIN objects AS reactions
    ON connection_entries.child_id = reactions.id
JOIN (
    SELECT parent_id AS reaction_id, child_id AS reactor_id FROM links
    WHERE fieldname = 'user'
) AS reaction_authors
    ON reactions.id = reaction_authors.reaction_id
JOIN objects AS reactors
    ON reaction_authors.reactor_id = reactors.id
JOIN primitives_User AS reactor_data
    ON reactors.id = reactor_data.id
JOIN primitives_Reaction AS reaction_data
    ON reactions.id = reaction_data.id
LEFT OUTER JOIN primitives_Issue AS issue_data
    ON reaction_connections.reactable_id = issue_data.id
LEFT OUTER JOIN primitives_IssueComment AS issuecomment_data
    ON reaction_connections.reactable_id = issuecomment_data.id
WHERE reactor_name NOT IN ('"wchargin"', '"decentralion"')
;
```

And the results:

```
$ sqlite3 /tmp/mirror.db <whoreacts.sql
      reactor_name = "owocki"
     reaction_type = "THUMBS_UP"
reactable_typename = Issue
      reactable_id = MDU6SXNzdWUzNTI2NjA5ODA=
               url = "https://github.com/sourcecred/sourcecred/issues/696"

      reactor_name = "ashwaniYDV"
     reaction_type = "THUMBS_UP"
reactable_typename = Issue
      reactable_id = MDU6SXNzdWUzNjU3MDYwMjc=
               url = "https://github.com/sourcecred/sourcecred/issues/905"

      reactor_name = "claireandcode"
     reaction_type = "THUMBS_UP"
reactable_typename = IssueComment
      reactable_id = MDEyOklzc3VlQ29tbWVudDQxMDA0NzY3MA==
               url = "https://github.com/sourcecred/sourcecred/issues/586#issuecomment-410047670"

      reactor_name = "campoy"
     reaction_type = "HEART"
reactable_typename = IssueComment
      reactable_id = MDEyOklzc3VlQ29tbWVudDQxMDEzMzYxMw==
               url = "https://github.com/sourcecred/sourcecred/pull/598#issuecomment-410133613"

      reactor_name = "bzz"
     reaction_type = "HOORAY"
reactable_typename = IssueComment
      reactable_id = MDEyOklzc3VlQ29tbWVudDQxMDEzMzYxMw==
               url = "https://github.com/sourcecred/sourcecred/pull/598#issuecomment-410133613"
```

**Comment by wchargin** [comment]
Here are some file size comparisons using the `sourcecred/sourcecred`
repository data:

| Compression | Post bodies | RelationalView (B) | SQLite (B) |
|---|---|--:|--:|
| None | Included | 4 945 499 | 6 569 984 |
| Gzip | Included | 910 654   | 1 656 186 |
| None | Removed  | 3 219 701 | N/A       |
| Gzip | Removed  | 244 632   | N/A       |
```

(All sizes are in bytes.)

Note that tables account for 67.8% of the total database size; indices
account for the other 32.2%. Given that our performance is currently
plenty fast (and honestly we don’t do very much CPU-work), we could
probably drop all the indices without a big performance hit.

Note also that 16% of the per-byte space in the SQLite database is
unused. This proportion should decrease as the size of the database
increases, and does not increase the on-disk size.

**Comment by wchargin** [comment]
The Mirror system works and is integrated into SourceCred! :tada:

I’ve noted some enhancements that I would like to see moving forward in
#938, #939, and #940. But the core is complete, so I think that this
issue can be closed.

**Comment by wchargin** [comment]
A debugging/investigation story, per @decentralion’s request.

I had been running the following command to track the progress of the
Mirror load for tbws/bootstrap:

```
watch -n 1 '
    sqlite3 /tmp/sourcecred/cache/twbs/bootstrap/github/mirror_*.db \
    "SELECT typename, COUNT(1) FROM objects GROUP BY typename" |
    tr "|" "\t" | sort -n -k2 | expand -t 20
'
```

This printed:

```
Organization        1
Ref                 1
Repository          1
PullRequestReview   2890
Reaction            3519
Commit              3628
PullRequest         9218
User                17019
Issue               17843
IssueComment        60563
```

I noted that all the pull requests and issues had been fetched, but
there were far fewer commits than pull requests. This was strange,
because surely each merged pull request has a merge commit—were so few
pull requests really merged? Searching for “is:pr is:merged ” on GitHub
confirmed that there were in fact 4457 merged pull requests in this
repository, so something was inconsistent with my expectations.

I opened a SQLite shell to investigate:

```
$ sqlite3 /tmp/sourcecred/cache/twbs/bootstrap/github/mirror_*.db
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> 
```

Perhaps I had registered all these pull requests but not fetched all of
their data:

```
sqlite> SELECT z, COUNT(1) FROM (
   ...>   SELECT last_update IS NULL AS z
   ...>   FROM objects WHERE typename = 'PullRequest'
   ...> ) GROUP BY z;
0|9218
```

No: all 9218 pull requests had non-NULL update times.

Did the Mirror module fail to follow the links properly, or are the pull
requests really missing merge commits?

```
sqlite> SELECT z, COUNT(1) FROM (
   ...>   SELECT child_id IS NULL AS z
   ...>   FROM links WHERE fieldname = 'mergeCommit'
   ...> ) GROUP BY z;
0|2698
1|6520
```

Okay: most of the pull requests really do have null `mergeCommit`. Which
ones? Are there observable patterns? Let’s list some of them:

```
sqlite> SELECT url FROM
   ...> primitives_PullRequest JOIN links ON primitives_PullRequest.id = parent_id
   ...> WHERE fieldname IS 'mergeCommit' AND child_id IS NOT NULL
   ...> ORDER BY CAST(number AS INTEGER) DESC
   ...> LIMIT 10;
"https://github.com/twbs/bootstrap/pull/27566"
"https://github.com/twbs/bootstrap/pull/27563"
"https://github.com/twbs/bootstrap/pull/27562"
"https://github.com/twbs/bootstrap/pull/27560"
"https://github.com/twbs/bootstrap/pull/27556"
"https://github.com/twbs/bootstrap/pull/27547"
"https://github.com/twbs/bootstrap/pull/27544"
"https://github.com/twbs/bootstrap/pull/27540"
"https://github.com/twbs/bootstrap/pull/27539"
"https://github.com/twbs/bootstrap/pull/27533"
```

Comparing to the first page of search results for “is:pr is:merged ” on
GitHub, these match up. How about the ones at the very beginning?

```
sqlite> SELECT url FROM
   ...> primitives_PullRequest JOIN links ON primitives_PullRequest.id = parent_id
   ...> WHERE fieldname IS 'mergeCommit' AND child_id IS NOT NULL
   ...> ORDER BY CAST(number AS INTEGER) ASC
   ...> LIMIT 10;
"https://github.com/twbs/bootstrap/pull/1"
"https://github.com/twbs/bootstrap/pull/3"
"https://github.com/twbs/bootstrap/pull/12"
"https://github.com/twbs/bootstrap/pull/16"
"https://github.com/twbs/bootstrap/pull/21"
"https://github.com/twbs/bootstrap/pull/30"
"https://github.com/twbs/bootstrap/pull/51"
"https://github.com/twbs/bootstrap/pull/58"
"https://github.com/twbs/bootstrap/pull/71"
"https://github.com/twbs/bootstrap/pull/87"
```

Comparing to the last page of search results, we see that PR `#26` was
“merged” on GitHub, but it is absent from our list—we do not have a
`mergeCommit` for it!

Nothing seems amiss on that pull request’s page. Indeed, it says, “mdo
merged commit `7852619` into `twbs:master` on Aug 20, 2011”.

What happens if we query this manually?

```
$ ghquery '{
>   resource(url: "https://github.com/twbs/bootstrap/pull/26") {
>     ... on PullRequest { url merged mergeCommit { id } }
>   }
> }' | jq .
{
  "data": {
    "resource": {
      "url": "https://github.com/twbs/bootstrap/pull/26",
      "merged": true,
      "mergeCommit": null
    }
  }
}
```

(Here, [`ghquery` is my shell function for querying GitHub][ghquery].
The same query works in the GraphiQL instance.)

[ghquery]: https://gist.github.com/wchargin/630e03e66fa084b7b2297189615326d1

Indeed, this commit is `merged` but has no `mergeCommit`. Strange.

I’m still investigating what’s actually going on here, but I hope that
this helps demonstrate how inspecting a SQLite database can be valuable
for debugging.

**Comment by decentralion** [comment]
@wchargin, a question for you.

In the documentation, the `child_id` field on the `connection_entries` table is not null, which makes sense to me:

```sql
CREATE TABLE connection_entries (
    conn_id INTEGER NOT NULL,
    idx INTEGER NOT NULL,  -- impose an ordering
    child_id TEXT NOT NULL,
    FOREIGN KEY(conn_id) REFERENCES connections(rowid)
);
```

However [as implemented][1] the field is nullable. Why is this?

[1]: https://github.com/sourcecred/sourcecred/blob/99b2b12a14c80ca427ca0fc47e4cfbf324b572a2/src/graphql/mirror.js#L285

**Comment by wchargin** [comment]
> In the documentation, the `child_id` field on the `connection_entries`
> table is not null […] However as implemented the field is nullable.
> Why is this?

Because the elements of a collection actually are nullable: for example,
a [`UserConnection`][uc] has `nodes` at `[User]`, not `[User!]`.

I can’t recall off the top of my head if we’ve ever run into this in
practice, but it seemed best for the storage layer to be sound with
respect to the schema provided by the server.

[uc]: https://developer.github.com/v4/object/userconnection/
