### ISSUE TITLE
Round the corners of the SourceCred logo

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#647]
The current SourceCred logo is a square. I think it would look nicer with rounded corners. The Discord UI does a pretty nice job IMO:

![image](https://user-images.githubusercontent.com/1400023/43989635-ef655058-9d02-11e8-958e-586bb742cfaa.png)

Should be a simple modification of the artisanal, hand-crafted SVG added in https://github.com/sourcecred/sourcecred/pull/636

**Comment by wchargin** [comment]
I would like to register that the team is not unanimous on this issue.
:-)

Personally, I think that it looks much nicer with square corners than
rounded corners. The circle in the center, the diagonal spokes, and the
square field balance each other quite nicely.

I’d suggest that this be untagged “contributions welcome” and instead
considered as “waiting until an actual designer checks in”.

**Comment by decentralion** [comment]
Closing in favor of https://github.com/sourcecred/mission/issues/5
