### ISSUE TITLE
Consider removing Address↔string conversion functions

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#66]
Consider removing address↔string conversion functions

**understandabad** (*adj.*): A seemingly confusing decision that makes sense only once you realize the implementation details behind a leaky abstraction.

*ex.* Our `Address` type requires that none of its components contain a literal dollar sign. Why? Because the `addressToString` and `stringToAddress` conversions use the dollar sign as a delimiter for the three components, and string forms are used as keys in the `Graph`’s maps.

We could relatively easily allow arbitrary addresses by using nested maps:

```js
type AddressMap<T> = {[repositoryName: string]: {[pluginName: string]: {[id: string]: T}}};
class Graph {
  nodes: AddressMap<Node<mixed>>;
  edges: AddressMap<Edge<mixed>>;
  /* ... */
}
/* private */ function addressMapGet<T>(map: AddressMap<T>, key: Address): ?T {
  const repositoryBucket = map[key.repositoryName];
  if (repositoryBucket === undefined)
    return undefined;
  const pluginNameBucket = repositoryBucket[key.pluginName];
  if (pluginNameBucket === undefined)
    return undefined;
  return pluginNameBucket[key.id];
}
/* private */ function addressMapSet<T>(map: AddressMap<T>, key: Address, value: T) {
  let repositoryBucket = map[key.repositoryName];
  if (repositoryBucket === undefined)
    repositoryBucket = map[key.repositoryName] = {};
  let pluginNameBucket = repositoryBucket[key.pluginNameName];
  if (pluginNameBucket === undefined)
    pluginNameBucket = repositoryBucket[key.pluginNameName] = {};
  pluginNameBucket[key.id] = value;
}
```
This would be a completely under-the-hood implementation change, and would remove the `$`-restriction. It may well be a faster implementation, too.

**Comment by dandelionmane** [comment]
What if we replace `addressToString(address)` with `JSON.stringify(address)`?
We get the same benefits, and perhaps more (going to add a comment on #65 going into more details). And it's simpler than both your suggestion, and the current implementation.

**Comment by dandelionmane** [comment]
Since it's just an implementation detail, favoring the more-complex approach over JSON.stringify seems like premature optimization; we can revive the triplemap when/if JSON.stringify shows up on our profilers.

**Comment by dandelionmane** [comment]
Also, understandabad: 👍

**Comment by dandelionmane** [comment]
I decided to test it.

Test 1:
```js
function addressMapGet(map, key) {
  let repositoryBucket = map[key.repositoryName];
  if (repositoryBucket === undefined)
    return undefined;
  let pluginNameBucket = repositoryBucket[key.pluginName];
  if (pluginNameBucket === undefined)
    return undefined;
  return pluginNameBucket[key.id];
}
function addressMapSet(map, key, value) {
  let repositoryBucket = map[key.repositoryName];
  if (repositoryBucket === undefined)
    repositoryBucket = map[key.repositoryName] = {};
  let pluginNameBucket = repositoryBucket[key.pluginName];
  if (pluginNameBucket === undefined)
    pluginNameBucket = repositoryBucket[key.pluginName] = {};
  pluginNameBucket[key.id] = value;
}

let exampleAddressMap = {};

let repos = ["ironfield", "copperfield", "oilpatch", "smelters", "mainbase"];
let plugins = ["belts", "bots", "trains", "pipes", "furnaces"];

let addresses = [];

for (let r of repos) {
  for (let p of plugins) {
    for (let i=0; i<100; i++) {
      let id = $`{r/p/i}`;
      let address = {repositoryName: r, pluginName: p, id: id};
      addresses.push(address);
    }
  }
}

let addressMap = {};
for (let a of addresses) {
  addressMapSet(addressMap, a, {});
}


console.time();
for (let i=0; i<1000; i++) {
  for (let a of addresses) {
    addressMapGet(addressMap, a);
  }
}
console.timeEnd();
// Result: 753ms
```


Test 2:
```

function addressMapGet(map, key) {
  return map[JSON.stringify(key)];
}
function addressMapSet(map, key, value) {
  map[JSON.stringify(key)] = value;
}

let exampleAddressMap = {};

let repos = ["ironfield", "copperfield", "oilpatch", "smelters", "mainbase"];
let plugins = ["belts", "bots", "trains", "pipes", "furnaces"];

let addresses = [];

for (let r of repos) {
  for (let p of plugins) {
    for (let i=0; i<100; i++) {
      let id = $`{r/p/i}`;
      let address = {repositoryName: r, pluginName: p, id: id};
      addresses.push(address);
    }
  }
}

let addressMap = {};
for (let a of addresses) {
  addressMapSet(addressMap, a, {});
}

console.time()
for (let i=0; i<1000; i++) {
  for (let a of addresses) {
    addressMapGet(addressMap, a);
  }
}
console.timeEnd()
//2886 ms

console.time()
for (let i=0; i<1000; i++) {
  for (let a of addresses) {
    addressMapGet(addressMap, a);
  }
}
console.timeEnd()
// 2885 ms
```

So yeah, the JSON.stringify approach is about 4x slower. I think it's a fair inference that this will be on the critical path. So, I support using your more efficient code.

**Comment by wchargin** [comment]
> I decided to test the performance.

Sweet; thanks!

> `      let id = $`{r/p/i}`;`

What's this? It evaluates to `undefined`, because `$` is not a tag function. Did you mean `let id = `${r}/${p}/${i}`?

On your original code, I get the following:
```
wcharginGet: 302.1630859375ms
stringifyGet: 2653.994140625ms
```

With this modification, I get:
```
wcharginGet: 259.894775390625ms
stringifyGet: 3873.736083984375ms
```
My profiling isn't super precise—I've got other processes running—but there seems to be a clear difference in the `stringifyGet` due to actually needing to stringify meaningful content.

I also made a jsperf based on your code. It shows wcharginGet to be approximately 12× faster, with 3948 get-all operations per second for `wcharginGet`, and 319 for `stringifyGet`:

![JSperf results](https://user-images.githubusercontent.com/4317806/36962194-689bd172-2003-11e8-880b-b0ed746b2862.png)

You can try it on your machine here: https://jsperf.com/address-string-302039074
