### ISSUE TITLE
GitHub Migrations API

### ISSUE THREAD

**Issue by mikeal** [sourcecred/sourcecred#694]
Wanted to make sure this was on your radar. It was announced recently along with Facebook and Google and a few other companies branding their GDPR compliance as new features :)

https://developer.github.com/v3/migrations/

It's basically a full export of all the data. An alternative to trying to constantly sync w/ GraphQL would be to have a user authenticate access to the relevant repos, subscribe to all hooks and events, and then kick off a migration for all the historical data. Then you'd have the full dataset without the need to continue syncing and new data would flow to you in realtime.

**Comment by decentralion** [comment]
Thanks for posting. I think for now we'll keep using the v4 api, but we'll keep this approach in mind if we start to roadblock.
