### ISSUE TITLE
Explicitly require a GNU environment

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#698]
Follow-up to #594, #602, etc.

I’m temporarily developing on macOS.

Based on this experience, I humbly but strongly suggest that we make a
short-term policy to only support GNU-style systems.

In principle, I have nothing against supporting every POSIX-compliant
system under the sun. But when your `xargs` doesn’t have `-0` and your
`readlink` doesn’t have `-f`, at some point I stop writing interesting
graph algorithms and start maintaining a menagerie of hacks to try to
convince the command-line primitives to behave. This is not something
that I am interested in doing.

macOS users can prod Homebrew (ugh) into cooperation by doing one of the
following, depending on versions:

  - `brew install coreutils --default-names`;
  - `brew install coreutils --with-default-names`;
  - `brew install coreutils` but then add something like
    `/usr/local/opt/coreutils/libexec/gnubin/` to the very front of your
    path;
  - whatever Homebrew decides to switch to next month.

**Comment by decentralion** [comment]
I'm biased strongly against this suggestion, as a lot of people develop on
Macs, and I want to welcome them as contributors. Telling them we don't support
their machine as a development environment is pretty un-welcoming.

But perhaps you can help me understand. You suggest a short-term policy—why
would this be short term? If we are going to support them eventually, what
benefit do we accrue by kicking the can down the road, except for allowing more
technical debt to accumulate?

**Comment by wchargin** [comment]
> Telling them we don't support their machine as a development
> environment is pretty un-welcoming.

The fact is that we _don’t_ currently support them. You and I both
develop on GNU/Linux. Our scripts require standard GNU/Linux tools, some
of which simply don’t have the right interface on macOS. For context, I
opened this issue because our static site building script does not work
on vanilla macOS because `readlink` does not support `-e` or even `-f`.
To give you an idea, even `readlink --version` is not supported!

  - Status quo: Require a GNU environment, but don’t document this.
  - Easy solution: Require a GNU environment; document this, and point
    Mac users to instructions on how to set up their dependencies.
  - Hard solution: Take pains to ensure that our scripts run in any
    POSIX environment, or at least on both macOS and GNU/Linux.

The status quo is certainly the _most_ unwelcoming to new contributors,
so it seems clear to me that we should not continue along this path.

The easy solution enables us to work on the interesting work. To be
clear, we are not shooing Mac users away; we are teaching them how to
set up dependencies, just as any project does: [tensorflow], [numpy],
[blender] all have specific instructions for macOS users. It comes with
the territory.

[tensorflow]: https://www.tensorflow.org/install/install_sources#prepare_environment_for_macos
[numpy]: http://scipy.github.io/devdocs/building/macosx.html
[blender]: https://wiki.blender.org/wiki/Building_Blender/Mac

If we choose the hard solution, then instead of focusing on how to
structure the build script, I have to spend time doing things like
[reimplementing `readlink`][1], jumping through hoops to avoid using the
`-z`/`-0` options on standard command-line tools, fiddling with embedded
Python scripts or C programs, etc. This is simply not a good use of my
time or yours.

[1]: https://stackoverflow.com/a/1116890/732016

> But perhaps you can help me understand. You suggest a short-term
> policy—why would this be short term? If we are going to support them
> eventually, what benefit do we accrue by kicking the can down the
> road, except for allowing more technical debt to accumulate?

We don’t currently have any macOS users. If we try to support macOS
without any users, issues will inevitably slip through the cracks. If we
wait until people actually need this support _and_ are not willing to
install GNU coreutils for whatever reason _and_ we want to accommodate
that, then we are in a better position to make sure that our code stays
correct and free of technical debt.

It is also much more logistically convenient. I expect that enforcing
macOS compatibility would significantly decrease my productivity, not
least because I would have to test everything on both macOS and
GNU/Linux, which is not conducive to our short-term, time-sensitive
goals. Once we have more development momentum, we can put resources
toward this problem if you like.

The technical debt that we accrue from these changes is low-interest.
The changes that need to be made are all local, self-contained, and
incremental.

You said something the other day about being careful not to spend too
much time doing everything right. I think that this is a perfect example
of an instance in which practicality beats purity.

**Comment by decentralion** [comment]
Thanks for making the case so clearly and cogently. I'm persuaded. Please update the documentation at your leisure.

**Comment by wchargin** [comment]
# about: coreutils on macOS

SourceCred requires that your system provide GNU coreutils. By default,
macOS provides BSD-like coreutils. SourceCred is not tested with these
coreutils and is unlikely to work without a large number of small
changes.

## What?

Coreutils are programs like `mkdir`, `stat`, `ln`, etc. that are used
commonly in shell programs. POSIX specifies a minimal set of
functionality for these programs. The GNU implementations have
additional functionality, which SourceCred depends on.

To use SourceCred on macOS, you’ll need to install the GNU versions of
coreutils.

To check whether your system is set up correctly, check that `stat`,
`readlink`, `sed`, and `awk` indicate that they are provided by GNU:

```shell
$ stat --version | head -n 1
stat (GNU coreutils) 8.30
$ readlink --version | head -n 1
readlink (GNU coreutils) 8.30
$ sed --version | head -n 1
sed (GNU sed) 4.5
$ awk --version | head -n 1
GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.1, GNU MP 6.1.2)
```

## How?

Homebrew users may find that the following command works:

```shell
brew install --with-default-names \
    coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt
```

You may also need to add `/usr/local/opt/coreutils/libexec/gnubin/` to
the _front_ of your `PATH` in your `.bash_profile`:

```sh
export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
```

If this information is out of date, perhaps check to see if [this Stack
Exchange answer][se-answer] has more up-to-date information.

[se-answer]: https://apple.stackexchange.com/a/69332/81205

Please feel free to ping @wchargin on this thread if this information
becomes stale.

## Why?

In the long run, we’d like to support vanilla macOS, without this
requirement. There are two obstacles standing in our way:

  - The primary SourceCred maintainers don’t use macOS. As a
    consequence, we don’t have an easy way to test changes on macOS
    systems.

  - Developing and testing everything on two systems requires a
    nontrivial amount of effort, and simply is not high on our current
    priorities.

Patches to reduce dependencies on GNU utilities that also make the code
better overall (e.g., #602) will be appreciated!

For more details, see earlier conversation on this issue.

**Comment by decentralion** [comment]
Dear mac users reading this thread: please let us know how this is affecting you! You can post, or:
- if you want us to work on fixing this soon, react with :+1: 
- if the status quo is fine and its nbd, react with :laughing:

**Comment by s-ben** [comment]
Got this working on mac (Mojave, 10.14) by just running `brew install coreutils`.

**Comment by decentralion** [comment]
Some notes on how I got this working on my (brand new) macbook; I intend to update the README with these steps in the future:

- installed [nvm](https://github.com/nvm-sh/nvm)
- installed node v8: `nvm install 8`
- setup node v8 `nvm use 8`
- installed yarn `brew install yarn`
- at this point, running `yarn` inside sourcecred produced a bunch of `better-sqlite3`-related warnings and errors. i fixed these via `npm install -g node-gyp`
- then, `brew install coreutils`
the `--with-default-names` flag that @wchargin mentioned wasn't available, so I manually updated my `.zshrc` with the new path component that `brew` told me to use
- after these steps, `yarn test` passed
- i got a no-permissions GitHub api token and updated my `.zshrc` to export it as `SOURCECRED_GITHUB_TOKEN`
- at this point, `yarn test --full` passed.

**Comment by blueridger** [comment]
I got this error as a result of a catalina upgrade:
gyp: No Xcode or CLT version detected!

Solved by uninstalling and reinstalling xcode command line tools.
https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d

**Comment by mkusold** [comment]
> Some notes on how I got this working on my (brand new) macbook; I intend to update the README with these steps in the future:
> 
> * installed [nvm](https://github.com/nvm-sh/nvm)
> * installed node v8: `nvm install 8`
> * setup node v8 `nvm use 8`
> * installed yarn `brew install yarn`
> * at this point, running `yarn` inside sourcecred produced a bunch of `better-sqlite3`-related warnings and errors. i fixed these via `npm install -g node-gyp`
> * then, `brew install coreutils`
>   the `--with-default-names` flag that @wchargin mentioned wasn't available, so I manually updated my `.zshrc` with the new path component that `brew` told me to use
> * after these steps, `yarn test` passed
> * i got a no-permissions GitHub api token and updated my `.zshrc` to export it as `SOURCECRED_GITHUB_TOKEN`
> * at this point, `yarn test --full` passed.

These instructions are a bit clearer and easier to follow (not to mention it involves installing less stuff). Can we consider updating the main "What, How, Why" comment with these instructions instead? 

As an insight into new dev onboarding -- I was following the README to get setup, was directed towards that main "What, How, Why" comment, and tried following that immediately instead of reading through this whole thread. Since it marked the PATH addition as optional, I didn't do it and therefore it didn't work. I think all Mac users will have to update the PATH to get this to work, so it'd be nice to be more clear that it isn't optional. Additionally, I appreciated the note on how to test that the installation is successful via the `yarn test` command.
