### ISSUE TITLE
Server-side render the cred attribution

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#703]
Right now, we don't run PageRank on the backend, or provide pre-rendered cred results on the cred explorer load. This means that users need to run PageRank on their own machines before seeing any results. 

As of 0.0.2, when projects are publicly posting their cred attributions, this will be a bad user experience - visitors should be able to see the cred, according to the project's canonical weights, immediately without needing to run PageRank themselves. This will reduce user confusion, and also be better for people with slow CPUs or visiting on mobile. 

To improve this, we should SSR the cred explorer results. Power users who want to tweak the weights and re-run will still be able to do so. This change will have some implications around e.g. storing weights in localStore, and might make the power user experience slightly less convenient, but I think it's actually a good thing. Storing weight tweaks in localStore makes the experience less reproducible and means that different people may see different cred without realizing why.

**Comment by decentralion** [comment]
Here's a proposal for what gets included with the server side render:

When the page loads, it comes bundled with every user's cred, and every connection that contributed to every user's cred. Then, when the page loads, the UI works normally as you explore where each user got their cred from. However, once you get down to the individual connection level (e.g. REFERENCES pull 703), you can't expand down to the node until you load the data. 

This way, on page load, you immediately have a workable UI that covers ~90% of regular behavior, i.e. checking out the leaderboard and doing some basic exploration. Once you want to get super far into it, then you need to load the whole graph.

We could consider doing the same thing for issues and pulls (or for top 100 issues and pulls).

**Comment by Beanow** [comment]
The current solution in TimelineCred is to run Timeline PageRank ahead of time and read summarized data in the frontend. Needing only the recalculate when changing parameters.

I think this covers the use-case for this issue. Suggest picking up further improvements when we rework the UI again.
