### ISSUE TITLE
Make `RelationalView#addData` safer

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#712]
In the current codebase (as of a5c909689a68b), the `RelationalView`
method exposes a public function `addData`. It is safe to call `addData`
multiple times with responses from different repositories each time, and
we do so in #711. But calling `addData` with a partial response
corresponding to a repository that already exists in the view can
silently put the view into an inconsistent state.

A comment in the code currently disclaims this, but it’s still a bit of
a ticking time bomb. As we write functionality like
incremental/resumable loading, we’re more likely to be bitten by it. We
should fix the underlying problem in some sane way or
other—@decentralion will know best.

**Comment by decentralion** [comment]
Superceded by #1539
