### ISSUE TITLE
Add webpack to Node backend

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#74]
We can’t use ES6 modules with our backend scripts, because we refuse to
acquiesce to the the `.mjs` autocracy that Node is trying to impose.
We’ve been using the old `module.exports` system, but this doesn’t let
us import and export Flow types. We’re certainly going to want to set up
Webpack eventually, so... we should do that.

cc @dandelionmane

**Comment by dandelionmane** [comment]
This was fixed by @wchargin  in https://github.com/sourcecred/sourcecred/pull/84

**Comment by wchargin** [comment]
> we refuse to acquiesce to [the] `.mjs` autocracy that Node is trying
> to impose.

I am vindicated: `create-react-app` is removing support for `.mjs`. :+1:
