### ISSUE TITLE
Build broken by #715

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#752]
Looks like #715 broke `yarn sharness-full`. Here's a [representative failure]. I identified #715 as the source of the breakage via `git bisect`.

[representative failure]: https://travis-ci.org/sourcecred/sourcecred/builds/423743442#L475

**Comment by wchargin** [comment]
My fault; will fix.

This did not show up in my testing because it actually does pass on Mac.
But that’s only because Mac has a broken version of `sh`. I’d used a
Bash-specific feature that properly fails on Linux.

I don’t have any cron failure emails from Travis. Do you?

**Comment by decentralion** [comment]
No, I didn't get any emails either.

**Comment by wchargin** [comment]
Thanks for bisecting and finding this!

We might want to fix the cron failure email situation (again…).
