### ISSUE TITLE
Consider using Greenkeeper to keep Flow and Prettier up to date

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#793]
Website: <https://greenkeeper.io/>. Free for open-source projects.

We like to keep Flow up to date because it is reasonably common for a
Flow upgrade to introduce breaking changes, and dealing with these
incrementally is much easier than dealing with them all at once.

The case for Prettier is similar.

Greenkeeper would automate the process of creating PRs like #791. An
example Greenkeeper pull request is here:
<https://github.com/MetaMask/metamask-extension/pull/5047>

We could of course use Greenkeeper for other dependencies, too.

**Comment by Beanow** [comment]
Are using it, thanks :]
