### ISSUE TITLE
Enable setting weights to 0

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#811]
Right now, the lowest a weight can go is `1/32`. We should be able to set weights explicitly to 0.

Rather than add an additional UI element, I think we should just change the leftmost extreme of the slider to signify 0. (This will make the slider a little less consistent—it will no longer always move in powers of 2—but I think that's OK.)

**Comment by wchargin** [comment]
Changing the leftmost extreme of the slider is fine with me. Adding a
separate checkbox would also be fine with me.

Will the options be [0, 1/32, …, 32], or [0, 1/16, …, 32] (or
equivalently [0, 1/32, …, 64])? The former has log-symmetric nonzero
range (plus −∞), while the latter has the nice property that 0 is
centered horizontally.

**Comment by decentralion** [comment]
This was fixed by #1005.
