### ISSUE TITLE
Re-license SourceCred to MIT + Apache 2

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#812]
@ianjdarrow has done some research into open-source licensing and determined that dual-licensing as MIT and Apache 2 is a best practice. Quoting from his writing elsewhere:

> This has two major benefits:
> 
> - There are concerns in the open source community about whether the MIT license leaves users vulnerable to patent infringement claims. We think the pure legal risk is small, but the way the open source community interacts with our project is really important. It makes sense to pick the license that makes the largest number of people comfortable.
> - There's now no reason to adopt a separate [DCO](https://developercertificate.org/), since the Apache-2 license grant addresses the same issue.
>
> Why use a dual license, instead of just Apache-2? The Apache-2 license is incompatible with the GPLv2 license, which includes things like the Linux kernel. With a dual license, GPLv2 projects can just use the MIT license instead. Our goal is to make our software available to as many projects as possible, so we'd rather adopt a licensing scheme that doesn't exclude anyone.

The first step is to get explicit OK from our current contributors. I consent to the relicensing.
@wchargin and @claireandcode can you comment expressing whether or not you approve to additionally licensing your contributions under Apache 2?

**Comment by wchargin** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by claireandcode** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by wchargin** [comment]
Thanks @claireandcode ! I will update the license accordingly.
