### ISSUE TITLE
give better diagnostic info when loading many repositories

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#852]
When loading many repositories using `sourcecred load --output`, if any repository fails, it can be very difficult to trace which particular repo triggered the issue. Also, it's hard to guess how far into the process SourceCred is.

Some feature requests:
- [ ] when a failure occurs, print the name of the failure-inducing repository
- [ ] when loading multiple repositories,  print info on each successful plugin load so the user can see how fast the process is going

**Comment by wchargin** [comment]
Unassigning. These would be nice, but I have more important things to
work on and don’t want to give the impression that I’m prioritizing
this.

**Comment by dfield** [comment]
@decentralion what are some known failure cases?

**Comment by wchargin** [comment]
We can also fail if the user has hit their rate limit on the GitHub API
(this logic is in `fetchGithubRepo.js`). This is really quite rare,
though, as the quota is refilled hourly and we don’t make an exorbitant
number of requests. I think it’s happened once.

Other failure cases are usually bugs in SourceCred. In the past, we’ve
failed when a repository contains a comment from a user whose account
has been deleted, or when a repository has a dot in its name (valid in a
repo name but not a username), or when a repository has no Git commits
and so `git rev-parse HEAD` fails. It’s unfortunate if a bug like this
occurs half an hour into loading a list of 30 repositories, and we don’t
know which one caused the failure.

**Comment by decentralion** [comment]
What William said basically. I mostly see failures when I'm changing the graphQL query and don't have the continuations quite right.

**Comment by Beanow** [comment]
With the task reporter and `--project` style loading, think we have better feedback now :smile:
Feel free to reopen otherwise.
