### ISSUE TITLE
Create a Discourse Plugin

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#865]
Today, SourceCred gets data from two [plugins]: the git and github plugins.

[plugins]: https://github.com/sourcecred/sourcecred/tree/master/src/plugins

The plugins load data from Git and GitHub, and map that data into a [graph] showing how contributions in the domain are interrelated. 
Contributions, like Git commits or GitHub pull requests, become nodes in that graph, and relationships between them (authorship, references, etc) are edges.

[graph]: https://github.com/sourcecred/sourcecred/blob/master/src/core/graph.js

SourceCred uses [Discourse] for its community forum, available at https://discourse.sourcecred.io.
We should add a third plugin, the Discourse plugin, which loads data from arbitrary Discourse instances.

[Discourse]: https://www.discourse.org/

To start, it should have the following nodes and edges:

**Nodes:**
- USER, a Discourse login identity
- THREAD, a top-level thread
- POST, an individual pots in a thread (including the first message in the thread)
- CATEGORY, a Discourse category of threads

**Edges:**
- AUTHORS, user authors a post or thread
- REFERENCES, a post references a user, thread, or post (via url or @-refernece)
- QUOTES, a post quotes another post (there's an explicit tag)
- CONTAINS, categories contain threads and threads contain posts
- LIKES, a user likes a post

This is a relatively involved undertaking; whoever decides to do this, please
feel free to drop by our [Discord](https://sourcecred.io/discord-invite) to
chat about how the architecture works.

**Comment by decentralion** [comment]
Closing, because we aren't making active use of Discourse atm.

**Comment by decentralion** [comment]
I spent a bit of time today looking at the [discourse API](https://docs.discourse.org/).

Some thoughts:
- Getting data from the API requires a key to be created by the forum maintainers. This means, in contrast to GitHub, it will be impossible to generate cred for a Discourse forum without explicit buy-in from the admins
- There doesn't seem to be any way to scope API keys with specific permissions, so they're quite sensitive. We should be careful with these.
- The [Topics api](https://docs.discourse.org/#tag/Topics) has endpoints for getting recent topics and top topics, but not for getting all topics. This could be a problem, except:
- There's a [get Topic](https://docs.discourse.org/#tag/Topics%2Fpaths%2F~1t~1%7Bid%7D.json%2Fget) API by integer ID, and looking at our instance, it appears that the topics are assigned incrementing ids, starting at 1. So we could retrieve all the topics by getting the latest id, and then iterating from 1 to the latest id
- Similarly, while there is no method to get all the posts on a topic, the posts have incrementing integer ids, and we can get a post for a topic by id
- Much like the GitHub plugin, we should cache the results locally to avoid needing to download everything every time we re-run sourcecred. I think using sqlite again to build the cache will make sense. This time, I expect we will have the graph get generated directly from the sqlite cache rather than going through an extra layer of indirection.
- It would be helpful if Discourse is willing to give us a free instance to use as a test discourse, which has a few canonical posts and replies and which we can use for E2E snapshot testing. Much like [example-github](http://github.com/sourcecred/example-github)
- We should take some care to make sure that SourceCred doesn't leak details about private posts. The simplest way to do this would be to simply skip all topics that have the `"visible": false` set.

**Comment by decentralion** [comment]
We now have a test discourse instance: https://sourcecred-test.discourse.group/. Thanks @erlend-sh!

**Comment by jakubgs** [comment]
Is the plugin currently ready to use or does it still need some work?

**Comment by decentralion** [comment]
I would say it's ready to demo. There are a few pieces of outstanding work:
- add an option to load a discourse server from the command line
- detect mentions (e.g. `@username`) and references (link to another post or topic) and add edges
- add a way to do identity resolution between GitHub and Discourse, for projects (like SourceCred) that will use both together.

**Comment by vsoch** [comment]
Have you worked with Discourse before? It’s a complete beast! What do you mean by having sourcecred start a discourse server?

**Comment by decentralion** [comment]
@vsoch the Discousre plugin loads all the public posts / topics, creates nodes and edges representing them, and then creates cred based on that data. You can see a [demo here](https://discourse.sourcecred.io/t/sneak-peek-sourcecred-discourse-plugin/171). 

SourceCred (the project) makes extensive use of Discourse, so it's important that we are able to give cred based on activity there. I view it as a [requirement](https://discourse.sourcecred.io/t/discourse-from-day-1/185) before we [start the CredSperiment](https://discourse.sourcecred.io/t/introducing-the-credsperiment/183) and start paying people based on cred.

**Comment by vsoch** [comment]
oh I see - @decentralion is a plan in the works to eventually add the widgets to produce the grid / svg of contributors? I think I've seen something similar on discourse, but I just searched around and I can't find it now (I'll post it if I eventually do).

If you need another tester, our [discourse](https://ask.cyberinfrastructure.org/) also has a staging site, and I would definitely be excited to add something like sourcecred. I'll watch this issue for updates!

**Comment by jakubgs** [comment]
Could you provide some instructions on how to install it? I assume it's different from how most plugins are installed, which is by adding a `git clone` command to the `hooks` and `after_code` section of YAML configuration file.

**Comment by wchargin** [comment]
> I assume it's different from how most plugins are installed, which is
> by adding a `git clone` command to the `hooks` and `after_code`
> section of YAML configuration file.

Perhaps there’s some confusion—we’re not talking about a plugin that you
add to a Discourse server. We’re talking about a plugin _to SourceCred_
itself that happens to fetch data from Discourse using an API key.

**Comment by jakubgs** [comment]
Oh, that makes it clearer, thanks.

**Comment by vsoch** [comment]
Oh this makes so much more sense! Yes, I was thinking you were talking about an actual [Discourse Plugin](https://www.discourse.org/plugins), but it's the other way around :)

A cool [recent update](https://meta.discourse.org/t/discourse-2-4-0-beta3-release-notes/127600) (since sourcecred uses Discord) is that DIscourse now supports Discourse login. So you can discuss your Discourse topics on Discourse logging in with Discord! That doesn't sound confusing for a new person at all :P

**Comment by jakubgs** [comment]
So how would one go about using this plugin? In case of GitHub we specify the `SOURCECRED_GITHUB_TOKEN` env variable, what do we have to specify in case of Discourse?

**Comment by vsoch** [comment]
This is just a guess, but I'd say that sourcecred would [generate an api token](https://meta.discourse.org/t/how-to-create-an-api-key-on-the-admin-panel/87383) and then use [endpoints](https://docs.discourse.org/) to get users, collect metrics about contributing to the board, and then generating the plots / output.

**Comment by Beanow** [comment]
Is this issue resolved? It's marked as needing help on https://github.com/sourcecred/ by the "good first issue" label.

**Comment by decentralion** [comment]
Sorry @jakubgs, I missed the notifications for your comments asking how to use the plugin. You can take a look at this PR for instructions: https://github.com/sourcecred/sourcecred/pull/1374

@Beanow yeah I'll close this.
