### ISSUE TITLE
Consider using CircleCI instead of Travis

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#902]
I’ve observed recently that CircleCI builds for other projects are quite
fast.

From brief forays into CircleCI (see #901 and friends), it seems that
our CircleCI builds complete in always under a minute. It takes 30
seconds after the CircleCI build finishes for the Travis build to even
_start_ (“Hold tight, the log cannot be shown until the build has
started”), then some more time to get past the updating Heroku and
updating NVM steps.

Part of this is due to CircleCI’s caching of `node_modules`. To
establish a fair test, I enabled `cache: yarn` on Travis as well. Here
are the results:

**CircleCI**

  - 17:09:24: commit received by GitHub after local `git push`
  - 17:09:29: CircleCI job begins
  - 17:09:48: CircleCI job invokes `yarn test`
  - 17:10:06: CircleCI job done
  - time spent in `yarn test`: 18 seconds
  - total elapsed time: 42 seconds

**Travis**

  - 17:09:24: commit received by GitHub after local `git push`
  - 17:10:06: Travis job is still “booting”, showing no log data
  - 17:10:45: Travis job begins
  - 17:11:20: Travis job finishes updating Heroku and NVM, begins unpacking cache and running `yarn`
  - 17:12:37: Travis job invokes `yarn test`
  - 17:13:38: Travis job finishes
  - time spent in `yarn test`: 61 seconds
  - total elapsed time: 4m14s

It bears noting that CircleCI’s caching behavior seems faster in
principle: it caches `node_modules`, while Travis seems to cache just
the downloaded package files but still requires running `yarn` from
scratch. CircleCI still runs `yarn` for safety, but it takes 1.16s
because Yarn only has to check that everything is up to date. It’s
plausible that we could replicate this caching behavior on Travis, even
though the recommended config key `cache: yarn` does not do this.

Even so, however, the Travis worker is clearly much slower than the
CircleCI worker. Just running `yarn test` after all the cache work is
done takes longer than the entire end-to-end process for CircleCI! So
even perfect caching would still leave Travis far behind.

Empirically, it is not uncommon for a reviewer to refrain from
submitting a minor suggestion, or for a PR author to ignore such a
suggestion, because implementing the suggestion would require another
4-minute Travis cycle (and human context switch). If we had a 42s build
cycle, instead of a 4m14s build cycle, then I at least would be much
happier to make such changes. This would also help with merging stacks
of dependent PRs: even a short stack in Travis is annoying when you have
to wait 4 minutes between rebasing onto master and merging the
post-build commit.

The only thing blocking us from using CircleCI, once #901 is merged, is
that our cron jobs still run on Travis. CircleCI [does have support for
cron jobs (“scheduled workflows”)][cron]. So, given these promising
data, I think that I’ll port our cron job over to CircleCI, after which
we can drop support for Travis.

[cron]: https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow

**Comment by decentralion** [comment]
Thank you for doing this research! This is a very significant improvement.

**Comment by wchargin** [comment]
I’ve configured CircleCI with GitHub API tokens linked to my personal
account, just to get us unblocked. Could you please update this config
to use tokens from the @sourcecred-ci account?

<https://circleci.com/gh/sourcecred/sourcecred/edit#env-vars>

**Comment by decentralion** [comment]
> I’ve configured CircleCI with GitHub API tokens linked to my personal
> account, just to get us unblocked. Could you please update this config
> to use tokens from the @sourcecred-ci account?
> 
> https://circleci.com/gh/sourcecred/sourcecred/edit#env-vars

Done

**Comment by wchargin** [comment]
Great; thanks. Let’s give it a day or two to make sure that everything
is working as intended (including cron) before dropping Travis.

**Comment by wchargin** [comment]
Cron integration appears to be working: <https://circleci.com/gh/sourcecred/sourcecred/20>

I’ll add a badge to the README, then we can look into disabling Travis.
