### ISSUE TITLE
Spurious reference detection inside code blocks

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#903]
Consider the following pull request: https://github.com/ipfs/js-ipfs-block-service/pull/36

It has numeric references inside code blocks (e.g. `#62`). Per documentation [here] the numeric references should not be considered, as they are in code blocks. However, they do in fact get detected. See image below for an example.

Relevant: https://github.com/sourcecred/sourcecred/issues/432

[here]: https://github.com/sourcecred/sourcecred/blob/163b2c137757a16b2dce7324660e24410cf5540e/src/plugins/github/parseMarkdown.js#L9
![image](https://user-images.githubusercontent.com/1400023/46324208-3093c100-c5a7-11e8-951a-675ba6cc2dfd.png)

**Comment by wchargin** [comment]
The source post does not use Markdown `` `inline code` ``. Instead, it
uses HTML `<code>code elements</code>`. We treat all the contents of all
HTML elements as normal text.

Would you like to implement a pass to remove the contents of any HTML
`code` element?
