### ISSUE TITLE
Make Mirror robust to input data with incorrect `__typename`s

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#998]
It has come to our attention that the GitHub API occasionally returns
results that are internally inconsistent, in that a node’s returned
`__typename` can be incorrect, and nodes can appear in places where they
are disallowed by the schema. The instances in which we know that this
can occur are documented in #996.

This issue describes a proposal for a way to cope with this incorrect
input data, without changing the direct public API of the Mirror module,
without changing the spirit in which it operates, and with only a local
performance impact. This proposal does not require making any Mirror
functions asynchronous or performing any cross-cutting external queries.

## Assumptions

Since it has become clear that the GitHub API is sometimes simply wrong,
we should be clear and explicit about our assumptions. Until now, we
have made the following assumption:

> Whenever the `id` and `__typename` of a `Node` are selected, the node
> with that ID will always have the same `__typename`, in all contexts.

This is implied by [§3 of the Relay Global Object Identification
Specification][relay-spec] and [GitHub’s own docs][github-docs], but it
is unfortunately clear that this assumption is false.

We relax our assumption to the following:

> Whenever a `Node` is queried by `id` via [the `node` field of the
> top-level `Query` object][node-field] or the `nodes` field on the same
> object, the returned `__typename` is the same.

In other words, a node’s type is well-defined, is constant, and has an
effective source of truth.

[relay-spec]: https://facebook.github.io/relay/graphql/objectidentification.htm#sec-Node-root-field
[github-docs]: https://developer.github.com/v4/guides/using-global-node-ids/#2-find-the-object-type-in-graphql
[node-field]: https://developer.github.com/v4/query/#node

This _is_ consistent with our observations. Note, for instance, that
even [when a user transforms into an organization, the node’s ID
changes][id-change]. Note also that GitHub’s IDs are base64-encoded
strings of the form `` `${int}:${graphqlTypename}${databaseId}` ``\*,
like:

```shell
$ ghquery '{ user(login: "wchargin") { id } }' | jq -r .data.user.id | base64 -d
04:User4317806
```

Of course, IDs must be treated as opaque—we cannot try to construct them
ourselves—but we can use them to infer implementation details about
GitHub’s systems. In particular, the fact that the node typename is
encoded directly into the ID, together with the fact that the GitHub
schema does not have any typenames that end with a decimal digit…

```shell
$ ghquery '{ __schema { types { name } } }' |
> jq '.data.__schema.types | map(.name | select(test("[0-9]$")))'
[]
```

…is sufficient to imply our assumption.

\* The meaning of the leading integer in the base64-decoded IDs is not
clear. It appears to be determined by the typename, but not vice versa:
`Bot` and `Ref` both have `03`, `Issue` and `Label` both have `05`, and
`IssueComment` and `Organization` both have `012`. (We mention this only
for completeness.)

[id-change]: https://github.com/wchargin/ghost-playground/issues/2#issuecomment-435236022

## Proposal

We propose that the following changes be made:

  - Allow marking node reference and connection fields as having
    “untrustworthy `__typename`” in the schema.
  - Change the `typename` column of the `objects` SQLite3 table to be
    nullable.
  - When receiving own data or connection entries for a field of
    untrustworthy typename, register the object by ID, but do not record
    its typename (leave it `null`).
  - When checking for outdated objects, identify any objects with null
    typename. Query these objects by node ID, and request only their
    typenames.
  - In the schema, when specifying a node reference or connection field,
    allow specifying the known set of _actual_ element types (which may
    be more than just the declared element type), and update the Flow
    type generation accordingly.

This is a major version change to the Mirror module (i.e., the version
string in `_initialize` will need to be bumped).

Note that when we say “node reference or connection field” we also
include occurrences of these fields as “eggs” in nested fields, such as
`Commit.author.user` (which is in fact untrustworthy).

Note that it would suffice to consider _all_ fields as implicitly
untrustworthy, fetching each node’s typename explicitly. The restriction
to an explicit set of untrustworthy fields is for performance: querying
every node’s typename requires extra sequential queries proportional to
the number of objects in the database.

Treating all fields as untrustworthy could incur a significant
performance hit. For instance, the twbs/bootstrap repository has
197&thinsp;708 objects as of 2018-10-31T23:23:38-07:00; with a
`nodesLimit` of `100` (the current default), this would require at least
1978 additional queries, and probably more due to sequencing constraints
(if node **B** is only reachable as a field of node **A**, then you have
to ask for node **A**’s typename strictly before node **B**’s). Fetching
this repository required a total of 2252 queries as is, so we would be
looking at a 1.9× increase in query count.

Note also that we only need to fetch the typename once per node, not
once per reference. If a user reacts to 10 issues, we only need to fetch
their typename once. This is sufficient because of our assumption about
the stability of typenames.

Note that we may still of course incur database corruption if there is a
field that is untrustworthy that we do not know about. It would be nice
if we could improve the debugging experience around such cases. For
instance, logging every query as it is sent out (and before the results
are processed) could make it easier to identify the offending data
without having to rebuild a special debugging version of SourceCred.

## Implementation plan

This requires a code-compatible, data-incompatible change to the
`graphql/schema.js` API. Code that defines schemata under the old module
will continue to work under the new module, with the same semantics, but
the schema representation will have changed (new schemata may have
attributes like `untrustworthy: false` or equivalent).

This requires a code-compatible, data-incompatible change to the Mirror
API. The public functions exposed by the module do not change in
interface at all. The structure of the backing SQLite3 databases will
change, so existing databases will be invalidated. (Existing databases
will also have been invalidated due to the data format change of the
schemata.)

This does not require adding any kind of cross-cutting concerns to the
Mirror module. In particular, it should still be easy to write good,
complete tests for the new code.

After implementing this proposal, we will be able to clear the existing
set of blacklisted IDs, which was a temporary stopgap measure superseded
by this proposal. We may wish to keep the blacklisting functionality
there in case we run into new classes of problems and need a quick fix.
We could also remove it. (I would probably keep it in, but have no
strong preference.)

## Alternatives considered

This section discusses potential alternatives and the reasons for which
we decided not to use them.

### Unilateral schema changes

It is not possible to simply change our local version of a schema to use
broader types for the offending fields. For instance, we cannot change

```js
    Reaction: s.object({
      id: s.id(),
      content: s.primitive(s.nonNull("ReactionContent")),
      user: s.node("User"),
    }),
```

to

```js
    Reaction: s.object({
      id: s.id(),
      content: s.primitive(s.nonNull("ReactionContent")),
      user: s.node("Actor"),
    }),
```

even though this more closely matches what actually is returned. With
the latter version of the schema, we would query a reaction’s own-data
with a selection set like

```graphql
{
  __typename
  id
  content
  user {
    __typename
    ... on User { id }
    ... on Organization { id }
    ... on Bot { id }
  }
}
```

where the casing is necessary because the `Actor` interface does not
expose an `id` field, even though all of its implementations do. But the
above query is invalid according to the GraphQL type system, because the
declared type of `Reaction.user` is `User`, so the inline fragment with
type condition `Organization` is statically detected as “unreachable”
per [§5.4.2.3 of the GraphQL spec][graphql-5.4.2.3].

[graphql-5.4.2.3]: https://facebook.github.io/graphql/October2016/#sec-Fragment-spread-is-possible

### Exceptional handling of exceptional cases

Another alternative would be to treat all fields as sound by default,
but attempt to recover better when we find ourselves in an inconsistent
state. If we ever have inconsistent type information for a node, we can
directly query the GitHub API to “resolve the dispute”, as it were,
asking for the `__typename` explicitly.

Note that there is not, in general, enough local information to resolve
the dispute unilaterally. In particular, if we have recorded that a
node’s type is `A`, and then GitHub tells us on a subsequent query that
it is in fact `B`, then it is not true that one of us is always correct:
it depends on whether the first buggy queries were made before or after
the first non-buggy ones.

The primary downside of this approach is that it dramatically changes
the structure of the Mirror API. Currently, most of the internals of the
Mirror API are purely functional except for DB mutations. Functions
_emit_ queries (they do not _post_ them), and other functions take as
input the results of queries. With this change, any function that
ingests data would need to have the ability to directly query a remote
API. Such functions would also necessarily become asynchronous.

This change would also clearly _complicate_ the API, decreasing our
flexibility to address other kinds of problems in the future. We haven’t
been using the Mirror API in production for very long, so it’s possible
that there are entire classes of remote errors that we need to cope with
that don’t fit into this framework. If that turns out to be the case, it
will be easier to fix them in a simpler, more localized system than one
that can call out to a remote host at arbitrary points.

**Comment by decentralion** [comment]
I support this proposal, and am happy to implement it (so as to effect knowledge transfer re: the mirror module). It seems like a very clean way of resolving the class of problem we're encountering without complicating the contract overmuch or adding a bunch of hacks.

Once you've thought about this more and are reasonably confident in it, would you please write a high-level implementation plan (which pieces to change, etc) that I can use as a starting point?

**Comment by wchargin** [comment]
Yep, definitely. Thanks!

**Comment by wchargin** [comment]
There are two APIs that need to be defined: the actual schema data
types, and the public functions to construct those data types.
Everything else is mostly straightforward, at least at the interface
level.

The data type needs to encode the following information in, say, a node
reference field:

 1. the _de jure_ typename as specified by the remote schema;
 2. whether the field is untrustworthy; and
 3. the actual potential typenames.

(Item (1) is required for Mirror to know how to query a `__typename` on
unions. Item (2) is required for Mirror to know whether to query the
`__typename` immediately or pick it up on a subsequent query. Item (3)
is required to generate accurate Flow types.)

We could transcribe these requirements directly:

```js
export type NodeFieldType = {|
  +type: "NODE",
  +elementType: Typename,
  +untrustworthy: boolean,
  +actualTypenames: {|+[Typename]: true|},
|};
```

Note that we have the invariant that if `untrustworthy` is `false` then
the value of `actualTypenames` should be `{[elementType]: true}`, but if
`untrustworthy` is `true` then `actualTypenames` may be anything. We can
encode this invariant into the type:

```js
export type NodeFieldType = {|
  +type: "NODE",
  +elementType: Typename,
  +fidelity:
    | {|+type: "FAITHFUL"|}
    | {|+type: "UNFAITHFUL", actualTypenames: {|+[Typename]: true|},
|};
```

(I’ve switched from “trustworthy” vs. “untrustworthy” to “faithful” vs.
“unfaithful” because “trustworthiness” is a bit too awkward for my
tastes, and “fidelity” is IMO at least as clear).

Because this `fidelity` field is shared across node reference fields,
connection fields, and their eggy counterparts, we may extract it:

```js
// A field is _faithful_ if selecting its `__typename` and `id` will
// always yield the correct `__typename` for the node of the given ID.
// In theory, this should always be the case, but some remote schemas
// are broken. For details, see:
//
//   - https://github.com/sourcecred/sourcecred/issues/996
//   - https://github.com/sourcecred/sourcecred/issues/998
//
// For an unfaithful field, the `actualTypenames` property lists all the
// types of objects that can _actually_ be returned when the field is
// queried.
export type Fidelity =
  | {|+type: "FAITHFUL"|}
  | {|+type: "UNFAITHFUL", actualTypenames: {|+[Typename]: true|};

export type NodeFieldType = {|
  +type: "NODE",
  +elementType: Typename,
  +fidelity: Fidelity,
|};
export type ConnectionFieldType = {|
  +type: "CONNECTION",
  +elementType: Typename,
  +fidelity: Fidelity,
|};
```

As to the constructor APIs: it seems reasonable that the current form

```js
s.node("User")
```

should continue to be valid and refer to a faithful field. The best
shape for the API to describe unfaithful fields is less clear. Here are
some candidates:

```js
/* 1 */ s.node("User", s.unfaithful(["User", "Organization", "Bot"]))
/* 2 */ s.node("User", {actualTypenames: ["User", "Organization", "Bot"]})
/* 3 */ s.node("User", {unfaithful: ["User", "Organization", "Bot"]})
/* 4 */ s.node("User", {type: "UNFAITHFUL", actualTypenames: ["User", "Organization", "Bot"]})
/* 5 */ s.node("User", ["User", "Organization", "Bot"])
/* 6 */ s.node(["User", "Organization", "Bot"])  // bad
```

Of these, I prefer the first. We can export functions `faithful()` and
`unfaithful($ReadOnlyArray<Typename>)` that return `Fidelity` objects.
Then, the semantics of the optional argument is simply that it defaults
to `faithful()`.

Options (2) and (3) are fine, but require extra processing and introduce
another data type for no apparent benefit.

Option (4) is option (1) without the helper function—again, fine, but
the helper makes it nicer.

Option (5) is okay, but is not very clear in client code.

I’ve marked option (6) as “bad” because implicitly selecting the first
element of the list as the _de jure_ type means that the _de jure_ type
is required to be included in the set of actual typenames, and a priori
there is no reason that this should be required. (This also consequently
prohibits the `actualTypenames` set from being empty, which is never a
good sign.)

So, I suggest option (1).

**Comment by wchargin** [comment]
> would you please write a high-level implementation plan (which pieces
> to change, etc) that I can use as a starting point?

Sure. Give this a read and let me know what you think.

I’d suggest making the following commits:

 1.   - Add the `Fidelity` to the schema module.
      - Add fidelity fields to `NodeFieldType`, `ConnectionFieldType`.
      - Add `faithful` and `unfaithful` functions as described above.
      - Add appropriate validation in the `schema` function.
      - In the Mirror module, throw NYE (“not yet implemented”) if given
        any schema that transitively contains any unfaithful `Fidelity`,
        so that Mirror continues to behave correctly on all schemata
        that it accepts. (As in #916.)
      - In `generateFlowTypes`, similarly reject any such schema.
      - Note that this commit invalidates existing Mirror databases
        because the serialized schema types have changed, but that this
        does not require bumping the Mirror compat version.

 2.   - Change the Mirror `QueryPlan` type to include a `typenames`
        field, which is a list of object IDs whose typename to fetch.
      - Update `_findOutdated` to always return `[]` for this new
        field—which we know to be sound with the existing logic because
        of the `NOT NULL` constraint on the `typename` column in the
        `objects` table.
      - Update `_queryFromPlan` to throw NYE if `queryPlan.typenames` is
        not empty.

 3.   - Change the Mirror `UpdateResult` type to include a new clause,
        `TypenameUpdateResult`, which includes just `id` and `typename`.
      - Update `_FIELD_PREFIXES` appropriately.
      - Update `_updateData` to throw NYE if the new clause ever appears
        in its input.

 4.   - In the Mirror `_initialize` method, in the `objects` table
        declaration, remove the `NOT NULL` constraint from the
        `typename` column.
      - Add a `CHECK` constraint that if `last_update` is non-`NULL`
        then `typename` is non-`NULL`. (Grep for `CHECK.*end_cursor` for
        an example.)
      - Bump the Mirror compat version (`MIRROR_v3` → `MIRROR_v4`).

 5.   - Update `_findOutdated` to find any objects with `NULL`
        `typename` and include them in the `QueryPlan`. Note: in SQL,
        the expression `typename = NULL` always evaluates to false:
        specifically, to `NULL`. (`NULL`, like `NaN`, absorbs.) You want
        `typename IS NULL`.
      - You won’t be able to test this via the public APIs, because
        there is no way to use the public APIs to get rows into
        `objects` with null `typename`. To test this, manually insert
        the relevant rows.

 6.   - Update `_queryFromPlan` to handle the case where `typenames` is
        non-empty, generating an appropriate query:

        ```graphql
        { typenames_0: nodes(ids: [ ... ]) { __typename id } }
        ```

      - You may want to add `_queryTypename` in parallel with
        `_queryOwnData` and `_queryConnection`.
      - Decide what to do about the options to `_queryFromPlan`. You
        MUST respect the cap of 100 on the `ids` argument to the `nodes`
        field. You MAY reuse the `nodesOfTypeLimit` parameter for this
        purpose, or you MAY add an additional parameter. You SHOULD
        respect a maximum on the total number of nodes whose typenames
        to fetch; up to you whether to include these in the `nodesLimit`
        or add a new `typenamesLimit` (though I know what I’d do).
      - Test this (should be easy: this function is pure).

 7.   - Update `_updateData` to handle the case where the result
        includes `TypenameUpdateResult`s.
      - You may want to add `_updateTypename` in parallel with
        `_updateOwnData` and `_updateConnection`.
      - Decide what to do in the case where you get a typename update
        result for an object whose typename you already have recorded.
        What if the typename matches what you expected? What if it
        doesn’t? (Under what circumstances might this happen? Prior to
        this set of changes, are there any other problems that might
        arise under that same set of circumstances—i.e., is this a
        supported use case?)
      - Test this (will again require manually inserting rows).

 8.   - Update the initialization to no longer throw on a schema with
        unfaithful fidelities.
      - Update `_queryOwnData` to not query the `__typename` of an
        unfaithful field.
      - Update `_updateOwnData` to not update the `__typename` of an
        unfaithful field. Decide on reasonable error conditions.
      - Test this, which should now be possible with all the public
        APIs. Expand the end-to-end tests, like `extract`.

 9.   - Update `generateFlowTypes` to no longer throw on a schema with
        unfaithful fidelities.
      - Consider the right semantics for an unfaithful field whose set
        of actual typenames is empty. (There is a single correct
        answer.) Include a test case.

10.   - Update the GitHub schema to mark fields unfaithful in accordance
        with #996.
      - Clear the GitHub schema blacklist.
      - Run an end-to-end test against ipfs/js-ipfs-unixfs-engine.

I think that this should be sufficient, but I obviously haven’t
implemented it, so I may be missing anything.

It is reasonable to combine some subsets of these into fewer commits.
Some items may also be commuted.

At some point, you may find it useful to update the `SchemaInfo` type
with more auxiliary information about fidelity. Feel free to do so if it
is convenient, or not otherwise.

If it were me, I’d completely implement and test _all_ of these commits
before PRing _any_ of them. This is the kind of change where it’s quite
plausible that there’s some constraint that we haven’t yet realized will
bite us in the end, requiring changes to the overall design. Ideally,
I’d hold off until I had an end-to-end test actually working with the
SourceCred CLI to load ipfs/js-ipfs-unixfs-engine without a blacklist.

**Comment by wchargin** [comment]
(By the way, I wrote this^ on a plane with no internet, referring to
GitHub issues by inspecting my local mirror of SourceCred with an
SQLite3 shell. :+1: )

**Comment by wchargin** [comment]
As mentioned on Discourse, I’ve opened PRs 1662 through 1669:

  - #1662: [schema: add fidelity types][pr-1662]
  - #1663: [mirror: add typename support to query plan][pr-1663]
  - #1664: [mirror: add typename support to `UpdateResult`s][pr-1664]
  - #1665: [mirror: permit storing objects without known typename][pr-1665]
  - #1666: [mirror: request typenames in GraphQL queries][pr-1666]
  - #1667: [mirror: process typenames in query responses][pr-1667]
  - #1668: [mirror: permit and handle unfaithful fields][pr-1668]
  - #1669: [github: replace blacklist with fidelity annotations][pr-1669]

For consistency I’ve just requested @decentralion’s review on the
sequence, but @Beanow please feel free to chime in as well.

[pr-1662]: https://github.com/sourcecred/sourcecred/pull/1662
[pr-1663]: https://github.com/sourcecred/sourcecred/pull/1663
[pr-1664]: https://github.com/sourcecred/sourcecred/pull/1664
[pr-1665]: https://github.com/sourcecred/sourcecred/pull/1665
[pr-1666]: https://github.com/sourcecred/sourcecred/pull/1666
[pr-1667]: https://github.com/sourcecred/sourcecred/pull/1667
[pr-1668]: https://github.com/sourcecred/sourcecred/pull/1668
[pr-1669]: https://github.com/sourcecred/sourcecred/pull/1669

**Comment by Beanow** [comment]
Added myself for review on these out of curiosity, don't wait up if I don't get around to it. :smile:

**Comment by wchargin** [comment]
Yes, please feel free to review: especially the ones that haven’t yet
been reviewed, but I wouldn’t mind a second pair of eyes on any of these
changes, as they touch the core data loading pipeline. If something
seems problematic and out of line with the normal expectations of the
module, I’d love to hear about it.
